### ISSUE TITLE
[IAP] Restrict interactions when waiting for the Apple subscription popup

### ISSUE THREAD

**Issue by lmischner** [woocommerce/woocommerce-ios#10286]
**Describe the bug**
We don’t block interactions after the user taps “purchase [plan type]”. This leads to some oddities like:
(1) The user can think that they’re able to change which plan they want to purchase before the subscription dialog appears.
(2) The user can navigate pretty far away from the subscription screen (I got as far as another store) before the dialog appears, which could make it confusing as to which store is being upgraded.

**To Reproduce**
1. Tap 'upgrade now' in the banenr for a free trial site
2. select a plan
3. Tap "purchase [plan]
4. While waiting for the apple subscription popup, tap wherever you'd like.
Note how much you can do

**Screenshots**

https://github.com/woocommerce/woocommerce-ios/assets/103850310/dbf179e3-fd0c-4b8b-9e0b-aba2d6e8fe76

https://github.com/woocommerce/woocommerce-ios/assets/103850310/273a2949-e147-40d1-88cc-324e71d2a7e8

**Expected behavior**
I'd expect to not be able to do anything (Except cancel out of the workflow?) while waiting for the Apple screen to appear

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPad Air
- iOS version: iPadOS 15.6.1
- WooCommerce iOS version: built from trunk (14.3?)

**Comment by iamgabrielma** [comment]
Just for tracking purposes:

This issue could have caused the duplicated purchase attempt described here: p1690273582738139-slack-C025A8VV728

While both Apple and the WPCOM back-end has safeguards in place to not allow creating a duplicate purchase, the combination of waiting time until the process completes, and the issue described above, most likely is what triggered this duplication attempt by sending multiple requests to the endpoint.

I'm not sure yet how we'll tackle this, since we do not want to block the UI while the process is completed as could take a few minutes, but most likely we can disallow some interactions that could cause trouble.

**Comment by joshheald** [comment]
I've done a little investigation here.

> (1) The user can think that they’re able to change which plan they want to purchase before the subscription dialog appears.

I've got a fix for this, thanks for flagging it @lmischner . #10320

> (2) The user can navigate pretty far away from the subscription screen (I got as far as another store) before the dialog appears, which could make it confusing as to which store is being upgraded.

This is trickier. As @iamgabrielma says:

> I'm not sure yet how we'll tackle this, since we do not want to block the UI while the process is completed as could take a few minutes [...]

I agree with this. Ideally, if the merchant dismisses the Upgrades modal view after tapping Purchase, but while waiting for the IAP sheet to show, we'd cancel the IAP attempt which is still pending. Unfortunately, I can't find any way to do that.

> [...] but most likely we can disallow some interactions that could cause trouble.

Yes... I'm not too worried about attempts to upgrade a different store, that doesn't seem a likely error that people will face, but closing the modal because you don't think it's doing anything, and trying again seems more likely.

Two options come to mind:

1. Do nothing for now, and just see whether it turns out to be an issue. There are other protections against double charging, and we can't fix the fundamental issue anyway (e.g. if someone backgrounds the app while waiting for the sheet, it'll be presented over the home screen or a different app!)
2. Prevent the Upgrades modal from being dismissed for 15-30s while we're waiting for the sheet to be displayed. We could turn the `x` into a spinner while this is going on, but I wouldn't want to block it indefinitely.

What do you prefer @iamgabrielma @lmischner ?

**Comment by iamgabrielma** [comment]
> Two options come to mind:
> 1. Do nothing for now, and just see whether it turns out to be an issue. There are other protections against double charging, and we can't fix the fundamental issue anyway (e.g. if someone backgrounds the app while waiting for the sheet, it'll be presented over the home screen or a different app!)
> 2. Prevent the Upgrades modal from being dismissed for 15-30s while we're waiting for the sheet to be displayed. We could turn the x into a spinner while this is going on, but I wouldn't want to block it indefinitely.

I'd personally prefer the option 1 as feels more UX friendly than blocking the UI from being dismissed temporarily, and it could be also be miss-interpreted as the app being unresponsive during a purchase flow. If it actually turns out being a problem then we can iterate further with option 2 (or others).

**Comment by lmischner** [comment]
Is there a feasible 3rd option, where we could have a progress indicator (like a spinner wheel as part of a bottom banner) that does not block continued interaction with the app?
That probably introduces a lot more complexity, but would adhere to the usability heuristic of indicating system status to the user.

I imagine that would require a decent effort, though, since I don't think anything similar exists. We can wait and see if this winds up being a larger issue. In tracks or some other metadata, would it be easy to tell that this was the cause of a future issue?
