### ISSUE TITLE
[Mobile Payments] Pass `gatewayID` to existing IPP onboarding track events 

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#10596]
Context: pdfdoF-3HA#comment-4936-p2

We do not pass the _payment gateway ID_ as an explicit property to some IPP onboarding events, and rely on the event identifier itself to know if is WCPay or others. Ideally, we want to pass this explicitly into the event property list, for example as we do in `_card_present_collect_payment_success`

We should also leave a note in the track validation to clarify this (ref pdfdoF-3HA#comment-4945-p2 )

**Comment by jaclync** [comment]
From my understanding of the p2 comment thread & issue description, the plan for this issue is to add `plugin_slug` property to all `card_present_onboarding_*` events similar to how `plugin_slug` property is tracked in the `card_present_collect_payment_success` event. I'm going to work on it later, please correct me if I miss anything!

**Comment by iamgabrielma** [comment]
👋  Thanks for working on this @jaclync !

That's correct. Some events do track the gateway ID via the `plugin_slug` property specifically, while others don't, eg: in `*_present_onboarding_not_completed` we might know the gateway used by inferring from other properties like the description of the reason of failure, but there's no specific `plugin_slug` baked into the event.
