### ISSUE TITLE
Login: Site address check fails for some sites but succeeds on Android

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#11005]
**Describe the bug**
In some cases, the iOS app timeouts after 10 seconds when HEAD a request by the given site URL fails. Android is used GET and it works fine for the same site.

Internal discussions: p1696950932362829-slack-C03L1NF1EA3 & p1697531926595029-slack-C6H8C3G23.
CUW post: peaMlT-d1-p2.

**Comment by pachlava** [comment]
Adding a priority label to better align with the rules for MTTR metric.
See pdcxQM-2Su-p2

I'm setting `priority: high` since the issue originates from CUW, and it's potentially blocking users from logging in. Correct me if I'm wrong.

**Comment by itsmeichigo** [comment]
I thought we set `priority: high` only if a large number of users are affected. This issue should only happen to those with site connection issues causing the HEAD requests to time out, but we don't have that number.

**Comment by pachlava** [comment]
@itsmeichigo 👋 

The reasoning behind this activity (setting labels for already closed issues) is to calculate the MTTR metric for the apps. Instead of whitelisting (e.g. selecting all issues where the prio is `High`), we use blacklisting (ignore issues where prio is med or low), because whitelisting approach will miss the issues where `prio` or `type` labels weren't set at all. This inevitably leads to selecting more issues that should actually fall into MTTR selection, so I exclude them by adding the labels manually (in this case, setting the prio to `high` did not really exclude it, I did that for the better visibility).

For this one I initially set `high` because it comes from CUW, where, from my understanding, issues tend to be on the more prioritized side, no matter how many users they affect. `low` didn't feel right, and the repo had no `medium` priority initially - AFAIK, all issues with no prio labels are treated as medium. This however conflicts with our filtering rules for MTTR. I think I need to p2 this discussion. I've added `medium` prio to the repo yesterday, but I think it might affect some of your workflows.

I just tried recalculating the metric with this issue excluded (with prio set to `med`), and it doesn't really affect the value much - we still fit the target value. I'll keep it `med` while this matter is discussed in a p2, if that's fine 🙂
