### ISSUE TITLE
400 error on a products API request with empty status on app launch

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#11134]
**Describe the bug**

While inspecting the API requests on app launch, there's a 400 error on a `/wc/v3/products` API request with empty status `{"page":"1","per_page":"1","status":"","_fields":"id"}`. This happens for different sites, and is probably not expected for the feature it was added for. The response:

```
{
	"error": "rest_invalid_param",
	"message": "Invalid parameter(s): status"
}
```

**To Reproduce**

1. Relaunch the app in the logged-in state, and inspect the API requests --> notice a `/wc/v3/products` API request with an empty status parameter, which fails with 400

**Screenshots**

<img width="1394" alt="Screenshot 2023-11-13 at 11 23 58 AM" src="https://github.com/woocommerce/woocommerce-ios/assets/1945542/5bfc636f-379f-4ad6-9f93-60f7be33ae76">

**Expected behavior**

This products API request shouldn't fail, maybe the status isn't expected to be empty.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any
- iOS version: 17.0
- WooCommerce iOS version: 16.1

**Comment by rachelmcr** [comment]
It looks like this happens when we check if a store has products, for onboarding in the dashboard (line 238):

https://github.com/woocommerce/woocommerce-ios/blob/31cfe71ca249f5219d438459dbb2f3a2369b8aec/WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift#L234-L250

That isn't providing a product status to check, which defaults to `nil` here:

https://github.com/woocommerce/woocommerce-ios/blob/31cfe71ca249f5219d438459dbb2f3a2369b8aec/WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewModel.swift#L317

That's calling `ProductsRemote.loadProductIDs`, which falls back to an empty string when the product status is `nil` (line 379):

https://github.com/woocommerce/woocommerce-ios/blob/31cfe71ca249f5219d438459dbb2f3a2369b8aec/Networking/Networking/Remote/ProductsRemote.swift#L362-L387

According to the [REST API documentation](https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products), the `status` field should be used as follows:

> Limit result set to products assigned a specific status. Options: `any`, `draft`, `pending`, `private` and `publish`. Default is `any`.

If we don't provide a status parameter, we should either leave off that parameter from the request or provide `"any"` instead of an empty string. I'll check for other places where this could happen and update it.
