### ISSUE TITLE
[Tablet Orders] Billing information opens side-by-side rather than modally, ignoring for max-width

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#11767]
1. On an Order, tap on `Billing information`
2. Observe that opens by navigating to a new view side-by-side rather than modally, this ignores the max-with limitation set for the parent view.

<img width=600 src="https://github.com/woocommerce/woocommerce-ios/assets/3812076/4e81dded-d7d1-4f79-944a-1e81a04a354b"/>

**Comment by joshheald** [comment]
We'll have to set this separately; it's not the whole view controller that's width constrained, just the visible content.

From what I can tell, this is the only view currently which is pushed, instead of modally displayed. I'll just set the max width constraint separately now.

@joe-keenan did you intend for the max width to continue out to views which are pushed on to the stack?

**Comment by joshheald** [comment]
One more screen which needs this treatment – refund details:
![refund-details-full-width](https://github.com/woocommerce/woocommerce-ios/assets/2472348/8c14e9be-367b-46e4-8409-a5f302afafbf)
