### ISSUE TITLE
Require WPCom login before directing to the campaign creation flow for users logged in without WPCom

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#11782]

**Comment by itsmeichigo** [comment]
This issue seems more like a bug of the Blaze section on the Dashboard screen. I can reproduce the issue consistently following these steps:
- Create a JN site with Woo but no Jetpack.
- Log in to the app using site credentials or application password.
- Switch to the Products tab and create a new product then publish it.
- Switch to the My Store tab, notice that the Blaze section is displayed.
- Pull to refresh the dashboard, notice that the Blaze section disappears.

Expectation: the Blaze section should not appear after creating a new product when logged it without WPCom.
