### ISSUE TITLE
Errors decoding settings

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#1201]
Logging this so I don't forget about it. 

I am seeing these errors in the log on application start, which I can not reproduce consistently:

````
⚠️ Could not successfully decode SiteSetting value for woocommerce_all_except_countries
2019-08-20 08:00:12.369940+0800 WooCommerce[37054:2103065] ⚠️ Could not successfully decode SiteSetting value for woocommerce_specific_allowed_countries
2019-08-20 08:00:12.370047+0800 WooCommerce[37054:2103065] ⚠️ Could not successfully decode SiteSetting value for woocommerce_specific_ship_to_countries
````

It does not happen all the time, but I see them enough times to be concerning.

**Comment by ChrissiePollock** [comment]
I am seeing this in #3698127-zen as well.

**Comment by iamgabrielma** [comment]
The same appears on 4097440-zen:

> 2021/06/28 17:46:03:410 ⚠️ Could not successfully decode SiteSetting value for woocommerce_all_except_countries
> 2021/06/28 17:46:03:410 ⚠️ Could not successfully decode SiteSetting value for woocommerce_specific_allowed_countries
> 2021/06/28 17:46:03:410 ⚠️ Could not successfully decode SiteSetting value for woocommerce_specific_ship_to_countries

**Comment by joshheald** [comment]
From my site, this is a partial response from `wc/v3/settings/general`, which may help with debugging this issue.

```
{
  "data": [
  ...
    {
      "id": "woocommerce_all_except_countries",
      "label": "Sell to all countries, except for&hellip;",
      "description": "",
      "type": "multiselect",
      "default": "",
      "value": [],
      "options": {
        "AF": "Afghanistan",
        ...
        "ZW": "Zimbabwe"
      },
      "_links": {
        "self": [
          {
            "href": "https://taxbugcheck.mystagingwebsite.com/wp-json/wc/v3/settings/general/woocommerce_all_except_countries"
          }
        ],
        "collection": [
          {
            "href": "https://taxbugcheck.mystagingwebsite.com/wp-json/wc/v3/settings/general"
          }
        ]
      }
    },
    {
      "id": "woocommerce_specific_allowed_countries",
      "label": "Sell to specific countries",
      "description": "",
      "type": "multiselect",
      "default": "",
      "value": [],
      "options": {
        "AF": "Afghanistan",
        ...
        "ZW": "Zimbabwe"
      },
      "_links": {
        "self": [
          {
            "href": "https://taxbugcheck.mystagingwebsite.com/wp-json/wc/v3/settings/general/woocommerce_specific_allowed_countries"
          }
        ],
        "collection": [
          {
            "href": "https://taxbugcheck.mystagingwebsite.com/wp-json/wc/v3/settings/general"
          }
        ]
      }
    },
    {
      "id": "woocommerce_specific_ship_to_countries",
      "label": "Ship to specific countries",
      "description": "",
      "type": "multiselect",
      "default": "",
      "value": [],
      "options": {
        "AF": "Afghanistan",
        ...
        "ZW": "Zimbabwe"
      },
      "_links": {
        "self": [
          {
            "href": "https://taxbugcheck.mystagingwebsite.com/wp-json/wc/v3/settings/general/woocommerce_specific_ship_to_countries"
          }
        ],
        "collection": [
          {
            "href": "https://taxbugcheck.mystagingwebsite.com/wp-json/wc/v3/settings/general"
          }
        ]
      }
    },
    ...
  ]
}
```

**Comment by iamgabrielma** [comment]
I took a look into this one, and I was able to reproduce the warnings by adding a new country to the site's countries list array via this [snippet](https://woocommerce.com/document/add-a-new-country-to-countries-list/).

By adding the code to `functions.php` or via plugins like Code Snippets, then you can go to WooCommerce -> Settings and select our custom country to add some limitations, for example, select `Selling Location(s): Sell to all countries, except for...`.

Upon running the app, I could see the warnings in the simulator:

```
2022-06-19 17:57:15.955269+0700 WooCommerce[6878:3945602] ⚠️ Could not successfully decode SiteSetting value for woocommerce_all_except_countries
2022-06-19 17:57:15.955423+0700 WooCommerce[6878:3945602] ⚠️ Could not successfully decode SiteSetting value for woocommerce_specific_allowed_countries
2022-06-19 17:57:15.955558+0700 WooCommerce[6878:3945602] ⚠️ Could not successfully decode SiteSetting value for woocommerce_specific_ship_to_countries
```

I took a quick look at our [Networking SiteSettings model](https://github.com/woocommerce/woocommerce-ios/blob/trunk/Networking/Networking/Model/SiteSetting.swift). Some initial thoughts:

1 - We can't decode the API response for the custom country (This seems kind of expected, unless is added to core). By checking the HTTP response via Proxyman I see that the endpoint `path=/wc/v3/settings/products&_method=get` returns the data for these `settingID`'s, so the problem must not be getting it, but decoding it, or mapping it.
2 - There's no fallback, and failing to decode jumps directly to the [warning](https://github.com/woocommerce/woocommerce-ios/blob/trunk/Networking/Networking/Model/SiteSetting.swift#L47) because of a combination of `settingsID` not being Optional,  using `decode` rather than `decodeIfPresent`, as well as offers no nil-coalescence alternative if decoding the variable fails. 
3 - I'm not sure yet of the order on which this happens, but if we can't decode this `settingID`, [mapper](https://github.com/woocommerce/woocommerce-ios/blob/32b1587e2bc4aa5c4746f6dccefcbf1fad0cc0e7/Networking/Networking/Remote/SiteSettingsRemote.swift) and [remote](https://github.com/woocommerce/woocommerce-ios/blob/81ed7b18078c58d3337f53a91d0f09c802bf3c3f/Networking/Networking/Mapper/SiteSettingsMapper.swift) would fail to load for these as well. 
4 - It could be similar to [this problem](https://github.com/woocommerce/woocommerce-ios/pull/5252), where decoding fails because the data structure we're getting does not match the new type definition.

This could be entirely by design, so for the moment I'll just assign myself to the issue to investigate further :)

**Comment by iamgabrielma** [comment]
I checked the problem further with @joshheald and it seems that when we attempt to decode the API response we're [expecting](https://github.com/woocommerce/woocommerce-ios/blob/81ed7b18078c58d3337f53a91d0f09c802bf3c3f/Networking/Networking/Model/SiteSetting.swift#L44) `value` to be a String, however, this could be a mixed type. In this specific case, for `woocommerce_all_except_countries`, `woocommerce_specific_allowed_countries`, and `woocommerce_specific_ship_to_countries` its value is an Array, rather than a String, which fails to decode and throws the warning we're seeing.

I'll draft a PR shortly addressing the immediate scope of this issue and open a new one to deal with the bigger picture, which would involve a more flexible and long-term solution for checking and decoding different types coming from API responses.
