### ISSUE TITLE
[Tablet orders] Fix offline banners on Order tab

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#12112]
Offline banners no longer show on the order tab.

Enabling `shouldShowOfflineBanner` in one of the order view controllers does make them show up, but only in one half of the split view.

Enabling it in the `OrdersSplitViewWrapperController` doesn't do anything – but it's probably the right place for it to go, so that it covers the width of the screen on iPad.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by iamgabrielma** [comment]
I started to take a look into this one today, the reasons that the `shouldShowOfflineBanner` override doesn't seem to work when used in the `OrdersSplitViewWrapperController` is because it needs to be wrapped on a `WooNavigationController`, since the offline banner is triggered through its `WooNavigationControllerDelegate` delegate.

I believe this is done this way because we used to use the `WooNavigationController` as a wrapper for all our views, however, this is no longer the case with tablet support. That said, I see no reason why this "connectivity observer" and its methods generating the offline banner should be encapsulated in the current navigation controller delegate, so perhaps an initial solution could be to duplicate the specific "offline banner", and the connectivity observer bits into the `WooSplitViewController` ( I'll experiment with this today)

Noting as well that not only is broken for tablet support for Orders, but also for tablet support for Products, since both projects use the `WooSplitViewController` to create their wrappers. I dropped a message in corvid's channel so we don't duplicate efforts, and in case it wasn't logged in their project: p1709261954192889-slack-C06C3CZFHGD
