### ISSUE TITLE
Settings Page: WooCommerce Version Cell Misalignment with Adjacent Cells

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#12515]
In Settings, the WooCommerce version cell is not aligned with the other cells.

<img src="https://github.com/woocommerce/woocommerce-ios/assets/495617/85d4f586-8023-4532-86cc-8f21adbc7807" width=300 />

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by bozidarsevo** [comment]
@pmusolino did you get that on physical device or the simulator? Because when I run it on the simulator I get the bug but on my iPhone I do not get it:

![IMG_0814](https://github.com/woocommerce/woocommerce-ios/assets/6242034/67aac100-a17f-4c29-bb96-8911f28a9fb3)

![IMG_0815](https://github.com/woocommerce/woocommerce-ios/assets/6242034/7be34e98-0837-4b76-a4de-e31ba7cbebfc)

**Comment by pmusolino** [comment]
For me, it happens both in the simulator and on the device. :|

**Comment by bozidarsevo** [comment]
> device

which device are you using?

**Comment by pmusolino** [comment]
iPhone 13 Pro Max and iPhone 15 Pro Max (simulator)
