### ISSUE TITLE
[Woo POS] Refactor existing card payments code to use a `Presenting` implementation instead of UIViewControllers

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#12864]
We won't have a UIViewController to pass in to the adaptor from POS mode, instead, we should pass a "Null object", which implements a `Presenting` interface but doesn't do anything when its methods are called.

This will prevent any accidental misuse of a UIVC if we were to pass a real one in.

The POC touched on most but not all places these are used – in the real implementation, we shouldn't make any UIVCs in the adaptor. 

Areas we didn't tackle in the POC:
- Notice presentation 
- Receipt presentation
- Web view presentation

We should try to avoid the presentation completely in these cases, when used from SwiftUI. We can potentially rule all these out of scope for MVP, but it would be great, if possible, to receive e.g. the notice to present or the URL to show in a webview.

**Comment by jaclync** [comment]
Task list:

- [x] Add view controller presenting protocol to allow passing `UIViewController` or a Null implementation https://github.com/woocommerce/woocommerce-ios/pull/12896
- [x] Update `CardPresentPaymentPreflightController` to use `ViewControllerPresenting` instead of `UIViewController`. Fix UI/UX within `CardPresentPaymentPreflightController` where it assumes `UIViewController`
  - [x] Make sure UIKit import is removed from `CardPresentPaymentService` in https://github.com/woocommerce/woocommerce-ios/pull/12909
- [x] CardReaderConnectionController: open WC settings webview https://github.com/woocommerce/woocommerce-ios/pull/12932
- [x] CardReaderConnectionController: UIApplication.shared.open(adminUrl) - updated to always show in webview https://github.com/woocommerce/woocommerce-ios/pull/13169
- [x] [Skipped due to M1 scope - not supporting Tap To Pay] CardPresentModalBuiltInReaderCheckingDeviceSupport: WebviewHelper.launch(Constants.learnMoreURL.asURL(), with: viewController)
- [x] [Skipped due to M1 scope - not supporting receipt] CollectOrderPaymentUseCase.presentBackedReceiptFailedNotice: error notice https://github.com/woocommerce/woocommerce-ios/pull/12944/files - when the time comes, consider [refactoring the UI](https://github.com/woocommerce/woocommerce-ios/blob/28e3126911d9cbd6bc821dfee8527fd48dcaa5cb/WooCommerce/Classes/ViewRelated/Orders/Collect%20Payments/CollectOrderPaymentUseCase.swift#L529-L530)

**Comment by joshheald** [comment]
@jaclync – this one may be easier now that we have specific connection views/view models:

> CardReaderConnectionController: UIApplication.shared.open(adminUrl)

I think it's used for `Learn More` links, which we can add directly to the view and ignore it in the connection controller.

The built in alerts are for Tap to Pay, so we can ignore/minimally handle this one:

> CardPresentModalBuiltInReaderCheckingDeviceSupport: WebviewHelper.launch(Constants.learnMoreURL.asURL(), with: viewController)

It will also be handled directly on the view when we actually do it.

Let me know what you think... and whether we can move this issue now?

**Comment by jaclync** [comment]
> this one may be easier now that we have specific connection views/view models:
> 
> > CardReaderConnectionController: UIApplication.shared.open(adminUrl)
> 
> I think it's used for `Learn More` links, which we can add directly to the view and ignore it in the connection controller.

It's the WC settings admin URL to be opened outside of the app when the store isn't a WPCOM store. This one is a bit tricky since `UIApplication.shared.open(adminUrl)` is going to trigger the action within `CardReaderConnectionController` before the alert presenter can handle it differently. I'll see how I can make minimal changes to extract URL opening from the connection controller.

**Comment by jaclync** [comment]
Link to `UIApplication.shared.open(adminUrl)`: https://github.com/woocommerce/woocommerce-ios/blob/28e3126911d9cbd6bc821dfee8527fd48dcaa5cb/WooCommerce/Classes/ViewRelated/CardPresentPayments/CardReaderConnectionController.swift#L682-L683

**Comment by jaclync** [comment]
I've updated the task list https://github.com/woocommerce/woocommerce-ios/issues/12864#issuecomment-2141259637 to skip some tasks that are out of the M1 scope.
