### ISSUE TITLE
[Filtering Orders & Products] Can’t dismiss filter menu with swipe down gesture 

### ISSUE THREAD

**Issue by joe-keenan** [woocommerce/woocommerce-ios#13285]
The filter menu is non-destructive, so it should be dismissable by swiping it down.

https://github.com/woocommerce/woocommerce-ios/assets/95003933/d375b434-a442-449f-8dc8-6728a5ac10aa

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by rachelmcr** [comment]
I raised this question on p2 (p91TBi-bZ2-p2#comment-12912), just adding it here as well for reference:

Currently we show a discard changes prompt if there are changes to the selected filters. (As I understand it, we blocked the swipe gesture so we could enforce that discard changes prompt; I don’t think there’s a way to show that prompt when swiping to dismiss.)

Do you want to maintain the discard changes prompt? Or should we always allow merchants to dismiss the filters menu without any prompt?

Here are our options as I see it:

- Allow swiping to dismiss and remove the discard changes prompt.
- Allow swiping to dismiss but keep the discard changes prompt when you explicitly tap the Dismiss button.
- Allow swiping to dismiss as long as there aren’t any unsaved changes. Otherwise, block the swipe to dismiss and keep the discard changes prompt.

I'd lean toward the last option but I'm curious what you'd suggest here.
