### ISSUE TITLE
[Woo POS] M2: support for choosing which reader to connect to (multiple readers detected)

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-ios#13386]
This flow is supported in IPP but is not supported in the POS mode. When there are multiple readers found on bluetooth, the app should ask the user which one they want to connect to.

The app automatically prefers connection to the reader which it was connected to before - this behavior should remain unchanged.

P.S. This issue is a low priority for M2 and should be worked on after we are done with all the must-have tasks.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by joshheald** [comment]
We already show the multiple readers screen in POS if:

1. You don't have a known reader stored in the POS's KnownReadersProvider*
2. You tap "Continue searching" when the first reader is found.
3. And there's more than one supported reader in range.

*i.e. you've not connected to a reader yet within POS.

However, it's hard to repro in POS because we don't have a way to disconnect the reader within POS. 

In IPP, when you use the Disconnect button in the Manage Card Reader screen, that removes it from the IPP KnownReaderProvider, but not the POS one, as it's not a singleton.

For stores with multiple readers, we could add a disconnect button within POS, or find a way to make the existing IPP disconnect button clear down the POS reader provider, to make this easier. I prefer the former for simplicity and to avoid changing IPP.

pdcxQM-3PY-p2#comment-3105

**Comment by malinajirka** [comment]
Thanks for following up @joshheald ! Good news this screen already works! 

For the MVP, I believe we can rely on the existing `Disconnect` button in the Payments -> Manage Card Reader. In the end, if the app keeps connecting to a wrong reader, they can always turn it off. I'd personally consider closing this issue without changes, wdyt?

**Comment by joshheald** [comment]
> For the MVP, I believe we can rely on the existing `Disconnect` button in the Payments -> Manage Card Reader. 

It's fine for simply disconnecting a reader, but doesn't address this issue. 

The existing `Disconnect` button only removes the reader from the `KnownReaderProvider` for IPP, not the one used for POS. Tapping it will disconnect the reader, but the next time you try to connect to a reader within POS, it will automatically reconnect to the same known reader without giving the merchant any choice.

> In the end, if the app keeps connecting to a wrong reader, they can always turn it off.

That would work. It also shouldn't discover readers which are connected to other phones/tablets.

> I'd personally consider closing this issue without changes, wdyt?

Maybe... but I also think we could make it low priority, and have the task be to add a `Disconnect` button inside the `...` menu in POS.

**Comment by malinajirka** [comment]
> The existing Disconnect button only removes the reader from the KnownReaderProvider for IPP, not the one used for POS. Tapping it will disconnect the reader, but the next time you try to connect to a reader within POS, it will automatically reconnect to the same known reader without giving the merchant any choice.

Ohh, I see - on Android the app doesn't care whether you connected to the reader for IPP or POS, this is fully shared.

> Maybe... but I also think we could make it low priority, and have the task be to add a Disconnect button inside the ... menu in POS.

Sounds good.
