### ISSUE TITLE
Stats v4 off-by-one error when viewing "This Week"

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1357]
**Describe the bug**
Two bugs, possibly related, so they're both reported here. 1. The date label displays twice on the x-axis for "This Week." 2. The October bar is missing for "This Year", even though there are several sales reported for October.

<img width="532" alt="Screen Shot 2019-10-10 at 9 13 38 AM" src="https://user-images.githubusercontent.com/1062444/66577004-42a32a80-eb3e-11e9-83ff-d1be6ffa04f7.png">

**To Reproduce**
0. Have a store with sales on a Sunday, Monday, Tuesday. The site time zone is UTC based (in `wp-admin` Settings > General) with a non-zero GMT offset that is different from the device time zone.
1. Set your device region to the Netherlands. (Their regional calendar starts on Monday, not Sunday).
2. Build and run the app
3. Make sure v4 stats are activated
4. Navigate to "This week". 

Actual: There will be 2 labels for the Monday date. The first date and the data bar will have sales data for that Monday. The second / duplicated date will report sales for the next day, Tuesday.

**Screenshots**
Additional screenshots can be found in 2409158-zen. 

**Expected behavior**
The date labels on the x-axis are not duplicated.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: any
- iOS version: any 
- WooCommerce iOS version: 2.7.0.3

**WordPress Environment**
N/A

**Comment by jaclync** [comment]
I was able to reproduce this issue on the specific store, not the other test stores. With some debugging, I'm pretty sure the issue is from the empty timezone from the site. Because we display each stats plot in the site's time zone (a conclusion from p99K0U-1yG-p2), we calculate the start and end time parameters for each bar of the stats plot based on the site time zone. The site time zone is fetched [here](https://github.com/woocommerce/woocommerce-ios/blob/develop/Networking/Networking/Remote/AccountRemote.swift#L55-L66), and somehow it's returning an empty string for this particular site. It looks like this site is GMT+1, while the default value is GMT - I think the device time zone would be a better default here. However, there is daily saving time in a few countries (including many in Europe) and right now it's GMT+2 in the Netherlands but the site is GMT+1.

I also just checked all the 70 WP sites (just 3 of them have WC) my account has, and 53 of them have an empty time zone from the endpoint we use (https://public-api.wordpress.com/rest/v1.1/me/sites?fields=ID%2Cname%2Cdescription%2CURL%2Coptions&options=timezone%2Cis_wpcom_store%2Cwoocommerce_is_active).

The actions I'd propose:
1. Use the device time zone as the default time zone rather than GMT+0
2. Figure out why the time zone is empty, and what the default time zone is

**Comment by jaclync** [comment]
Update: it looks like the sites with empty timezone could be in different UTC regions (they only share the pattern of being in UTC+*). Now I remembered it might be possible to make stats v4 API requests without specifying a timezone. It doesn't seem to be a standard [ISO8601 format](https://en.wikipedia.org/wiki/ISO_8601) without a timezone (and no official API doc out there), but we can remove the timezone for this case so that the server considers the time in the site's time zone.

**Comment by jaclync** [comment]
Related issue: https://github.com/woocommerce/woocommerce-ios/issues/1376 for the issue in "Today" tab

**Comment by jaclync** [comment]
I updated the step 0 (prerequisite) to reproduce this issue in the description: this issue can be reproduced if the site time zone is UTC based with a non-zero offset that is different from the device time zone
