### ISSUE TITLE
Mobile Payments: Payment flow allowed despite ignoring location services requirement

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#13885]
Ref (video & discussion): p1725392360668769/1725392267.682619-slack-C025A8VV728

> I was able to collect TTP payment without allowing location permission, by ignoring the permission request modal. 

In some instances we've seen the payment flow continuing and collecting payment successfully when the user ignores the "Enable Location Services" request, which is required. This can happen both in IPP and POS.

A different issue regarding checking for location services earlier through the setup/payment flow could also be tackled together:  https://github.com/woocommerce/woocommerce-ios/issues/13857

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by staskus** [comment]
[Stripe Terminal SDK is responsible for disabling payment functionality if location is not granted](https://docs.stripe.com/terminal/payments/setup-integration?terminal-sdk-platform=ios):

> To reduce fraud risks associated with payments, and to minimize disputes, Stripe must know where payments occur. If the SDK can’t determine the location of the iOS device, payments are disabled until location access is restored.

There was a point made that:

> In some instances we've seen the payment flow continuing and collecting payment successfully when the user ignores the "Enable Location Services" request, which is required

However, according to the previous discussion (p1725392360668769/1725392267.682619-slack-C025A8VV728), the permission is not explicitly required for test transaction, that's why payment doesn't failed if location is not determined (not allowed / not disallowed).

> A different issue regarding checking for location services earlier through the setup/payment flow could also be tackled together: https://github.com/woocommerce/woocommerce-ios/issues/13857

We're planning to address location alerts in [Location pre-alert screen](https://github.com/woocommerce/woocommerce-ios/issues/14168) task. It will move the responsibility of asking for alerts from Stripe SDK to our app. This way we can ensure that payments are not permitted.

I'm closing this issue, it will be addressed it in the project.
