### ISSUE TITLE
[Order] Add Custom amount - Unable to tap CTA when keyboard visible

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#13955]
#### Issue

Unable to tap the "Add custom amount" CTA when the keyboard is visible.

Steps to reproduce
1. Start order creation
2. Add a few products
3. Tap "Add Custom Amount" -> "A percentage of the order total"
4. Enter a percentage and Name
5. Tap the CTA "Add Custom Amount" to save the changes
6. Notice that the tap doesn't work until we manually dismiss the keyboard

Tested in iPhone running iOS 18.0

#### Screen recording

https://github.com/user-attachments/assets/0e960556-fb47-44df-9643-b5ece57d73a6

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by iamgabrielma** [comment]
I reproduced this issue with (iOS16) once when I ran the app for the first time, but then I wasn't able to see it again on subsequent orders or runs. That said I have found some more inconsistencies with this view: 

- Sometimes adding the custom amount name first makes the percentage field non-tappable.
- Sometimes editing the custom amount name is not possible, only the amount. The field is not tappable/selectable.

At times I'm also seeing this issue with `SystemInputAssistantView` and `_UIRemoteKeyboardPlaceholderView` logged in the console:

```
2024-09-17 16:43:45.515810+0700 WooCommerce[66643:47865246] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x2800083c0 'accessoryView.bottom' _UIRemoteKeyboardPlaceholderView:0x1091c8060.bottom == _UIKBCompatInputView:0x10a421c80.top   (active)>",
    "<NSLayoutConstraint:0x2803181e0 'assistantHeight' SystemInputAssistantView.height == 45   (active, names: SystemInputAssistantView:0x10a418840 )>",
    "<NSLayoutConstraint:0x280001040 'assistantView.bottom' SystemInputAssistantView.bottom == _UIKBCompatInputView:0x10a421c80.top   (active, names: SystemInputAssistantView:0x10a418840 )>",
    "<NSLayoutConstraint:0x2800019f0 'assistantView.top' V:[_UIRemoteKeyboardPlaceholderView:0x1091c8060]-(0)-[SystemInputAssistantView]   (active, names: SystemInputAssistantView:0x10a418840 )>"
)
```

Since it's intermittent and due to the error above I think could either by related to the the timing of SwiftUI managing the keyboard vs view dismissal, and/or the layout inconsistencies when triggering the keyboard. I think we can try to call a "resign first responder" before fully view dismissal, as well as making it ignore the safe areas when appears, and see if this resolves the issue.

Are you able to reproduce this issue consistently with iOS18 @selanthiraiyan? Does it happens more than once or it's also intermittent in your end?

**Comment by selanthiraiyan** [comment]
Thanks for looking into this, Gabriel!

> Are you able to reproduce this issue consistently with iOS18 @selanthiraiyan? Does it happens more than once or it's also intermittent in your end?

I tested now with the iOS 18 official release, and I cannot reproduce this issue.

**Comment by iamgabrielma** [comment]
> I tested now with the iOS 18 official release, and I cannot reproduce this issue.

Gotcha, thanks for confirming! In any case I'll spend some time this week to try and find the cause, and see if we can make it better.
