### ISSUE TITLE
Orders screen doens't load when response has `taxes` with invalid `id` value

### ISSUE THREAD

**Issue by selanthiraiyan** [woocommerce/woocommerce-ios#14308]
Internal - peaMlT-Yo-p2

### Issue

The iOS app isn't able to parse the `/wc/v3/orders` response when any of the `taxes` under `line_items` have an invalid `id` value. The 
`OrderItemTax` mapper expects the id value to be `Int64`. 

To reproduce, use the following `line_items`. Note the `taxes` had a `String` `id` value where the app expects `Int`. 

```
 "line_items": [\
        \{\
          "id": 123,\
          "name": "Product name",\
          "product_id": 3122,\
          "variation_id": 3323,\
          "quantity": 1,\
          "tax_class": "",\
          "subtotal": "28.00",\
          "subtotal_tax": "3.64",\
          "total": "28.00",\
          "total_tax": "3.64",\
          "taxes": [\
            \{\
              "id": "stripe_tax_for_woocommerce__hst__13.0__India (GST)",\
              "total": "32.4",\
              "subtotal": "32.4"\
            \}\
          ],\
          "meta_data": [\
            \{\
              "id": 123,\
              "key": "pa_color",\
              "value": "white",\
              "display_key": "Color",\
              "display_value": "White"\
            \},\
            \{\
              "id": 124,\
              "key": "pa_logo-style",\
              "value": "avocado",\
              "display_key": "Logo Style",\
              "display_value": "Avocado"\
            \}\
          ],\
          "sku": "CHIANKD-A",\
          "price": 12,\
          "image": \{\
            "id": 123,\
            "src": "https://test.com/wp-content/uploads/2024/07/image.jpg"\
          \},\
          "parent_name": "Product name"\
        \}\
      ]
```
### Possible Solution

Check the possibility of ignoring the `taxes` with invalid `id` values and loading the rest of the orders. Currently, the app doesn't load any orders at all, which isn't a good user experience.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by rossanafmenezes** [comment]
Adding more information here regarding a recent report.
Context Slack convo: p1732107537674619-slack-C6H8C3G23
Ticket: 8961210-zd-a8c

Not exactly the same issue but also a parsing problem on iOS, probably due to a plugin modifying the order info but it is being parsed correctly on Android. 

For this user, searching for orders by customer name returns an error (`Sorry, we could not find this order` screen). Searching for order numbers, some orders work, some don't. They have two plugins that caught our attention (Advanced Product Search For WooCommerce and Ultimate Tax Exempt). That said, deactivating the plugins did not affect the search. App logs and screenshots of test sites are in Slack.

**Comment by malinajirka** [comment]
My two cents

I would personally suggest closing this issue as `won't fix`. We do not support all 3rd party extensions and it's not even our goal. 

If a 3rd party extension changes a type of a field which is defined in core, they are essentially making a breaking change to the API. Trying to consume partially data on the client can lead to critical bugs in certain scenarios. The app relies on the responses from the server.

For example, in the order creation, in certain flows the price of the product received from the server is used to calculate the total - if the app starts accepting partial data, we might end up in a situation that product price is received and tax is not received and we end up calculating total without a tax. This is just an example, which is actually handled in the existing flows - but I don't think we should create this precedent => if a response can't be parsed, we shouldn't try to parse just some parts of it and accept them as valid.

P.S. There might be cases in which it is fine, for example one order in the list of orders can't be parsed. But these are independent entities, that's why it is fine. But skipping tax lines in an order (dependent entities) feels quite risky.

**Comment by selanthiraiyan** [comment]
Thanks for your input, @malinajirka!

> If a 3rd party extension changes a type of a field which is defined in core, they are essentially making a breaking change to the API. Trying to consume partially data on the client can lead to critical bugs in certain scenarios. The app relies on the responses from the server.

@rachelmcr shared similar points here. peaMlT-Yo-p2#comment-2469

Also, I learned that we have previously done an exploration to list the faulty orders separately to let the users know which orders have invalid responses. pe5pgL-47W-p2

I will let @toupper decide whether to work on this issue or close it as won't fix.

**Comment by toupper** [comment]
I agree with @malinajirka here, I will mark it as won't fix 👍
