### ISSUE TITLE
[Issue Refunds] Add "Issue Refund" button

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#1487]
Order Details > Refunds

~For every order with the status `Processing`, add an "Issue Refund" button at the bottom of the Payment section. (Check with Android to make sure this is the only order status that shows the button.) Showing and hiding the button should be feature-flagged.~

Update 2020-09-09: Show the button at all times like on Android https://github.com/woocommerce/woocommerce-android/issues/1936#issuecomment-585610477. It will only disappear if it is not possible to refund the order (e.g. it's already refunded).

Update: 2020-09-21: Use latest styles

<img width="455" alt="Screen Shot 2020-09-21 at 10 11 28 AM" src="https://user-images.githubusercontent.com/562080/93784635-d86e8300-fbf2-11ea-95f3-5d9736b3b6b2.png">

**Comment by astralbodies** [comment]
Looks like the following happens:

1. If no payment method on an order, hide the button.
2. Order status == Pending, On Hold, or date paid == nil, hide the button.
3. If the order doesn't have a balance on it (order total - refunds == balance), hide the button.
4. Show the button otherwise.

That look right @0nko?

**Comment by 0nko** [comment]
That's correct @astralbodies :).

**Comment by shiki** [comment]
As agreed in CGPNUU63E-p1599186102050000-slack, we will be following what Android did https://github.com/woocommerce/woocommerce-android/issues/1936#issuecomment-585610477 and show the button at all times.
