### ISSUE TITLE
Log In: look into the string change from "Log in by entering your site address." to "Enter the address of your WordPress site you'd like to connect."

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1568]
Steps to reproduce:

- Update the `WordPressAuthenticator` pod to the latest
- Launch the app and log out
- Tap "Log in with Jetpack"

before `WPAuthenticator` update | after
-- | --
![IMG_8E7F2A77AA8A-1](https://user-images.githubusercontent.com/1945542/70249484-6342d600-17b7-11ea-88eb-1c651974a12e.jpeg) | <img src="https://user-images.githubusercontent.com/1945542/70225020-34157000-1789-11ea-865c-0142d76ccc41.png"/>

**Comment by jaclync** [comment]
I looked at the commit history in the `WordPressAuthenticator` shared library to see what changed the title of the logging in by site address button. It looks like the string was changed in https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/123 for this WPiOS issue https://github.com/wordpress-mobile/WordPress-iOS/issues/12188 but the string doesn't seem to be used in the button in the issue's screenshot. @shiki do you know if the change of the logging in by site address button title from "Log in by entering your site address." to "Enter the address of the WordPress site you'd like to connect." was intentional in https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/123 ? (since you created the issue 😄)

**Comment by shiki** [comment]
> do you know if the change of the logging in by site address button title from "Log in by entering your site address." to "Enter the address of the WordPress site you'd like to connect." was intentional in wordpress-mobile/WordPressAuthenticator-iOS#123

Hi! 👋 The change of the button title is not intentional. It should have changed the instructions. 

<img src="https://user-images.githubusercontent.com/198826/71819199-765ff480-3048-11ea-80f0-17f71c825f46.png" width="320">

I think [PR#123](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/123) changed the wrong line of code since I had to redo the fix in [PR#170](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/170) ([0c3a93f](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/commit/0c3a93ff5bf435f8b059fb4973dbf1d6ffc492d4)). 

I'm sorry I didn't think of checking what [PR#123](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/123) actually changed. 😞

**Comment by shiki** [comment]
Verified that this is still happening. Moving this to _To do_ for now.

**Comment by jaclync** [comment]
Since we added SIWA, the login with email screen no longer shows the alternative login options (they are available in the bottom sheet in the prologue screen). Also, we are adopting UL&S starting release 5.8 which does not show this string either. Closing this now!
