### ISSUE TITLE
Order Details: product quantity title in the 2-column header view isn't aligning to the trailing edge

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1647]
Something changed in 3.3, and the title of the 2-column header view in Order Details > Product list is off:

WCiOS 3.2.0.4 | WCiOS 3.3
-- | --
![IMG_9735](https://user-images.githubusercontent.com/1945542/71139113-39be8b80-2248-11ea-9f28-8cb556c4ceba.PNG) | ![IMG_9736](https://user-images.githubusercontent.com/1945542/71139114-3a572200-2248-11ea-80f1-63e7e541d9d1.PNG)

**Comment by mindgraffiti** [comment]
@jaclync if you find using a code-generated view for this to be a better option, I'm all for it. This view as had layout issue after layout issue pop up, partly because it does things a table section header shouldn't do (two columns) and partly because stackviews don't remain consistent between OS versions (an issue popped up when iOS 12 was released, and now 13.x has weirdness).
