### ISSUE TITLE
Orders/Notifications: Reviews tab gets a badge when a new order is received

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1735]
**Describe the bug**

After receiving a new order, the Reviews tab in the app gets a badge even though there are no new reviews.

**To Reproduce**
1. Open the app and visit the Reviews tab to clear any badge on the Reviews tab icon.
2. Exit the app.
3. Receive a new order on your store.
4. Tap the push notification for the new order.
5. Confirm the new order details open (expected) but the Reviews tab also gets a badge (unexpected).

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/72536960-2f0d0b80-3873-11ea-9b62-cd1b1d4bfa09.png" width="50%">

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.3
- WooCommerce iOS version: 3.4.0.0 TestFlight build

**Comment by rachelmcr** [comment]
This is related to the issue reported in https://github.com/woocommerce/woocommerce-ios/issues/1388 but the issue here is with the badge on the Reviews tab in the app (versus the app badge).

**Comment by jaclync** [comment]
Since the Reviews tab still observes the app's badge number init/update, we probably want to refactor how we observe and set the app's badge number:

- Update the Reviews tab badge based on the default `NotificationCenter` (similar to [how we update the Orders tab count](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/Notifications/PushNotificationsManager.swift#L176)) instead of the app's badge number
- Update the app's badge number when viewing the Order Details and Review Details from a push notification (decrement by one)

Let's test this when the app receives the new order push notification in the foreground, background, and closed state. Also, let's make sure the app's badge number is updated as expected.

**Comment by rezzap** [comment]
This was reported by a user in 2691883-zen. Waiting for more details from them.

**Comment by DustinHartzler** [comment]
> "It is just the badge popping up, not an actual notification. I mean I am getting a notification that I have a new order, but every time I get an order I have to load the review page to get the badge to go away."

Came to report the same thing. From me :)
