### ISSUE TITLE
Improved Stats: Visitor count can be wrong

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1795]
**Describe the bug**

When I select the current month on the "This Year" tab, I expect the stats to match what I see on the "This Month" tab. However, the Visitors count doesn't match — the visitor count for "This Month" is too high.

It looks like the Visitors count for "This Month" may simply be adding up the total visitors for each day in the month. However, this is not accurate if the same visitor comes to the site on multiple days in the month.

**To Reproduce**
1. Log in to a store with WC Admin where at least one visitor has returned to the store on multiple days in the same month.
2. Enable the Improved Stats feature.
3. Select the "This Year" tab, select the current month, and note the number of visitors displayed.
4. Select the "This Month" tab and note that the number of visitors is different.

**Screenshots**

This Month tab (in January)|This Year tab (January selected)
-|-
<img src="https://user-images.githubusercontent.com/8658164/73373428-828a4b00-42b0-11ea-854a-0c1246aef31c.png">|<img src="https://user-images.githubusercontent.com/8658164/73373455-8ddd7680-42b0-11ea-8d9b-6399afe9de17.png">

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.3
- WooCommerce iOS version: 3.5.0.0 TestFlight beta

**Comment by jaclync** [comment]
I noticed incorrect visitor count in "today" tab - it is showing 10, however I didn't visit the site at all today and "this week" shows 1 visitor count 😓 After some debugging, it seems like the "today" tab isn't getting the correct `SiteVisitStats` since both "today" and "this week" end on Sep 30 and one overrides the other in storage. That's why "today" tab is getting the visitor count on "this month" tab.

today | this week | this month
-- | -- | --
![IMG_7717](https://user-images.githubusercontent.com/1945542/94669258-93112a80-0343-11eb-949e-96cb60fe455e.PNG) | ![IMG_7718](https://user-images.githubusercontent.com/1945542/94669268-960c1b00-0343-11eb-8fc8-b30a9aa224c5.PNG) | ![IMG_7719](https://user-images.githubusercontent.com/1945542/94669272-973d4800-0343-11eb-9377-9ec2fffe2967.PNG)

"This month" and "this year > this month" visitor count also don't match:

this month | this year > this month
-- | --
![IMG_7719](https://user-images.githubusercontent.com/1945542/94669272-973d4800-0343-11eb-9377-9ec2fffe2967.PNG) | ![IMG_7720](https://user-images.githubusercontent.com/1945542/94669481-dd92a700-0343-11eb-9f5e-9ab8c26dbc13.PNG)

**Comment by jaclync** [comment]
I'd recommend we add another attribute to `SiteVisitStats` that is unique for all 4 tabs (like `timeRange` enum). Also, we can use this opportunity to add an attribute for site ID. This requires schema migration, so holding off until another sprint.

**Comment by rachelmcr** [comment]
A user reported this issue for their store (internal ref: 3402266-zen). They noted the same scenario that I saw: When you are on the "This Year" tab and select a specific month, the visitor count for that month is off.

**Comment by reginabally** [comment]
A similar report from the Woo iOS app review:

> We started an online business 2 mths ago This app was supposed to keep me up to date with traffic to the site etc as I’m not at the website My business partner is 
I had to learn from our advertising company that the results this app was showing were nearly 600 unreported visits to the site Thank god the ppl running our ad campaign are on the ball because you clearly are not
I’m now looking at your reviews and wondering why my business partner choose your app at all The reviews are mostly bad

Date of review: Oct 13, 2020
iOS app version: 5.1

**Comment by jaclync** [comment]
Right now we save `SiteVisitStats`'s `granularity` to the period unit like `day`/`month` for all 4 time ranges. However, there are 3 tabs with granularity `day` and their `date` could also be the same on certain days of the month. For example, today is Jan 25 (Monday) and the EOW (`date` for "This Week" tab) is Jan 31 (Sunday) which happens to be the same as the EOM (`date` for "This Month" tab). In the database, we now only have 3 `SiteVisitStats` entities:

<img width="735" alt="Screen Shot 2021-01-25 at 2 20 11 PM" src="https://user-images.githubusercontent.com/1945542/105671681-128fbe80-5f1e-11eb-877e-61cdd5ffee50.png">

while there should be 4 for the 4 tabs. Let's update `SiteVisitStats`'s `granularity` to `StatsTimeRangeV4` so that each `SiteVisitStats` is unique for all time ranges.

**Comment by rachelmcr** [comment]
This should be resolved by the changes in https://github.com/woocommerce/woocommerce-ios/pull/8427, which fetch the visitor stats from the stats summary endpoint. This endpoint is designed to provide the total count for the given time period (total day's visitors for Today tab, total week's visitors for This Week tab, etc).
