### ISSUE TITLE
Stats: update dashboard charts

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#1896]
Ref: p91TBi-2rF-p2

- [ ] Let's always show 3 labels on the y-axis:
  - If all y values are non-negative, the minimum y-axis is at $0
  - Otherwise, if any negative y values, we show [-max, 0, max] where `max` is the max magnitude from all y values
<img width="487" alt="Screen Shot 2020-02-25 at 11 04 31 AM" src="https://user-images.githubusercontent.com/1945542/75211378-a8771280-57be-11ea-9535-361d2ff60cd8.png">

- [ ] See if we can add an 8px between the right edge of y-axis labels and the left edge of x-axis

<img width="401" alt="screen-shot-2020-02-21-at-11 44 28-am" src="https://user-images.githubusercontent.com/1945542/75211384-aca33000-57be-11ea-8e9a-9365be6fdbd9.png">

**Comment by Garance91540** [comment]
Update here on design request: 
Removing this: <strike> Otherwise, if any negative y values, we show [-max, 0, max] where max is the max magnitude from all y values </strike> since it turned out to look a bit weird for example when the max negative revenue is quite small (ie $50) and the max positive revenue quite big (ie$13,000)

Adding this:
- Make the zero axis a dashed line (plz check that colors for all axes are iOS Gray 4)
- Make top corners of data bar rounded (this helps understanding where is the top and where is the bottom of the data bar, so when there;s negative revenue users understand well where to look at)
<img width="908" alt="Screen Shot 2020-03-20 at 4 47 23 PM" src="https://user-images.githubusercontent.com/28450084/77180777-b3297c80-6aca-11ea-9516-37eef6fd5dab.png">

**Comment by Garance91540** [comment]
I'm also seeing on my store a double minus sign before the negative values, as well as negative value and the zero bar even when all the values are positive:

![IMG_0301](https://user-images.githubusercontent.com/28450084/81564554-344d1380-9398-11ea-9984-54ead4370784.PNG)

**Comment by jaclync** [comment]
> I'm also seeing on my store a double minus sign before the negative values, as well as negative value and the zero bar even when all the values are positive:

this issue is fixed separately in #2431

**Comment by jaclync** [comment]
Closing this since we just worked on Home Screen M2 - My Store tab updates, and the design in this issue is outdated.
