### ISSUE TITLE
Order List: the padding of the bottom loader indicator is wrong

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#1922]
It seems to me that the padding of the bottom loader in the Orders table view is wrong, it seems too close to the above cell. It should look like in the product list.

## Screenshots
<img src="https://user-images.githubusercontent.com/495617/76248802-56b09c80-6242-11ea-8ddc-b92b3740ed90.png" data-canonical-src="https://user-images.githubusercontent.com/495617/76248802-56b09c80-6242-11ea-8ddc-b92b3740ed90.png" width="300" />

## Mobile Environment
Please include:
- Device: iPhone 11 Pro simulator
- iOS version: 13.2.2
- WooCommerce iOS version: 3.8

**Comment by Garance91540** [comment]
Ah weird I can't reproduce it! (it shows up well spaced on my iPhone 11)

24px vertical padding should do the trick, thanks for spotting this 👍

**Comment by pmusolino** [comment]
Thank you @Garance91540! Can I ask you what version of the app are you using?

**Comment by Garance91540** [comment]
3.6.0.1

**Comment by shiki** [comment]
I may have caused this. I'll include it as part of the Orders List Redesign project.

**Comment by pmusolino** [comment]
Good first issue for a trial.

**Comment by ealeksandrov** [comment]
I have a question about this logic for different layout of `FooterSpinnerView`:

https://github.com/woocommerce/woocommerce-ios/blob/e89d49660bd8de4269ce34fb6754469dd3cd65a9/WooCommerce/Classes/ViewRelated/ReusableViews/FooterSpinnerView.swift#L35-L49

What are use cases to have such difference?

The only good example with working `.grouped` spinner that I found - `ReviewsViewController`.
And it works because it has `sectionFooterHeight="18"` in nib file:
https://github.com/woocommerce/woocommerce-ios/blob/ce58b6df7ff98bfee6073be333d205fd40ff7268/WooCommerce/Classes/ViewRelated/Reviews/ReviewsViewController.xib#L22

In current issue spinner is broken because it was a switch from `.plain` to `.grouped` table view + new table view has collapsed height setting for `sectionFooterHeight` (instead of 18 in example above):
https://github.com/woocommerce/woocommerce-ios/blob/fa624059875c37f730c1ffafefe0fe060a01b26e/WooCommerce/Classes/ViewRelated/Orders/OrderListViewController.swift#L230

From what I see - we can have zero height setup for all footers everywhere and use just `.plain` constraints setup in `FooterSpinnerView`. Am I missing something?

**Comment by pmusolino** [comment]
Good catch @ealeksandrov! 

> From what I see - we can have zero height setup for all footers everywhere and use just .plain constraints setup in FooterSpinnerView. Am I missing something?

From your observations, my answer is yes. Can you do a spin just to check if using the `plain` constraints as default for all the `tableViewStyle` doesn't create any regression on other tableview/view controllers?

**Comment by ealeksandrov** [comment]
Sure I'll do a check and create draft PR. I'm only not sure if I can correctly find all usage cases and verify them - there are 9 search results for `FooterSpinnerView()` 🙂
