### ISSUE TITLE
Launch screen stretched on iPhone 11 Max

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-ios#1932]
I don't know if this is only happening on the Max or if it's all sizes. Reporting so we don't forget.

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-10 at 15 57 26](https://user-images.githubusercontent.com/373903/76358859-320f0000-62e8-11ea-95da-33f6ff052bfa.png)

**Comment by jaclync** [comment]
I also noticed this distorted logo today - I checked the [asset](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Resources/Assets.xcassets/LaunchLogo.imageset/woo-icon-120x120.pdf) is 82 × 48 (aspect ratio 1.708) while the image view size in [`LaunchScreen.storyboard`](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Resources/Base.lproj/LaunchScreen.storyboard) is 171x125 (aspect ratio 1.368) - maybe that's why the logo appears compressed horizontally?

My suspicion is that the [launch screen was cached](https://stackoverflow.com/questions/33002829/ios-keeping-old-launch-screen-and-app-icon-after-update) during testing (we probably didn't test by reinstalling the app) in https://github.com/woocommerce/woocommerce-ios/pull/1855, and we can fix this by updating the size of the logo image view in `LaunchScreen.storyboard`

**Comment by pmusolino** [comment]
As Jaclyn said, I also believe that the launch screen was cached during testing, but it's strange that it wasn't noticed in `LaunchScreen.storyboard`. My fault. I'm opening a PR that fix that. 👍
