### ISSUE TITLE
Add Tracking: clean the Shipping Provider when the user presses back

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#1949]
There is a bug and at the same time an improvement to do in this area.

When you try to add a Shipping Provider, select it, and you press back (so you don't save changes) if you try to reopen the Add Tracking screen you can see that the Shipping provider is populated with the old value. This happens not only to the order on which you are making these changes, but also on the other orders. See this GIF for more details:
![bug add tracking](https://user-images.githubusercontent.com/495617/76541912-91097c00-6484-11ea-8b8c-208b6f8ad800.gif)

The improvement is to implement, like on Android, a system that allows the user to discard changes, following the pattern that we currently use on Products, showing the Action Sheet with the `Discard changes` button.
![Simulator Screen Shot - iPhone 11 Pro - 2020-03-12 at 17 08 42](https://user-images.githubusercontent.com/495617/76542354-20169400-6485-11ea-9678-241da7d421f0.png)

**Comment by joshheald** [comment]
I can reproduce this still.

Prioritization:
Severity – Medium: bug with a workaround
Impact – Low: 4.5% of users open shipment tracking each month.
= Low

**Comment by joshheald** [comment]
N.B. This plugin is required for repro: https://woocommerce.com/products/shipment-tracking/?quid=bf4a4531475ca8cdb30e88430db700bf

**Comment by iamgabrielma** [comment]
> When you try to add a Shipping Provider, select it, and you press back (so you don't save changes) if you try to reopen the Add Tracking screen you can see that the Shipping provider is populated with the old value. This happens not only to the order on which you are making these changes, but also on the other orders.

@joshheald and I took a look into this one and seems that is a side effect of deliberate behavior introduced as a [feature](https://github.com/woocommerce/woocommerce-ios/issues/848), with this, we discovered a related bug that affects how this field is actually populated as well:

The way we [insert or update the tracking provider](https://github.com/woocommerce/woocommerce-ios/blob/ea86d3e0219ad7cfe1efb7c2d379144ac5a3a510/Yosemite/Yosemite/Stores/AppSettingsStore.swift#L479-L504) in this list seems to indicate that we want to save the most recent tracking provider, which makes sense as merchants may want easy access to the one they use the most rather than scrolling through the whole list of providers, however, what does instead is checking if the provider exists in our preselected list, and if it does, uses its position as index to update the list, which actually causes that the order doesn't change when we use [.first](https://github.com/woocommerce/woocommerce-ios/blob/ea86d3e0219ad7cfe1efb7c2d379144ac5a3a510/Yosemite/Yosemite/Stores/AppSettingsStore.swift#L435) to load these. If the preselected provider doesn't exist, it doesn't work as expected either, because we're still loading the `.first` item, but we're [appending](https://github.com/woocommerce/woocommerce-ios/blob/ea86d3e0219ad7cfe1efb7c2d379144ac5a3a510/Yosemite/Yosemite/Stores/AppSettingsStore.swift#L495) it to the end of the list.

In a nutshell: You never get the latest tracking provider you've used unless you use only one, which defeats the feature's purpose.

Proposed solution:

1. Keep the tracking provider pre-population as originally intended. This happens when initializing the model, we [preload](https://github.com/woocommerce/woocommerce-ios/blob/81ed7b18078c58d3337f53a91d0f09c802bf3c3f/WooCommerce/Classes/ViewModels/ManualTrackingViewModel.swift#L250-L260) a list of provider names that we've used previously.
2. While we want this pre-population to happen, we don't want this to be saved/loaded if the merchant dismisses it (original reported issue), this seems to happen because we call this function on [didSet()](https://github.com/woocommerce/woocommerce-ios/blob/81ed7b18078c58d3337f53a91d0f09c802bf3c3f/WooCommerce/Classes/ViewModels/ManualTrackingViewModel.swift#L118-L122), we can remove it from here and hook it only to the "Add" button.
3. Resolve the way we create the `newPreselectedProvider` list. We can alter the way these values are saved in the list so it fixes the bug, however, a simpler solution seems to be to get rid of the list entirely and use only one value representing the latest used shipment provider, as it would seem we're not using this list anywhere else for any other check or functionality across the app, it is only used here.
 
What do you think? Anything I may be missing? Any feedback is appreciated.

For visibility, I've also shared this in ref: p1656409752134409-slack-CGPNUU63E , and p91TBi-9lY-p2
