### ISSUE TITLE
Products: Title field is huge/not edited inline

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#1957]
**Describe the bug**

According to the designs, the title field should be edited inline:

![image](https://user-images.githubusercontent.com/8658164/76618350-4f2e1380-6520-11ea-8331-7aa3ea07c6ac.png)

However, the current implementation has the title field use a full-screen editor (same as the description field), encouraging very long, multi-line text.

**To Reproduce**
1. Go to the Products tab.
2. Select a product.
3. Select "Title."

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/76618427-771d7700-6520-11ea-95e6-0ee734285058.png" width="50%">

**Mobile Environment**
Please include:
- Device: iPhone XS
- iOS version: 13.3.1
- WooCommerce iOS version: 3.8.0.0 TestFlight beta

**Comment by jaclync** [comment]
I couldn't find the original discussion where I asked Kylea about editing the product name UX, but I believe it was updated in the design (under the "Simple products flow" page) back in November when I created https://github.com/woocommerce/woocommerce-ios/issues/1419:

<img width="536" alt="Screen Shot 2020-03-16 at 1 27 19 PM" src="https://user-images.githubusercontent.com/1945542/76725889-8a337f80-678a-11ea-8d28-e9cf7381f3ab.png">

As I recall, we moved edit product name to fullscreen for the following reasons:
- "Done"/discard changes UX is consistent across all editable fields. with inline editing, there's no way to discard changes except for leaving the edit screen
- implementation cost - we already have an editable plain text view

I agree though it might encourage longer title, maybe we can some non-blocking warning if the title gets longer than like 20 characters on the edit title screen? @Garance91540

**Comment by Garance91540** [comment]
Hi @jaclync ! This is currently how we have implementing it on Android, that's why I don't know why we chose to implement it differently on iOS. 

Would it be long to make the Title an edit inline field? This would be my preferred solution so:
1. we keep iOS and Android consistent
2. we avoid users an extra click when they can enter data from the product page 
3. we avoid long titles (we'll need to find a solution anyway to implement character limit on this field if we went with the full-screen view)
