### ISSUE TITLE
Bottom sheet UI framework

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#2054]
- [x] Add bottom sheet code from WPiOS https://github.com/woocommerce/woocommerce-ios/pull/2154
- [x] Add generic bottom sheet list selector UI https://github.com/woocommerce/woocommerce-ios/pull/2155
- [x] iPad improvements to fit to height https://github.com/woocommerce/woocommerce-ios/pull/2272
- [x] Wrapper for presenting a bottom sheet (discussion: https://github.com/woocommerce/woocommerce-ios/pull/2155#discussion_r412303534) https://github.com/woocommerce/woocommerce-ios/pull/2273
- [ ] Remove BottomSheet from WCiOS and use it from WPUI https://github.com/woocommerce/woocommerce-ios/pull/2285

We've had several cases where we want to show a bottom sheet UI, examples:
- [x] [Products tab sort options](https://github.com/woocommerce/woocommerce-ios/issues/2036) https://github.com/woocommerce/woocommerce-ios/pull/2156
- [x] [Edit product - more details](https://github.com/woocommerce/woocommerce-ios/issues/2053)

It probably makes more sense to use a third-party framework rather than creating our own as the states could get complicated with tablet and portrait/landscape orientation support.

Thuy did some research on the bottom sheet framework options in p99K0U-2h3-p2, and I briefly tried 2 of them (`PanModal` and `FloatingPanel`) during hack week and picked `FloatingPanel` for the hack project p77Llu-dwV-p2 (some comparisons in the p2 post).

**Comment by jaclync** [comment]
gathering some initial thoughts here from @pmusolino and @shiki !

2 related p2 posts:
- p99K0U-2h3-p2
- p77Llu-dwV-p2

Questions:
- Third-party framework or our own?
- Have you used or heard of good recommendations for any third-party bottom sheet frameworks?
- (Optional) Any thoughts on [`PanModal`](https://github.com/slackhq/PanModal) and [`FloatingPanel`](https://github.com/SCENEE/FloatingPanel) from looking at their GitHub README?

**Comment by pmusolino** [comment]
Thank you @jaclync for opening this issue. It seems something to which we must find a solution immediately.

> Third-party framework or our own?

If there is a third-party library that is well supported by their creator, has a good number of users and has all the functionalities that we need, I prefer a third-party library. It is one less thing to develop and maintain in the future. Another option could be to use a third-party library until we have time to develop ours (perhaps an external pod).

> Have you used or heard of good recommendations for any third-party bottom sheet frameworks?

I never used a bottom sheet different from the Apple one (which is not what we are looking for). I found [here](https://github.com/vsouza/awesome-ios#alert--action-sheet) a long list of alert and action sheet, but no one of these seems what we are looking for. 

> (Optional) Any thoughts on PanModal and FloatingPanel from looking at their GitHub README?

At the moment `FloatingPanel` seems to be the closest library to our needs because we can put inside every View Controller that we want. The other libraries instead seem to force you to add single buttons or single cells, and you cannot add completely customized components.

**Comment by shiki** [comment]
> Third-party framework or our own?

I agree with what Paolo said.

> Have you used or heard of good recommendations for any third-party bottom sheet frameworks?

No experience, unfortunately.

> (Optional) Any thoughts on PanModal and FloatingPanel from looking at their GitHub README?

I'd leave this decision to you since you have more experience with it. 🙂It looks like you got the barcode scanner to work with `FloatingPanel` so we could go with that. Also, `FloatingPanel` seems to have more documentation which is always a plus.

If possible, we should code it in a way that we can switch to a different library later if `FloatingPanel` gives us too much trouble. This is usually not easy though so it's okay if we can't.

**Comment by pmusolino** [comment]
An update here paNNhX-5K 💯
