### ISSUE TITLE
Pull-to-refresh for Empty States

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2124]
<img src="https://user-images.githubusercontent.com/198826/78911072-0bf19280-7a43-11ea-974b-d91c771b5288.png" width="240">

## Is your feature request related to a problem? Please describe.

1. I created a new site and linked Jetpack.
2. I logged in on the app.
3. I opened the Products tab on the app. It is empty as expected. The "No products yet" Empty State is shown. 
4. In wp-admin, I created a new product and published it.
5. I went back to the app. The Products tab was still visible. 
6. The Empty State is still shown and there is no obvious way for me to refresh the Products tab. 

## Describe the solution you'd like

In WCAndroid, you can pull-to-refresh on the Empty State view:

<img src="https://user-images.githubusercontent.com/198826/78911316-64c12b00-7a43-11ea-979b-fb0c78eee92b.png" width="240">

Perhaps we can do the same for iOS? 

## Environment 

- iPhone Xs
- iOS 13.1
- WC 4.0-beta

---

What do you think, @Garance91540? 

Sorry to bother you a lot today. 😐

**Comment by Garance91540** [comment]
> Perhaps we can do the same for iOS?

For sure,  didn't realize it wasn't enabled on the Products tab!

> Sorry to bother you a lot today. 😐

haha please continue! I really appreciate your design-centered, thorough reviews of our apps always making sure we're providing the best experience to our users!

**Comment by leonardodamato** [comment]
Hi guys, how are y'all?

Is there anyone already taking care of this? Otherwise I can do it. 

As I could see, the current scenario is that an `Overlay View` is being added to the main view, which is loaded in front of the `TableView`, making it impossible to `pullToRefresh`.

My suggestion would be instead of add this Overlay View to the main view, set it as backgroundView for the TableView when empty then `nil` otherwise. 

If you guys think that this is a good approach to solve it, I can go ahead. 😀

**Comment by shiki** [comment]
Hi @leonardodamato! Thank you for contributing! Good to you around here again. 🙂 

> My suggestion would be instead of add this Overlay View to the main view, set it as backgroundView for the TableView when empty then nil otherwise.

I'm not sure if that's the best approach. 🤔 Based on our experience, adding views on top of the main `UITableView` would just lead to complex and hard to debug UI code. I've also personally found some difficulty in making VoiceOver work well on views that are placed on top of `UITableView`. 😐 

I wonder if we can have a separate `UIViewController` instead. In https://github.com/woocommerce/woocommerce-ios/pull/2078, we made it so that the main table, and ghost table, and the other views have their own `UIViewControllers` (or UIView). Do you think that's possible?

**Comment by leonardodamato** [comment]
Hey @shiki! Thanks ☺️

I agree with you that this overlay that is being applied on the current code isn’t a good approach.

I did some tests, and removing this overlay view and then setting a `emptyStateView` to `tableView.backgroundView`, seems like it is a simple and efficient method to do this. 

I can create the PR with this solution for you guys to analyze it.  What you think?

**Comment by leonardodamato** [comment]
Hey @shiki, 

This is the result I've achieved using the view as a tableView.backgroundView instead of an overlay. 

What do you think? 
| | |
| --- | --- |
| ![2020-04-15 18 01 50](https://user-images.githubusercontent.com/2797522/79317058-9016af00-7f48-11ea-827b-300849517bf9.gif) | ![2020-04-15 17 59 33](https://user-images.githubusercontent.com/2797522/79317084-986eea00-7f48-11ea-85b6-b2bbd40dbc2c.gif) |

**Comment by shiki** [comment]
@leonardodamato Thanks for the GIFs!

I'm not sure if this is the way to go. When using the background view, it looks like it is static and doesn't scroll when you pull to refresh. 🤔 

I guess this isn't as straightforward as I originally thought. 😐

**Comment by leonardodamato** [comment]
Oh I see. I will have a look and see whether I can do it 😄Thanks for showing the right way to do it!

**Comment by shiki** [comment]
@leonardodamato It turns out that I may be able to work on this along with #1961. Just letting you know! 🙂
