### ISSUE TITLE
Failing unit tests setting Arabic language

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#2132]
We have some failing tests in `DoubleWooTests`, `NSDecimalNumberWooTests` and `ReviewViewModelTests` when the language in the simulator is configured to Arabic.

<img width="559" alt="Schermata 2020-04-13 alle 11 53 29" src="https://user-images.githubusercontent.com/495617/79111853-99075500-7d7d-11ea-876c-2fbc2af79033.png">

**Comment by pmusolino** [comment]
Update.
I re-tested this issue, and now I also see 15 failing tests in `CurrencyFormatterTests`

<img width="402" alt="Schermata 2020-09-04 alle 15 34 01" src="https://user-images.githubusercontent.com/495617/92245063-14e87200-eec4-11ea-9567-0dcb9ea93dfb.png">

**Comment by rachelmcr** [comment]
These tests are failing because we are making assertions on localized, human-readable strings and Arabic uses different numerals. Any time we convert a number to a string with `NumberFormatter().string` it localizes the string, which returns e.g. `١,١٧` instead of `1,17` (equivalent strings but with different numerals).

Do we intend for our tests to pass in any supported locale? Or do we only mean to test them in English?

I'm wondering because in `CurrencyFormatterTests`, for example, we set English as the locale in a number of tests using this constant:

```swift
private let sampleLocale = Locale(identifier: "en")
```

If we want to force the tests to always run with `EN` as the locale, we could add that to the unit test plan configuration (under `UnitTests.xctestplan` > Configurations > Localization). That way, regardless of the simulator's language, the tests will always be run in English without having to force it in specific tests.

If we want these unit tests to work in all languages, though, we'll need to account for cases where the localized string uses different numerals than English. One possibility would be to set the expected value based on the simulator locale, taking into account the different expected result with Arabic. For example, in `testDecimalSeparatorIsLocalized` in `CurrencyFormatterTests`:

```swift
let expectedResult = Locale.current.languageCode == "ar" ? "١,١٧" : "1,17"
```
