### ISSUE TITLE
Order Details → Separate Product Name from Variation Name

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2280]
⚠️ This is not as easy as it looks as it may involve a few API fetches in order to get the variation names. See p91TBi-2Lt-p2.

![image](https://user-images.githubusercontent.com/198826/81869558-71004280-9531-11ea-99d8-8e3de92d5ea6.png)

- Title: product name only
- Subtitle: Variant selected (if any), quantity and price. This will make it easier to visually separate the product from the variations selected, especially if several have been selected for the same product (ie “White” and “Medium”)

Ref p91TBi-2CE-p2#comment-627

**Comment by shiki** [comment]
Related to https://github.com/woocommerce/woocommerce-ios/issues/1127 and blocked by https://github.com/woocommerce/woocommerce-rest-api/issues/9.

**Comment by jaclync** [comment]
@woocommerce/ios-developers would love to get your thoughts on implementing this, since it involves schema change:

The variation attributes are in each `OrderItem`'s `meta_data` field in the API response `GET /orders/{{order_id}}`:

```
"line_items": [
  {
    "id": 720,
    "name": "(Variable) Chocolate bars",
    "product_id": 846,
    "variation_id": 1275,
    ...
    "meta_data": [
      {
        "id": 6041,
        "key": "darkness",
        "value": "99%",
        "display_key": "Darkness",
        "display_value": "99%"
      },
       ...
     ]
  }
]
```

We have a few ways to store the variation attributes from `meta_data` in `Storage.OrderItem` if its `variationID` is non-zero:

- Add a new relationship `attributes: [GenericAttribute]` or `variationAttributes: [GenericAttribute]`. Its `id`/`key`/`value` are from `id`/`display_key`/`display_value` in the API response `meta_data` field respectively.
- Create a new model `OrderItemAttribute` that contains all the attributes from `meta_data` (`id`/`key`/`value`/`display_key`/`display_value`) even though we're only using `display_key` and `display_value` for this issue. Then add a new relationship `attributes: [OrderItemAttribute]`.
- Add a new attribute `details: String`: this freeform string can potentially be parsed from other fields in the future, but is less flexible in how we display the variation attributes (like comma separated)

In `Networking.OrderItem`, I'll add the corresponding field and parsing the meta data with a decodable struct (similar to `ProductVariation.attributes: [ProductVariationAttribute]`).

I personally prefer adding a relationship of attributes, what do you think?

**Comment by pmusolino** [comment]
@jaclync I'd say that I prefer the new relationship `attributes: [GenericAttribute]` because in that way we can do some queries on the stored properties. Using a generic string offer a lot of freedom, but we can't do anything without parsing it first.

I've just a question about the `GenericAttribute` model. Will we use only `id`, `key` and `value` for the moment? What will happens if in the future we will need to parse new fields just for the Orders?
Personally, I'd say to use a new model just for Orders `meta_data`. I don't think that in the future we want to add new fields under `GenericAttribute`, having them shared with other non-related models.
What do you think?

**Comment by jaclync** [comment]
> I've just a question about the GenericAttribute model. Will we use only id, key and value for the moment? What will happens if in the future we will need to parse new fields just for the Orders?
Personally, I'd say to use a new model just for Orders meta_data. I don't think that in the future we want to add new fields under GenericAttribute, having them shared with other non-related models.
What do you think?

For using `GenericAttribute` model, I was planning to just keep the existing attributes (`id`, `key`, `value`) for this issue (getting `GenericAttribute`'s `id`/`key`/`value` from `id`/`display_key`/`display_value` from the API response `meta_data` respectively). Maybe we can name it `variationAttributes: [GenericAttribute]` to be explicit. Would it be better to create a different model to include all the variation details including `key` and `value` that aren't user-facing? I'll add this to the idea list in any case.

@shiki do you know if it's possible for an order line item's `meta_data` to be non-empty and not just variation attributes like by a third-party plugin?

**Comment by shiki** [comment]
I am inclined towards having a separate model, `OrderItemAttribute`.

> Create a new model OrderItemAttribute that contains all the attributes from meta_data (id/key/value/display_key/display_value) even though we're only using display_key and display_value for this issue. Then add a new relationship attributes: [OrderItemAttribute].

Even though it looks like they are all stored in the same database in the API, we should probably consider `ProductVariation` attributes and `OrderItem` attributes to be separate entities in the app. I think this would make it easier to understand. And probably easier to do migration later if we need to restructure either `ProductVariation` or `OrderItem`. 

Another thing is that in my short experience with working with the API, I was immediately confused with what was stored in `meta_data` and where they came from. 😬 

### OrderItemAttribute 

We could probably clarify things further by renaming the properties to our understanding of the API:

- `metaID` (just for reference)
- `name` (the `display_key`). The "key" here is intentionally generic in the API to [_save database disk space_](https://take.ms/CHQ5O) I think. But using `key` doesn't help in our context. 
- `value` (the `display_value`)

---

> @shiki do you know if it's possible for an order line item's meta_data to be non-empty and not just variation attributes like by a third-party plugin?

Yes, it looks like it's possible for plugins to modify the result of that, unfortunately. There's a [woocommerce_order_item_get_formatted_meta_data](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-order-item.php#L295) filter. 🙈 So it's probably best to be defensive in reading the API.

**Comment by jaclync** [comment]
Related discussion: CGPNUU63E/p1602796453088400-slack
