### ISSUE TITLE
Stats → Show Red Icon on Top of the Sync Icon in the Banner

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2465]
Continuation of #1946. 

<img src="https://user-images.githubusercontent.com/198826/85429177-98d4c400-b53b-11ea-8852-d8caa3f9ce3e.png" width="320">

**Comment by Ecarrion** [comment]
Hey @Garance91540 

I tried to add the pink dot indicator by code but it turned out to be very tricky due to some dynamism between dark mode and RTL orientation.

We have decided that the best way to move forward is to get a composed image that includes the sync icon + the dot.
I can grab that from Figma for the light version, but could you do one for dark mode, please?

Thanks!

**Comment by Garance91540** [comment]
Hi @Ecarrion sounds good, I added the dark mode designs in the Figma file.
