### ISSUE TITLE
Use NSPersistentStoreCoordinator instead of FileManager in Core Data Backups

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2473]
From @jaclync 

> Let’s update how we copy and remove the SQLite file to use NSPersistentStoreCoordinator API instead of FileManager.

Ref p91TBi-2YF-p2

**Comment by astralbodies** [comment]
Taking this on next week.

**Comment by astralbodies** [comment]
I am going to close this issue for now. Upon further investigation, the two areas we do backups from (#2816 removes one of these) require the DB to be in a migrate-able state. The operations Apple suggested do object copy from one persistent store to the other rather than copying the actual SQLite file. In our case, we’re trying to backup outside the scope of Core Data. I left the backup operation as is in the iterative migrator and used that logic in the CoreDataManager for the recovery operation.
