### ISSUE TITLE
Edit Products: Updating sale price does not show the "Update" button

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2637]
@jaclync @pmusolino  Not sure if this is expected or not.

1. Edit a simple product.
2. Navigate to Price
3. Change the Sale Price
4. Tap Done.
5. Notice that the Sale price in the product details list is still the _old sale price_.  ⚠️ 
6. Notice that the Update button is not shown. ⚠️ 
6. Opening the Price page again shows the newly edited price. ⚠️ 

Changing the regular price shows the Update button. 

I used the recent `develop` (67e2151).

Here is a video: https://drive.google.com/file/d/15ntU9kXOpAn3_9P2AA9-Mp89P-i9622J/view?usp=sharing

_Please ignore the "Update Error" on that because I was testing a failing API call_. 😁

**Comment by jaclync** [comment]
Great find Jayson! I was able to reproduce this issue and it looks like this line skips the sale price while comparing two `Product`s:

https://github.com/woocommerce/woocommerce-ios/blob/faee100732aeb94752aa66e8f06fd786042cd336/Networking/Networking/Model/Product/Product.swift#L595

I don't think the alternative types could affect the comparison, since it's comparing two `Product`s with fixed types after decoding from API response.
