### ISSUE TITLE
Login: Status bar is white on white in light mode

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-ios#2654]
**Describe the bug**
When your iPhone or iPad is in light mode the status bar is white and you can't see the time and such on the login prologue screen.

**To Reproduce**
1. Launch the app in a logged-out state.

**Screenshots**
![IMG_0119](https://user-images.githubusercontent.com/373903/90186280-89286d80-dd7d-11ea-9034-44fc575d945f.PNG)
![IMG_0120](https://user-images.githubusercontent.com/373903/90186288-8af23100-dd7d-11ea-912c-8f7cd06dac79.PNG)
![IMG_0020](https://user-images.githubusercontent.com/373903/90186397-b83edf00-dd7d-11ea-9e2c-dc82fadf5922.PNG)
![IMG_0021](https://user-images.githubusercontent.com/373903/90186399-b8d77580-dd7d-11ea-8bc8-286405ae148e.PNG)

**Expected behavior**
The status bar should be visible on all screens. I don't know if this is an issue with WP Authenticator or us.

**Mobile Environment**
Please include:
- Device: iPad Pro 11" & iPhone 6s Plus
- iOS version: 13.x
- WooCommerce iOS version: 4.8 (SIWA branch)

**Comment by jaclync** [comment]
After some debugging, it turned out there is a status bar style option we didn't override in Woo and it's default to `lightContent`. It's [used in login prologue's superclass `LogInViewController`](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/blob/81d30cd61f1027bff1d7146fdcd12bfc832a64d5/WordPressAuthenticator/Signin/LoginViewController.swift#L44-L48) (I forgot about the superclass 🤦🏻‍♀️).

Setting the [status bar style option](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/blob/81d30cd61f1027bff1d7146fdcd12bfc832a64d5/WordPressAuthenticator/Authenticator/WordPressAuthenticatorStyles.swift#L116) to `default` in Woo fixes this. I'll update the PR https://github.com/woocommerce/woocommerce-ios/pull/2644
