### ISSUE TITLE
[Product Details] "Categories" section is displayed by default

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-ios#2726]
On the product details page, the "Categories" section is displayed by default, but it should only be displayed if user has previously selected it in the "More Details" bottom sheet

**Comment by pmusolino** [comment]
Hi @Garance91540 👋

Unfortunately, it seems that is not possible to hide Categories, because by default a Product has always a category. Also if you create a new product without selecting a category, a category will be automatically assigned. If you remove it, it will be automatically reassigned. So a Product has always at least a category that will be shown. Is this behavior different on Android?

**Comment by jaclync** [comment]
it's interesting that I'm able to have no categories for a product on my test site, I wonder if this is some site configuration?

<img src="https://user-images.githubusercontent.com/1945542/91518215-57d5a300-e922-11ea-9f8f-9b28c776b076.png" width="300" />

I checked G's site, and the "Uncategorized" category cannot even be deleted 🤔 

<img width="328" alt="Screen Shot 2020-08-28 at 11 40 57 AM" src="https://user-images.githubusercontent.com/1945542/91518691-6f615b80-e923-11ea-9f40-af146e407731.png">

On my test site, I have no category with this default and warning. I saw in [this post](https://wordpress.org/support/topic/stop-from-having-default-category/) that there's no way to disable a default category, I'm not sure if my test site is an edge case.

**Comment by Garance91540** [comment]
Mmm I see.  I wonder if we could set a rule to not display the "Categories" row if the category equals "Uncategorized". Because really what's the value of seeing the "Uncategorized" row? WDYT?

**Comment by pmusolino** [comment]
I thought about using this workaround since the category id differs from site to site. Unfortunately, the category name also changes based on the language set on the site. For example, on my website configured with the Italian language, I see “Senza Categoria”. I don't see at the moment any way to hide the default category :( 

> Because really what's the value of seeing the "Uncategorized" row?
I agree, there is no value for the user. 💯

**Comment by pmusolino** [comment]
@jaclync really strange :/ I'm not able to replicate it

**Comment by jaclync** [comment]
Yea like @pmusolino mentioned, the default category could be different strings per locale. Also, the user can pick a different category as the default so the default category can be any string. Unless the default category is available in the API (it's not currently available based on the [documentation](https://woocommerce.github.io/woocommerce-rest-api-docs/#product-categories)) we can't tell which category is the default.

I think it's fine for the default category to show up in the product details, since it belongs to the product anyway. Otherwise the user might think the product has no categories?

**Comment by Garance91540** [comment]
I see, it kind of defeat the purpose of the bottom sheet to show by default sections that are not needed, but if there's no way to hide the "Categories" row if a product doesn't have a category, there's not much we can do 🤷‍♂️

**Comment by jaclync** [comment]
closing this issue for now - if we hear from users about seeing the default category, let's talk to the core team about adding support for the default category.
