### ISSUE TITLE
Dashboard UX: Days tab is confusing

### ISSUE THREAD

**Issue by stephhjacq** [woocommerce/woocommerce-ios#275]
Reports look great! 
Quick question about the Days view--is this 7 days? It doesn't match what I see on desktop:

![http://cld.wthms.co/P4DfgS](http://cld.wthms.co/P4DfgS+)
Full Image: http://cld.wthms.co/P4DfgS+

If this is intentional, the inconsistency may cause confusion/support questions.

**Comment by mindgraffiti** [comment]
In StatsV4, we have changed the "DAYS" tab to say "This Week". It may still confuse users, because the WC-Admin plugin shows "Last 7 days" in their sales reports instead of "This Week." We aren't going to fix this issue because our mobile user research findings state that users are demanding a "This Week" view, not a rolling "Last 7 days" view.

This bug can be reopened if HEs encounter any users that mention they are confused over the "This Week" format.

**Comment by jaclync** [comment]
In stats v4, "DAYS" tab (the first tab) becomes "Today". I just checked WC admin on web, and it seems like "This month" is shown by default. We could potentially show "This month" for stats v4 by default to mirror the web behavior? @mindgraffiti

**Comment by mindgraffiti** [comment]
@jaclync good question! We aren't following the web defaults, we're following our user research. The designs show the default as "Today" because that's what our users have told us that's what they expect to see.
