### ISSUE TITLE
Add siteID to SiteVisitStats and TopEarnerStats

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2916]
From @jaclync in https://github.com/woocommerce/woocommerce-ios/pull/2897#issuecomment-701757804. Continuation of #2897. 

We should also add `siteID` to the `SiteVisitStats` and `TopEarnerStats` entities. Both in Core Data and in Networking models. 

Doing this would help us eliminate the need to delete entities when switching stores: 

https://github.com/woocommerce/woocommerce-ios/blob/6c58e2fa3d37a3e5099c179ef54854f9a5402586/WooCommerce/Classes/Authentication/Epilogue/SwitchStoreUseCase.swift#L39-L73

And also helps us with ensuring that we're not showing data from different sites.

**Comment by jaclync** [comment]
Working on this! Since we don't delete all `TopEarnerStats` when switching stores, I noticed that the app shows top performers from another store when the current store has no orders for this week 😨 

store 1 | store 2
-- | --
![Simulator Screen Shot - iPhone 11 - 2021-01-22 at 15 24 45](https://user-images.githubusercontent.com/1945542/105460230-6f913780-5cc6-11eb-8caf-4d63c177b76a.png) | ![Simulator Screen Shot - iPhone 11 - 2021-01-22 at 15 24 55](https://user-images.githubusercontent.com/1945542/105460240-728c2800-5cc6-11eb-850f-e6be46d46d47.png)
