### ISSUE TITLE
Default cursor location when editing inventory 

### ISSUE THREAD

**Issue by warrendholmes** [woocommerce/woocommerce-ios#2921]
**Describe the bug**
When I update the inventory of a variation, the cursor is at the front of the inventory number and trying to move it around isn't a great experience. By default it should be at the back of the inventory number so its easy to edit. Hope that makes sense!

**To Reproduce**
1. Go to a variable product.
2. Click on Varations.
3. Select Inventory.
4. Click in the inventory field and see the cursor is at the front. 

**Mobile Environment**
Please include:
- Device: iPhone 11 Pro
- iOS version: 14.0.1
- WooCommerce iOS version: 5.0

**Comment by jaclync** [comment]
Hmm I can't seem to reproduce the issue on iPhone 11 iOS 13.7 simulator and iPhone XR iOS 14.0 device 🤔 

Did you mean the cursor in this screenshot is in the front for you?

<img src="https://user-images.githubusercontent.com/1945542/96071383-9d4f2f00-0ed4-11eb-9735-dc226144d188.png" width="300" />


This is a screencast from my testing:

![simulator](https://user-images.githubusercontent.com/1945542/96071278-582afd00-0ed4-11eb-9cb6-33cbf5cb6781.gif)

**Comment by shiki** [comment]
I can reproduce this by tapping on the first number of the stock value. However, if I tap on the last number, the cursor will be in the last position. I can reproduce this same behavior in the Notes app's search field and other app's text fields. I believe this is the expected behavior. 

With that, I'm going to close this. 🙂
