### ISSUE TITLE
Shipping Labels M2: add a link to order details to view information about shipping label creation

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-ios#2975]
We need to provide a link below the **Create shipping label** to find out how to create shipping labels. This will only be displayed if the **Create shipping label button** is displayed.

## Subtasks

- [ ] Show the info link in order details https://github.com/woocommerce/woocommerce-ios/pull/3769
- [ ] Navigate to the new info screen with a link "Learn more" to https://woocommerce.com/products/shipping/ (we can probably reuse `EmptyStateViewController` for this screen)

<img src="https://user-images.githubusercontent.com/22608780/95947008-59dcbe00-0e0b-11eb-89f7-9f2c8e5e081d.png" width="300"/>. <img src="https://user-images.githubusercontent.com/22608780/95947034-63febc80-0e0b-11eb-9fbd-bca696ed0793.png" width="300"/>

**Comment by jaclync** [comment]
@woocommerce/mobile-designers I'd like to confirm some design differences between the shipping label creation info screen and another use case of a reusable UI component:

This is how the design looks like for shipping label creation info screen:

<img width="245" alt="Screen Shot 2021-03-02 at 5 19 46 PM" src="https://user-images.githubusercontent.com/1945542/109626426-822b4600-7b7b-11eb-85ae-28bfabe1fbdd.png">

Since this screen looks a lot like the empty state UI like in the orders tab (I hardcoded to show the empty state), I was wondering if we could reuse the design here to be more consistent (screenshots below). 

Using the empty state UI link style | Orders tab empty state
-- | --
![Simulator Screen Shot - iPhone 11 - 2021-03-02 at 17 14 34](https://user-images.githubusercontent.com/1945542/109626785-e948fa80-7b7b-11eb-8cba-c575496900a6.png) | ![Simulator Screen Shot - iPhone 11 - 2021-03-02 at 17 17 15](https://user-images.githubusercontent.com/1945542/109626800-ecdc8180-7b7b-11eb-8200-1ef138dc8f32.png)


The differences between the dev screenshot and design are:

- The details text color ("Cut the post office line...") is dark (design) vs. gray (empty state component)
- The "Learn more" CTA is a link (design) vs. a primary button (empty state component)

Do you think it's better making the two design customizations above, or following the current empty state text color & button style? I can implement the design customizations, but just wanted to confirm before doing so!

**Comment by Garance91540** [comment]
Hi @jaclync , thank you for bringing this up! Actually, both of those screens are obsolete...

I shared the [new illustration library back in December](https://woomobilep2.wordpress.com/2020/12/15/illustration-library-update/), but we haaven't had the chance to update it yet in the app, and I didn't update designs in WC ship either. I just did!

**Comment by jaclync** [comment]
Hey @Garance91540! I couldn't find the screen for shipping label creation information in the p2 and Figma ([this](https://user-images.githubusercontent.com/1945542/109626426-822b4600-7b7b-11eb-85ae-28bfabe1fbdd.png) is the current design in the WCShip Figma). Could the updated version be added to the Illustration Figma as well?

For the illustration update on the orders tab empty states, we'll work on that separately and focus on shipping label creation info screen for this issue.

**Comment by Garance91540** [comment]
Hi @jaclync , I just tagged you on Figma so you can grab the assets directly from there for light and dark mode

<img width="283" alt="Screen Shot 2021-03-03 at 6 08 19 PM" src="https://user-images.githubusercontent.com/28450084/109843630-92aaf180-7c4b-11eb-9ff2-abcc38a36cd2.png">

makes sense that we'd be tackling the order tab empty state separately!
