### ISSUE TITLE
[Issue Refunds] Confirmation → Dismiss Keyboard when Scrolling

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#2980]
Continuation of #2768, there should be a way to dismiss the keyboard if the user has entered something in the Reason for Refund text field which causes the keyboard to be present. I'm not sure if we have a standard for this at the moment. 

I'm thinking the behavior could be to dismiss the keyboard when:

- When tapping outside of the text field. 
- When scrolling down or up.

**Comment by rachelmcr** [comment]
I ran into this as a blocker while beta testing (5.6.0.0 TestFlight beta). Entering a Reason for Refund prevented me from completing the refund, because I couldn't dismiss the keyboard or scroll far enough to reach the Refund button at the bottom of the screen:

<img src="https://user-images.githubusercontent.com/8658164/100736333-7b4d3580-33ca-11eb-82e3-4459182cb111.PNG" width="300px">

The only way I could get around it was to go back to the previous screen, continue the refund, and not enter a Reason for Refund the second time around.

**Comment by Ecarrion** [comment]
Hi @rachelmcr , this should be fixed with https://github.com/woocommerce/woocommerce-ios/pull/3248
I'll redirect the branch to the `release/5.6`
