### ISSUE TITLE
Display the product type cell also in the Product creation screen

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#3050]
We always should display the product type selected (even if in read-only) in the product details page during the product creation if possible. It gives users feedback on what they previously selected (1. select product type on bottom sheet > 2. see product type selected on product details page). Discussion here p5T066-1zC#comment-6119

<img width="203" alt="Screen Shot 2020-10-22 at 16 51 34" src="https://user-images.githubusercontent.com/495617/96906319-eafe0580-1499-11eb-8154-6b0cf24f5b3b.png">

**Comment by jaclync** [comment]
Just wanted to share why product type was hidden in the first place (ref p91TBi-3f7-p2 and p91TBi-3dS#comment-1649 is the discussion) - the reason was because we don't support adding a variable product now, we decided at the time to hide the product type until we support variable product creation in M5.
