### ISSUE TITLE
Linked Products: Add Tracking

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#3151]
These events are supposed to answer the question “Are people using the new feature?”. If they don't, please let me know. 🙂 I'm also avoiding proposing too many event triggers. If you feel like these are still too many then you're probably right! 

## The Button

<img src="https://user-images.githubusercontent.com/198826/99010707-bf55c480-2507-11eb-9977-36f8b280b944.png" width="300">

Event Name | Trigger
--------|-------
`product_detail_view_linked_products_tapped`        |  When the Linked products button is tapped as shown above.     

This is already implemented in Android.

## Linked Products

<img src="https://user-images.githubusercontent.com/198826/99008473-78fe6680-2503-11eb-949b-b907e9dd4dab.png" width="300">

Event Name | Trigger | Custom Properties
--------|-------|----
`linked_products`        |  When this screen is shown.      |  `action="shown"`
`linked_products` | When the Done button is tapped. This indicates that the user has changed something and is definitely using the linked products feature. | `action="done"`

## Linked Products Selector 

<img src="https://user-images.githubusercontent.com/198826/99009362-2faf1680-2505-11eb-8947-cd74aa5b4b35.png" width="300">

Let's rename the existing grouped products selector events so they are more generic. We'll use `context` to differentiate between grouped products, cross-sells, and upsells.

Old Event Name | New Event Name | Custom Properties
--------|------|--
   `grouped_product_linked_products_add_tapped`    |  `connected_products_selector` | `action: "add_tapped", context: "grouped_products OR upsells OR cross_sells"`
   `grouped_product_linked_products_added`    |  `connected_products_selector` | `action: "added", context: "grouped_products OR upsells OR cross_sells"`
   `grouped_product_linked_products_done_button_tapped `    |  `connected_products_selector` | `action: "done_tapped", context: "grouped_products OR upsells OR cross_sells"`
   `grouped_product_linked_products_delete_tapped `    |  `connected_products_selector` | `action: "delete_tapped", context: "grouped_products OR upsells OR cross_sells"`

---

Corresponding Android issue: https://github.com/woocommerce/woocommerce-android/issues/3159

**Comment by pmusolino** [comment]
@shiki Since there are some existing events in the product list selector and we are reusing all these components, should they match the events used before in grouped products? 
Consider that I make this flow generic, so we can pass new events for "products add tapped", "products added", "products done button tapped", and "delete tapped". 

These are the existing events for grouped products:
- `grouped_product_linked_products_add_tapped`
- `grouped_product_linked_products_added`
- `grouped_product_linked_products_done_button_tapped`
- `grouped_product_linked_products_delete_tapped`

**Comment by shiki** [comment]
@pmusolino Do you think **not tracking** those events would be faster to implement for Linked Products? Maybe pass an option like `ProductSelectorVC(trackEvents: Bool = false)`. 

I'm challenging the notion that we're probably tracking too many events that we don't use. 😬 If we do end up needing them, we can always add them later. Adding too many track events also adds more work for us. 🙈 

Let me know if I'm misunderstanding you!

**Comment by pmusolino** [comment]
Sorry, I lost your message here @shiki.
I was meaning that since the product selector VC is now generic (is used for grouped and linked products, but in the future for other purposes), we use some events that we track in these screens. These events now are based on grouped products, but since we should use these events also for linked products, we should have them generated also for linked products.
For the moment it's not possible to not track these events, but if you think that they are superfluous I can work to make them optional for other cases.

**Comment by shiki** [comment]
@pmusolino I agree that we have to track these events similarly since the product selector is reused. It doesn't look like these events are currently being used in Funnels so we might have an opportunity to rename them. What do you think about these?

Current Event Name | New Event Name | Custom Props
--------|------|--
   `grouped_product_linked_products_add_tapped`    |  `connected_products_list` | `action: "add_tapped", context: "grouped_products OR upsells OR cross_sells"`
   `grouped_product_linked_products_added`    |  `connected_products_list` | `action: "added", context: "grouped_products OR upsells OR cross_sells"`
   `grouped_product_linked_products_done_button_tapped `    |  `connected_products_list` | `action: "done_tapped", context: "grouped_products OR upsells OR cross_sells"`
   `grouped_product_linked_products_delete_tapped `    |  `connected_products_list` | `action: "delete_tapped", context: "grouped_products OR upsells OR cross_sells"`


Should we remove the `linked_products_category` event that I mentioned above? I think that one will be unnecessary since we're keeping these events that already exist.

**Comment by pmusolino** [comment]
- I think that, maybe, a better name for this event should be `connected_products_selector` or something like that since we show also the elements that should be selected.
- I agree with the custom properties.
- Yes, the `linked_products_category` can be removed, because will be substituted by these events.

**Comment by shiki** [comment]
> I think that, maybe, a better name for this event should be connected_products_selector or something like that since we show also the elements that should be selected.

Agreed. 

> Yes, the linked_products_category can be removed, because will be substituted by these events.

Sounds good to me!

---

I have updated the issue description.

**Comment by pmusolino** [comment]
@shiki do you think that we can make the name of these events more generic? In the future, this flow will be probably used for other selectors, and we are already passing the `context`.

What do you think about `products_selector_*` or something like that? Or are you matching these ones on Android?

**Comment by shiki** [comment]
@pmusolino Not quite sure what you mean. I had thought that `connected_products_selector`, as you suggested, is already generic. Would you mind pointing me to the event names that are not generic enough?

**Comment by pmusolino** [comment]
Oh sorry, I didn't notice the second column with the new name :omg: my bad! 💯

**Comment by shiki** [comment]
Whew! 😌
