### ISSUE TITLE
[UL&S] Entering a Jetpack store address leads to unexpected username/password screen

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#3362]
**Describe the bug**

Logging in with a Jetpack store address leads to an unexpected username/password screen with old styling.

**To Reproduce**
1. Start logged out of the app.
2. Select the “Enter store address” option.
3. Enter a self-hosted, Jetpack store address (with or without WooCommerce installed).
4. Notice that you are taken to a username/password screen that isn't styled correctly.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/102371329-fbbc8a80-3fb5-11eb-9f37-54d8f46ce948.png" width="300px">

**Expected behavior**
I expect to either see an error message/screen (if WooCommerce isn’t installed) or be taken to a WordPress.com login screen with an option to enter my site credentials (if WooCommerce is installed).

**Mobile Environment**
Please include:

- Device: iPhone XS
- iOS version: 14.2
- WooCommerce iOS version: 5.7.0.0 TestFlight beta

**Comment by ctarda** [comment]
This one is concerning too. Unexpected indeed.

**Comment by ctarda** [comment]
Gotcha! The difficult solution is:
* When Authenticationmanager's `shouldPresentUsernamePasswordController` is called, the parameter siteInfo is nil. 
* Because that parameter is nil, we end up asking WPAuthenticator to `.presentPasswordController`

The reason why that parameter is nil is deep into WPAuthenticator, and if we reach the point where we receive this parameter as nil, there is no way for us to tell if wordpress is not installed, if Jetpack is not installed or if none of them are installed. 

So I think the best we can do is present this error:

<img width="359" alt="Screenshot 2020-12-17 at 11 15 01 AM" src="https://user-images.githubusercontent.com/2722505/102439404-2d3a6200-4059-11eb-8586-8a6efca7e9c4.png">

while also removing the possibility of WPAuthenticator from reaching the screen with the old ui. 

On it!

**Comment by ctarda** [comment]
The issue is that at this point, for self-hosted sites with Jetpack installed, we are requesting from WPAuthenticator to `presentPasswordController` passing a hardcoded false to indicate that the site is not self hosted. 

The fix is passing a flag that reflects the real status of the site
