### ISSUE TITLE
[UL&S] “Try another account” button doesn't work after magic link login

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#3367]
**Describe the bug**

If you use a magic link to log in to a WordPress.com account, and then select “Try another account” on the epilogue screen, you aren't returned to the prologue screen as expected. Instead, you end up on a screen with an endless spinner.

**To Reproduce**
1. Start logged out of the app.
2. Select the WordPress.com login option.
3. Enter a WordPress.com account email address.
4. Select the magic login link option.
5. Check your email and use the magic login link.
6. On the epilogue screen, select "Try another account" to log in to a different account, and notice you aren't returned to the prologue screen.

**Screenshots**
<img src="https://user-images.githubusercontent.com/8658164/102380644-1136b200-3fc0-11eb-8c76-2f5f371548d3.png" width="300px">

**Mobile Environment**
Please include:

- Device: iPhone XS
- iOS version: 14.2
- WooCommerce iOS version: 5.7.0.0 TestFlight beta

**Comment by ctarda** [comment]
This one is a serious one. I haven't been able to figure out what is going on yet.

**Comment by ctarda** [comment]
This is an issue with StorePickerCoordinator

When the "Try Another Account" is tapped, the method `restartAuthentication` is called. This method switches on `selectedConfiguration` which seems to have the value `.login`. 

At this point we attempt a pop in a navigation controller that exists (it's not nil).

**Comment by ctarda** [comment]
StorePickerCoordinator is instantiated in AuthenticationManager:

`func presentLoginEpilogue(in navigationController: UINavigationController, for credentials: AuthenticatorCredentials, onDismiss: @escaping () -> Void)`

This method is a delegate method called by LoginViewController.showLoginEpilogue, which is also providing the "dismiss block" that StorePickerCoordinator will call later, after popping its navigation controller.

It looks like the dismiss block is nil

**Comment by ctarda** [comment]
Good news and bad news. 

First the bad news: this bug is happening in production as well. (That's 5.6 downloaded from the App Store)

What I think is happening at this point is:
* I am not sure how, but when returning to the app after tapping the magic link, something calls `AppCoordinator.displayStorePicker()`. 
* This method launches the store picker because, according to the comments, `Authenticated user does not have a Woo store selected — launching store picker.`. 
* This store picker is launched with configuration `.standard`.
* AppCoordinator retains StorePickerCoordinator
* Later on, AuthenticationManager also instantiates a StorePickerCoordianator, with config `.login`

I'll start tracing backwards from the point where AppCoordinator instantiates the storepicker

**Comment by eshurakov** [comment]
Duplicated issue: https://github.com/woocommerce/woocommerce-ios/issues/3270

**Comment by rachelmcr** [comment]
Ah, I missed the prior report of this issue, thanks @eshurakov! I'm going to close #3270 even though it's the earlier issue, just because this one includes more notes/research.

As discussed in Slack, this is an unfortunate issue but doesn't need an urgent/high priority fix (a fix in `develop` should be fine when we have one) since it's unlikely that many people use this button. (It's meant as an escape hatch if someone realizes they've logged in to the wrong account. It looks like we don't track how often it's used, but we don't expect it to be very common.)

**Comment by ctarda** [comment]
After some discussion, the plan is to fix this on a PR against develop over the holidays.
