### ISSUE TITLE
Top performers: support original date ranges

### ISSUE THREAD

**Issue by bummytime** [woocommerce/woocommerce-ios#353]
Issue stolen from [the Woo Android repo](https://github.com/woocommerce/woocommerce-android/issues/301):

> In #299 we added support for top performers, but we were unable to match the design because the backend didn't support the date ranges in the tabbed UI (7 days, 30 days, 90 days, 1 year), at least not in a way that didn't require making separate requests for product details.
>
> The Woo team resolved this [here](https://github.com/woocommerce/woocommerce/pull/21045) by adding the missing product details. Once we're able to use the v3 Woo API in the app, we should update the UI to support the original date ranges.

**Comment by mindgraffiti** [comment]
@jaclync can you confirm that StatsV4 fixes this problem?

**Comment by jaclync** [comment]
yep I checked the code for `top-earners` API (link to code at 141284-pb), and it's getting the top earners for the current day/week/month/year. Since stats v4 shows the stats for today/this week/this month/this year, this works correctly for the date range. For stats v3, it's an issue because the tabs are showing the past 1 month/3 months/1 year/5 years.

**Comment by mindgraffiti** [comment]
@jaclync perfect! Would you do the honors and close this one?
