### ISSUE TITLE
Order Details: Product image not loading for variable product

### ISSUE THREAD

**Issue by momo-ozawa** [woocommerce/woocommerce-ios#3733]
### Description

On the Order Details screen, the product thumbnail image is not loaded for a variable product.

https://github.com/woocommerce/woocommerce-ios/pull/3678 fixed product images not loading for simple products, but the problem still persists for variable products.

Internal ref: p5T066-1XH-p2#comment-7374
> thumbnail images do not load on the Order Details screen for any product in the order that has variations involved. Should products with variations show a thumbnail on the Order Detail screen?

**Comment by momo-ozawa** [comment]
Quick investigation notes:

`lookUpProduct(by: item.productOrVariationID) ` returns `nil`, which is why the product thumbnail image isn't loading

https://github.com/woocommerce/woocommerce-ios/blob/d85f00e17d55d1f849fdf3ed2a6c865451c5030f/WooCommerce/Classes/ViewRelated/Orders/Order%20Details/Product%20List%20Section/Product%20Details/ProductListViewController.swift#L73-L84

**Comment by iamgabrielma** [comment]
This is resolved with https://github.com/woocommerce/woocommerce-ios/pull/9988 as part of https://github.com/woocommerce/woocommerce-ios/issues/9808 . The core of the issue was that we were not saving variations locally as their own model, but as a part their parent products. In the PR linked above we changed the mechanism by implementing that disambiguation directly in the ProductStore and upsert the local results as `Product` or `ProductVariation` depending on the type, so they would show properly at the moment:

| Header | Header |
|--------|--------|
| ![Simulator Screen Shot - iPhone 11 Pro - 2023-08-15 at 12 45 58](https://github.com/woocommerce/woocommerce-ios/assets/3812076/d82cb44f-b632-4268-afd5-0e6fab656a5c) | ![Simulator Screen Shot - iPhone 11 Pro - 2023-08-15 at 12 46 11](https://github.com/woocommerce/woocommerce-ios/assets/3812076/f01437b3-c271-4ff4-ad82-d5e27d9fc02a) | 

Closing!
