### ISSUE TITLE
Replace xcpretty with trainer

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#3779]
While trying to implement p91TBi-4AQ-p2 to get better diffs on Xcode unit tests, we noticed that there is a problem with our CI where only the first line of the error message is being displayed. 

@AliSoftware noticed that the reason for this is because `xcpretty` which is part of our Fastlane setup is ignoring the rest of the error message lines when prettifying the output. 

The suggestion is to replace `xcpretty` with `trainer` and see if that fixes our problem.

**Comment by AliSoftware** [comment]
Some relevant links:
 - [Twitter convo with Krzyszt, author of the better Difference pod](https://twitter.com/aligatr/status/1367076026908557315)
 - [Trainer tool repository](https://github.com/fastlane-community/trainer) – with integration instructions in README.

---

Note that `trainer`'s goal is to generate a nice junit-like report from `xcresult` bundles (that `xcodebuild`/`multi_scan` generates at the end of running the tests), which is slightly different from `xcpretty` whose role is to prettify the raw and very verbose output of `xcodebuild` to filter it and make it more readable.

This means that in practice those 2 tools should not be mutually exclusive and maybe we can keep both:
 - `xcpretty` will have an effect of what's visible in the live logs on the CI logs. Disabling `xcpretty` in `multi_scan` will have the effect that the CI's stdout will suddenly become way more verbose and noisy, while keeping it will keep CI's stdout more compact and readable, even if it also means it will filter out some stuff, accidentally (like multi-line assert messages) or not (parts of raw logs deemed too verbose by xcpretty)
 - `trainer` will not affect the live logs, but instead runs after the fact, once `multi_scan` has finished. Using `trainer` or not won't affect CI's live stdout logs while the tests are running, but will allow us to print a nicer and more readable report/summary at the end of the CI job

So in practice maybe we should use both, i.e keep `xcpretty` enabled (no change in the call to `multi_scan` and its `output_style`), but also run `trainer` after `multi_scan` to generate a nice summary report, and `cat` the generated report file _only_ if we have detected a test failure – so that it's directly readable at the end of the job's logs when you open the CI, without having to download a file to read it (even if it would _still_ be nice to _also_ have that trainer report be saved as artefacts to be downloaded)
