### ISSUE TITLE
Order Details: do not offer the "email note to customer" option if no email is available

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-ios#3840]
Steps to reproduce:

1. Create an order that does not have an email included.
1. Open the oder in the app.
1. Tap "Add a note".
1. Observe you are able to toggle the "Email note to customer" option even if there is no email on file.

**Result:** if you try using the "Email note to customer" option if there is no email saved as part of the order details then the email will fail silently—we should not show the email toggle if there is no email on file to send the message to.

<img src="https://user-images.githubusercontent.com/1119271/111522066-7dd85e80-871f-11eb-8ba4-b4101f7a58e8.png" width="270" alt="image">
<sup>Tested with WCiOS 6.2.0.0 TestFlight beta on iPhone 6S iOS 13.7.</sup>

**Comment by leonardodamato** [comment]
Hello @designsimply. Hope you are well :) 

What do you think it would be the best approach for this issue? Hide the whole cell or maybe just disable the toggle? 

If we only disable it, we might need to insert a message somewhere otherwise the user will not know why they cannot activate the button. 

If it is ok for you, I think I can take care of it as soon as we know how this should be handled. :) 

Thanks!
