### ISSUE TITLE
Variations: Update attribute list buttons

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#3905]
Ref: p91TBi-4O0f-p2

Update attributes list screen to:

- Update top nav CTA to “Generate” to best convey to users the next step is a creation step

<img width="323" alt="update-attributes-list" src="https://user-images.githubusercontent.com/562080/113598401-b2468880-9602-11eb-9151-2cc4d81535d2.png">

**Comment by Ecarrion** [comment]
Being worked on by @itsmeichigo

**Comment by itsmeichigo** [comment]
FYI @Ecarrion, I see on develop now variation creation is disabled in the edit attributes flow so this `Generate` button will not be visible for testing for now. Just want to give a heads up on that!

Also, as I see on develop now the navigation bar has `back` button instead of `close` button like in the screenshot, so I'll just keep it as is. Let me know if I should update otherwise.

![Simulator Screen Shot - iPod touch (7th generation) - 2021-04-26 at 23 23 04](https://user-images.githubusercontent.com/5533851/116117535-8b9dde00-a6e6-11eb-8e0a-ce2d7ad67e9d.png)

**Comment by Ecarrion** [comment]
Hey @itsmeichigo 

>  I see on develop now variation creation is disabled in the edit attributes flow so this Generate button will not be visible for testing for now. Just want to give a heads up on that!

Variation creation should be enabled. You should see the "Done"(to be renamed) button when creating a variable product for the first time! 

> Also, as I see on develop now the navigation bar has back button instead of close button like in the screenshot, so I'll just keep it as is. Let me know if I should update otherwise.

That's perfect!
