### ISSUE TITLE
[Mobile Payments] Optimizing use of Combine in CardPresentPaymentStore

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#3926]
At this point CardPresentPaymentStore is over retaining the Futures it gets from the CardReaderService.

When we dispatch an action declared in CardPresentPaymentStore we instantiate one cancellable (or more than one in some methods) and then store it in a set of Cancellables.

We never clear that set of Cancellables though, so every time we dispatch a method in the store we will be adding new cancellable to he existing ones. if we dispatch the same method twice in a row, then we'll have duplicated results. 

Since we are basically interested in four streams (card reader discovery, connection status, payment collection and card reader events), the simplest solution might be getting rid of the set of cancellables, and declare four different Cancellables that we override every time we dispatch the corresponding method in the Store.

**Comment by koke** [comment]
So far, I've started investigating the part of the store that deals with reader discovery and connection.

My understanding of the potential states for discovery and connection looks something like this:

![Card Present Payments - Reader connection](https://user-images.githubusercontent.com/8739/117136453-adfbbf80-ada8-11eb-8b13-0bec1dd425a2.png)

Also, there are some assumptions I got from looking at the code, documentation, and the sample app:
- You have to set the token provider before doing anything else with the SDK.
- The SDK will stay in discovery mode until it's canceled, a reader is connected, or an error happens. I'm not sure which kind of errors might happen, but one I experienced in the sample app was that the token provider did not provide a valid token. Another was that the app tried to start discovery while the SDK was already busy with another operation.
- We should not cache any Reader value beyond the call to `connect`. This means that connecting to a Reader always requires a discovery process before.
- We should ensure no reader is connected before starting a discovery process. This, combined with the previous fact, means that only one reader can be connected at a time.
- We should ensure no discovery process is already active before starting discovery.
- The SDK provides a `connectedReader` and `connectionStatus` as a source of truth.

The current sequence of events for the simple case where a single reader is discovered and connected looks like this:

![stripe-discovery](https://user-images.githubusercontent.com/8739/117137134-9113bc00-ada9-11eb-803a-9d210915bfb6.png)


@allendav @ctarda does this match your understanding of how the SDK works?

The issues I see with the current implementation are:

- The `store(in:)` method we use to store cancellables is more suited to an object with a finite lifecycle, so when that object is deallocated, it cancels any outstanding subscription. The store will live as long as the app is running, so those will never be cancelled. We probably need to keep track of each individual subscription more explicitly.
- The `startCardReaderDiscovery` action has a completion block, but the discovery process can call `didUpdateDiscoveredReaders` multiple times as the list of discovered readers change. The problem with relying on completion blocks to pass data from the store to the UI is that blocks aren't cancellable. If the discovery process ends because a reader is connected or there is an error, the store can be aware of that, but if the user navigates away from the settings (or there's a different UI to cancel the search), the store isn't aware of that yet.
- There is a `cancelCardReaderDiscovery`, which also stores a cancellable, but it's not called from anywhere. I'm not sure what to do with this one.
- The `connect` function in the service returns a future, but the store ignores the result of the operation, and will actually call the completion according to the `connectedReaders` publisher, which will never get updated if there's an error connecting. I understand we haven't implemented error handling yet, but I would imagine we want to observe one of the things, as the `Future` returned by `connect` could also include the information about the connected reader. Although I'd rather rely on `Terminal.shared.connectedReader` and `Terminal.shared.connectionStatus` as the source of truth.
- The `connectedReaders` publisher has an output type of `[CardReader]`. However, there can only be one connected reader at any time, so it should probably be an optional.
- `observeConnectedReaders` is only used from `CardReaderSettingsConnectedViewModel` which I don't think it's being used anywhere, so I'm not sure how to deal with that one.
- Similarly, `observeKnownReaders` is only used from `CardReaderSettingsUnknownViewModel` which also seems unused.
- I'm still pretty new to Combine, but I'm not sure we're leveraging it correctly. In the case of `discoveredReaders` and `discoveryStatus`, we can send a completion event when the discovery process is finished, so we know when to stop listening for updates. Then a [Sink](https://developer.apple.com/documentation/combine/subscribers/sink) subscriber can be used instead of the `sink` operator, which automatically cleans up after the subscription completes.
- I generally find the use of completion blocks in `Action`s quite odd. I think we can make it work for this use case, but I also wonder if it would be better to have the UI access the Service directly through the `ServiceLocator`, and access the publishers directly, leaving actions only for user-initiated interaction. However, this feels more like a longer term discussion around data flow and combine, for which I might write a more general proposal in the future.

I think I'm going to start with fixing just a couple of the cases where the implementation is more ready and use those as an example for the rest as we complete the implementation. Then I'll evaluate the ones for payment and software updates separately.

**Comment by ctarda** [comment]
Thanks for the exploration @koke 

I would say that your understanding of the sequences and flows is pretty accurate. Just to help clarify some of the context, I've picked some of the bullet points you mentioned:

>  but I also wonder if it would be better to have the UI access the Service directly through the ServiceLocator, and access the publishers directly, leaving actions only for user-initiated interaction. However, this feels more like a longer term discussion around data flow and combine, for which I might write a more general proposal in the future.

This is something we might want to avoid. We are going to need some business logic on top of the service anyway, and going with a store/action makes it easy to integrate that logic into the rest of the app in a way that is consistent with other vertical concerns, and therefore is familiar to everyone. And we get a lot from free, like support for logging in and out, switching stores, etc. Payments are just another feature.

> The store(in:) method we use to store cancellables is more suited to an object with a finite lifecycle, so when that object is deallocated, it cancels any outstanding subscription. The store will live as long as the app is running, so those will never be cancelled. We probably need to keep track of each individual subscription more explicitly

That was my gut feeling as well.

 > In the case of discoveredReaders and discoveryStatus, we can send a completion event when the discovery process is finished, so we know when to stop listening for updates. Then a Sink subscriber can be used instead of the sink operator, which automatically cleans up after the subscription completes.

This seems like a solid improvement.

> There is a cancelCardReaderDiscovery, which also stores a cancellable, but it's not called from anywhere. I'm not sure what to do with this one.

This is probably not fully implemented yet. I would suggest leaving it as it is for now, until @allendav completes the work on the discovery UI and then reassess.

@allendav  do you have any other thoughts?

**Comment by designsimply** [comment]
@ctarda I see that this issue is labeled critical priority but also that there are several related and closed PRs. Can this issue be closed?

**Comment by ctarda** [comment]
Sorry @designsimply , I missed your comment. Yes, closing!
