### ISSUE TITLE
Automatic Sign-ups Should Be Disabled

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-ios#3962]
## Problem

In https://github.com/woocommerce/woocommerce-ios/issues/3146, we prevented the app from automatically creating a WordPress.com account. But at some point, most probably in https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/574, that change was reversed. The app now allows automatic sign-ups again. 

Tested in recent `develop`: 4fe9522. 

https://user-images.githubusercontent.com/198826/114770987-4d3d1200-9d29-11eb-9154-91843717151f.mp4

Android still works as expected. 

## Expected

I would expect the functionality shown in #3146 (PR https://github.com/woocommerce/woocommerce-ios/pull/3286) to be restored. 

## Tasks

- [ ] This could probably use an automated test. Hopefully, it's feasible.

---

FYI @designsimply This is probably one of those critical scenarios that we should keep track too.

**Comment by AliSoftware** [comment]
Just encountered that bug today by trying to log in but made a typo in my email address which led to sign up flow instead.

This uncovered a subsequent issue where, when I went back in the flow to fix the typo and provide the right, already existing email, I then wasn't able to go past the password screen next. When clicking on the "Continue" button on the password screen, after seeing the spinner for a second, the button goes back to normal state, I stay on the same screen, and nothing happens (see video below).
Only when I went back to the very start of the login flow, and start all over again (but without making the typo during the flow at all) was I able to log in.


https://user-images.githubusercontent.com/216089/118282826-fadd4580-b4ce-11eb-93b1-429bd8c18d1d.mp4

Note: in the video above I did type the password on the password screen at the end of the video. The password being typed is not visible in the video only because iOS is smart enough not to record passwords during screen recording.
