### ISSUE TITLE
Shipping Labels: checking shipping label creation eligibility for an order (endpoint)

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#4083]
For completing task #2971 we should integrate the [SL creation eligibility endpoint](https://github.com/Automattic/woocommerce-services/pull/2334) for deciding whether we show the Create Shipping Label button, removing the client logic.

This is the [PR opened on Android](https://github.com/woocommerce/woocommerce-android/pull/3827).

- [x] Networking layer https://github.com/woocommerce/woocommerce-ios/pull/4138
- [x] Storage layer (if needed. Not sure we want to store locally these information)
- [ ] Yosemite layer (Jaclyn already created an empty method inside `ShippingLabelStore`) https://github.com/woocommerce/woocommerce-ios/pull/4143

**Comment by rachelmcr** [comment]
I don't think we need to implement anything in the storage layer for this. Because we have to check the endpoint separately for each order, and it's possible for eligibility to change for an order (e.g. if we implement a new client feature or payment methods are changed remotely) it seems like we should always check the eligibility remotely rather than relying on locally stored information.
