### ISSUE TITLE
[Mobile Payments] Ensure Issue Refund works correctly for orders completed using in-person payments

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#4182]
For orders completed using in-person card present payments, ensure the Issue Refund flow works correctly i.e. that the refund is issued through the WCPay platform.

If not in scope for Beta, open a separate issue to disable the Issue Refund button for such orders for Beta.

cc @ctarda

**Comment by allendav** [comment]
OK, tested this and overall it works well. The only oddity is it presents the payment method as "Pay on delivery" in two places and I think that should say "WooCommerce Payments."  I created a test order and collected payment using a point of sale test card and a reader. I then used the app to process a refund and then examined both wp-admin and the internal dashboard to confirm it properly processed the refund through WCPay/Stripe.

The only change I recommend is to change "Pay on delivery" to show "WooCommerce Payments" in the two places noted below.

![a](https://user-images.githubusercontent.com/1595739/119895382-8ce34600-bef2-11eb-9276-71b3fec603ae.PNG)

![b](https://user-images.githubusercontent.com/1595739/119895377-8bb21900-bef2-11eb-8716-3133bda6c779.PNG)

![c](https://user-images.githubusercontent.com/1595739/119895372-8b198280-bef2-11eb-9651-5d1a3c887fed.PNG)

![d](https://user-images.githubusercontent.com/1595739/119895366-894fbf00-bef2-11eb-8819-0cb75b364bdb.PNG)

![e](https://user-images.githubusercontent.com/1595739/119895353-8785fb80-bef2-11eb-953c-59eed3a9a0fe.PNG)

**Comment by allendav** [comment]
I tracked this down to https://github.com/Automattic/woocommerce-payments/issues/1944 - a problem in the backend. Recommend closing this issue and prioritizing 1944

Once set correctly, it appears correctly automatically in the iOS app:

![f](https://user-images.githubusercontent.com/1595739/119903438-8f976880-befd-11eb-8b8b-09fc8e1e8fdb.png)


cc @ctarda

**Comment by shiki** [comment]
For some reason, Issue Refund does not work correctly for me. When using a site that has the Stripe gateway, the app correctly indicates “Credit card” in the Refund screen: 

<img src="https://user-images.githubusercontent.com/198826/124522700-6a75ff80-ddb1-11eb-9ad9-f1ce808ef3da.png" width="300">

And the transaction shows up properly in WC Admin  → Payments → Transactions. It's attributed to the Visa card.

<img width="2330" alt="refund transaction" src="https://user-images.githubusercontent.com/198826/124522724-7f529300-ddb1-11eb-8314-194642ac483f.png">

However, when using WCPay (iOS app version 7.0-beta), I see “Cash on delivery”. 

<img src="https://user-images.githubusercontent.com/198826/124522786-a8732380-ddb1-11eb-8851-e40317d58a8d.png" width="300">

And I don't see it being attributed to the credit card in WC Admin:

<img width="2326" alt="transaction - wcpay" src="https://user-images.githubusercontent.com/198826/124522813-c04aa780-ddb1-11eb-95a0-bcea194b77a4.png">

Perhaps I'm not following the intended use case? I mainly followed these steps: 

1. Create an order on the web. I used Wojtek's test site.
2. Pick Cash on Delivery. 
3. In the app, process and accept the payment using the reader. 
4. Tap on Issue Refund. 

Let me know if you need more info, @allendav or @ctarda.

**Comment by allendav** [comment]
Hey @shiki - I think I am misunderstanding the first half of your comment above. Did you mean you used the Stripe gateway and then you saw that Stripe gateway transaction show up in wp-admin > Payments? Stripe gateway payments shouldn't show up there - only WCPay gateway payments should.

**Comment by shiki** [comment]
Sorry, @allendav. I looked at my settings and it turns out I was using WooCommerce Payments on my site (https://flyingorigami.shiki.me/). I originally thought I was using the Stripe extension. 🤦  

I invited you so you can check it out but I think this was a miscommunication. 

This is the flyingorigami.shiki.me site is set up:

![image](https://user-images.githubusercontent.com/198826/124523743-8c718100-ddb5-11eb-8eec-007d8fa01690.png)

And it's the same with the second half in the comment, which is Wojtek's site (https://wziebatests.it): 

![image](https://user-images.githubusercontent.com/198826/124523781-bd51b600-ddb5-11eb-9c73-5cbb4433dd25.png)

So I think the difference was, for flyingorigami.shiki.me, I used these steps:

1. Create an order on the web. 
2. Pay with **test credit card**.
2. In the app, issue a refund. 
3. The app shows “Credit card”. 

For Wojtek's site, I follow the steps described in https://github.com/woocommerce/woocommerce-ios/issues/4182#issuecomment-874359082. 

--- 

I think my expectation was, using Wojtek's site, when I paid using the reader, the app would then show “Credit card”. But I'm not sure how these are supposed to work. 

Let me know how I can better explain this more. 😬

**Comment by allendav** [comment]
Ah - I think you are referring to a documented problem: https://github.com/Automattic/woocommerce-payments/issues/1944

Does that make sense?

**Comment by shiki** [comment]
@allendav I believe you're right! We use the payment method title in that screen:

https://github.com/woocommerce/woocommerce-ios/blob/3d0448e9c8213fe89829b172eda4bff541ebb307/WooCommerce/Classes/ViewRelated/Orders/Order%20Details/Issue%20Refunds/RefundConfirmationViewModel.swift#L147-L148

Sorry I made things more confusing. 😬 I should have carefully read all the other comments above.

**Comment by allendav** [comment]
No worries whatsoever. This is a moderately complicated endeavor.
