### ISSUE TITLE
[Mobile Payments] Button label truncated when payment fails

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#4222]
When a payment fails, the text in the modal button is truncated:

![Screen Shot 2021-05-19 at 11 40 48](https://user-images.githubusercontent.com/8739/118791925-75271480-b897-11eb-8221-fccf64749ce6.png)

To reproduce, try to make a test purchase with an amount ending in `.75` (or any of the other [error decimals](https://stripe.com/docs/terminal/testing#physical-test-card)).

**Comment by allendav** [comment]
The first part of the fix is to change from truncate in the middle to word wrap, and I poked at this a bit today with that but the NUXButton really doesn't look good with multiple lines of text (text gets close to button edge). It seems to be overriding the insets or constraining the height or both.

I'll keep trying

<img src="https://user-images.githubusercontent.com/1595739/119205290-bb71a480-ba4c-11eb-9eea-a6f8da0c995c.PNG" width=50% />
