### ISSUE TITLE
[Mobile Payments] Add support for "Several Readers Found"

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#4333]
Even though we have UI that suggest that we would be able to handle multiple card readers, there is no logic to do so.

This comment in line 100 of CardReaderSettingsUnknownViewModel tells the story:
`        /// TODO: Add another viewmodel and view to handle multiple discovered readers.`

**Comment by ctarda** [comment]
@allendav  could you please prioritize this over your other tasks?

**Comment by ctarda** [comment]
This is pretty much what is missing.

<img width="203" alt="Screen Shot 2021-05-31 at 17 24 36" src="https://user-images.githubusercontent.com/2722505/120243266-25503200-c235-11eb-98eb-e83cfca2366b.png">

**Comment by ctarda** [comment]
@allendav  let's see what comes out of this discussion first: p91TBi-5fB-p2

**Comment by ctarda** [comment]
@allendav crisis adverted for now. p91TBi-5fB#comment-4849-p2 I will move this to the post-beta 1 backlog for now

**Comment by allendav** [comment]
@ctarda sounds good - I also added my thoughts in comment 4854

**Comment by allendav** [comment]
@ctarda 

I've looked at what I think it would take to do this and I am proposing adding a new modal to CardReaderSettingsAlerts that presents the list. This will also require changes to the CardPresentPaymentsModalViewModel protocol to also include an optional array of tappable items (found readers) and CardReaderConnectionController to use that modal instead of the "found one reader" modal. We'll also have to stop using bluetoothProximity and switch to bluetoothScan in order to see multiple readers.

I'll wrap it all in a feature flag and implement it over the course of roughly 5 PRs:

Testing will require ensuring this works properly both in the settings context but also in the collect-payment context.

- PR 1
    - Feature flag
- PR 2
    - change to bluetoothscan
    - change CardReaderConnectionController foundReader to array
    - update CardReaderConnectionController onConnectToReader to connect to the selected reader
- PR 3
    - extend CardPresentPaymentsModalViewModel protocol to also include optional tableviewcell array
    - Add foundMultipleReaders to CardReaderSettingsAlertsProvider protocol
    - Add foundMutlipleReaders to CardReaderSettingsAlerts
    - add CardPresentModalFoundMultipleReaders conforming to CardPresentPaymentsModalViewModel
    - Add foundMultipleReaders to CardReaderSettingsAlertsProvider protocol
    - Add foundMutlipleReaders to CardReaderSettingsAlerts
- PR 4
    - add new state to CardReaderConnectionController to show foundMutlipleReaders
- PR 5
    - remove feature flag

I estimate this would take 3-5 working days to complete.

**Comment by ctarda** [comment]
@allendav Thanks for that! One observation: it is okay, I think, to build that modal separately from the current CardPresentPaymentsModalViewModel / view controller pair. It seems to me like CardPresentPaymentsModalViewModel is already doing too much. A bit of repetition is okay if it prevents a lot of complexity 😉 Your choice though!

**Comment by allendav** [comment]
Point is well taken! The VM does have its fingers in a lot of bowls already. I will think on this a little before diving into PR 3.
