### ISSUE TITLE
Variations: Remove redundant "No Price" banner

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#4451]
Could we remove the price alert banner on the Variations list screen (sorry I know this was in the original designs)? I think it’s probably enough that we show the banner on the parent product page + the “No price set” button. With the banner, the Variation list screen becomes a bit too crowded

<img width="180" alt="screen-shot-2021-06-16-at-4 07 44-pm" src="https://user-images.githubusercontent.com/562080/122566104-cd734280-d00c-11eb-9aa5-297b600874ac.png">

reported by @Garance91540

**Comment by shiki** [comment]
Android issue: https://github.com/woocommerce/woocommerce-android/issues/4258

**Comment by rossanafmenezes** [comment]
Re-opening this issue since while working on the Android version of this I came across an unexpected behaviour related to the banner. The "no price" warning banner only shows if you tap the variation tab first. 

## Steps to reproduce

- Go to the products screen
- Open a variable product that has no price set for one of the variations. 

## Expected behaviour

The Warning Banner saying the variation without a price won't show in their store should be displayed in the product details screen

## What happens instead?

When you open the product there's is no banner:

![photo_2021-10-21 14 57 15](https://user-images.githubusercontent.com/30724184/138349533-efca2e17-0deb-4c60-a20f-95d94984a3f1.jpeg)


However, if you click on the Variations tab and then go back to the product details screen the banner is displayed:

![photo_2021-10-21 14 57 19](https://user-images.githubusercontent.com/30724184/138349588-e5439935-25e8-41a8-93d7-7dc56758df82.jpeg)
