### ISSUE TITLE
Connect and Payment flow: Modal UI updates

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-ios#4550]
Hi there, I know we discussed about the modal size issue before, but I thought it would be clearer to do an exhaustive audit anyway.

Here's a general comparison of screenshots and designs the whole connect reader + collect payment flow so we can get an overview, and I'll detailed the changes separately below:

<img width="719" alt="Screen Shot 2021-07-06 at 10 58 31 AM" src="https://user-images.githubusercontent.com/28450084/124572684-1fa7c680-de49-11eb-97ee-d4b6f4e8d2c3.png">

I made some changes to unify the connect and collect flow to make implementation a bit easier:
- the modal titles fonts are always "body" and have a fixed top vertical padding of 32px
- if there are buttons, they always have a bottom vertical padding of 16px, and left and right padding of 16px
- In general (there are some exceptions, as displayed on Figma) all the other modal elements are vertically distributed between the modal titles and the buttons

*Scanning Reader

Screenshots | Designs
------------ | -------------
![IMG_1057](https://user-images.githubusercontent.com/28450084/124571927-811b6580-de48-11eb-984d-3df4c7d9f4a5.png) | ![Frame 648](https://user-images.githubusercontent.com/28450084/124573583-fb001e80-de49-11eb-8393-22ab48c10b9e.png)

- Update modal size to 280 x 382 px
- Update text font to match design
- Update image size to match design

*Connect Reader screen

Screenshots | Designs
------------ | -------------
![IMG_1058](https://user-images.githubusercontent.com/28450084/124570982-a9569480-de47-11eb-87e4-e7be98a5563a.png) | ![Frame 649](https://user-images.githubusercontent.com/28450084/124574020-59c59800-de4a-11eb-9a21-3be0029ea761.png)

Here's the list of UI updates:
- Update modal size to 280 x 382 px
- Update text font to match design
- Update image size to match design
- Update button sizes and vertical padding to match designs

*Collect Payments - insert card

Screenshots | Designs
------------ | -------------
![IMG_1062](https://user-images.githubusercontent.com/28450084/124574217-8bd6fa00-de4a-11eb-8362-8aaf2ea0d90d.png)  | ![Frame 646](https://user-images.githubusercontent.com/28450084/124574259-942f3500-de4a-11eb-92b8-32f40107a3c8.png)

Here's the list of UI updates:
- When no customer name is added in the order, the modal reads "Collect payment from..." Can we update to read "Collect payment" only? 
- Update modal size to 280 x 382 px
- Update text font to match design
- Update image size to match design
- Update button sizes and vertical padding to match designs

* Collect Payments - remove card

![IMG_1063](https://user-images.githubusercontent.com/28450084/124574568-e1130b80-de4a-11eb-89df-ae28bf17ac78.png) | ![Frame 646](https://user-images.githubusercontent.com/28450084/124574605-eb350a00-de4a-11eb-9e40-47dd05f9bf2b.png)

Here's the list of UI updates:
- Update modal size to 280 x 382 px
- Update text font to match design
- Update image size to match design

Please let me know if you have any questions!

**Comment by koke** [comment]
I've made some progress with the modal dimensions, but there's one screen that is looking all weird. When the app is trying to connect to a reader, the content is a bit too small for the modal. From the other modals where this is the case, I assume we want the content aligned to the top instead of centered, but there's a lot of empty space in this case. The designs show a Cancel button in this screen, but the Stripe SDK doesn't offer the option to cancel a connection request.

Screenshot|Design
-|-
<img width="375" alt="Prologue" src="https://user-images.githubusercontent.com/8739/131665713-10a4fd8a-3b89-48de-a518-66455cdb00b6.png">|<img width="375" alt="Prologue" src="https://user-images.githubusercontent.com/8739/131665847-fb0ed908-3ba4-4ce7-8c0d-a56a5f7ebd71.png">

I'm not sure what's the right solution for this one

**Comment by Garance91540** [comment]
Hi koke, 

It's ok if there's whitespace at the bottom of the modal. But can you please confirm we are matching the following padding specs:

<img width="652" alt="Screen Shot 2021-09-01 at 10 35 46 PM" src="https://user-images.githubusercontent.com/28450084/131741319-6764d28b-5e02-4dd4-93fa-14fa7c78ecae.png">

Additionally, the modal title should read "connecting to reader" (and not "scanning for reader") like in your screenshot. The font for this title also looks different, it should be iOS/Body

Let me know if you have questions!

**Comment by koke** [comment]
> can you please confirm we are matching the following padding specs

@Garance91540 I don't think the current implementation is matching those. What I see is that we are using a shared configurable view for all the modals:

![Screen Shot 2021-09-02 at 09 50 10](https://user-images.githubusercontent.com/8739/131804334-05280e8f-7f79-4096-a79e-09cc9ca5ab20.png)

This view will has a 32px spacing between its elements. I think we probably need to change how this is implemented because we'd want the buttons to be bottom-aligned, even if the content doesn't fill the minimum height (382px).

Making the illustration top padding relative to the container can be problematic because the text above might not fit the available space with larger font sizes or translations. Right now, it seems we're not handling dynamic text too well in these modals though 😞 

Searching|Reader found
-|-
![Screen Shot 2021-09-02 at 09 57 52](https://user-images.githubusercontent.com/8739/131805449-0674d2b7-6d9a-4123-8a7f-b72c6f5dc668.png)|![Screen Shot 2021-09-02 at 09 58 04](https://user-images.githubusercontent.com/8739/131805443-0a9310f4-8bec-4474-b52d-b02cca5da10d.png)

On the other hand, if we make the illustration's position relative to the text above, it will jump across screens, since the title height might change, as in these two screens:

![Screen Shot 2021-09-02 at 09 59 18](https://user-images.githubusercontent.com/8739/131805696-aeb2b01e-966e-45e9-8760-286e9111664d.png)

One thing I can try is making that illustration 112px from the top of the container, and ensuring the text above uses a smaller font if needed to fit in the available space.

On the other hand, I see some screens where the illustration is placed higher up, so now I'm questioning if there is a shared logic across all the modals, or we should implement each one individually to match the designs exactly (@ctarda another point for SwiftUI here 😉)

![Screen Shot 2021-09-02 at 10 07 39](https://user-images.githubusercontent.com/8739/131806987-907beb4b-4cb1-4d5f-80d1-8f9147dcfb75.png)

**Comment by Garance91540** [comment]
> This view will has a 32px spacing between its elements. I think we probably need to change how this is implemented because we'd want the buttons to be bottom-aligned, even if the content doesn't fill the minimum height (382px).

Yep, the current implementation doesnt match the designs :) . The modal should have a fixed height (382px) and width (280px), the title is top aligned (fixed 32px vertical padding), and the buttons are bottom aligned (fixed 16px padding) as you mentioned.

> On the other hand, I see some screens where the illustration is placed higher up, so now I'm questioning if there is a shared logic across all the modals

The illustrations' positioning can vary on each modal, the only fixed ruled is this one:
> The modal should have a fixed height (382px) and width (280px), the title is top aligned (fixed 32px vertical padding), and the buttons are bottom aligned (fixed 16px padding) as you mentioned.

> One thing I can try is making that illustration 112px from the top of the container, and ensuring the text above uses a smaller font if needed to fit in the available space.

I'd like to keep the font size consistent across modals if possible, so I'd prefer we don't make it smaller :)

The screenshot you shared originally was good enough tbh, if it's too complicated to make the polish adjustments I suggested, let's leave it for now. 

Can we simply address those 2 items:

> Additionally, the modal title should read "connecting to reader" (and not "scanning for reader") like in your screenshot. The font for this title also looks different, it should be iOS/Body
