### ISSUE TITLE
[Mobile Payments] if a card present payment fails with "Networking.Dotcom error 0" the option to collect payment is removed

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-ios#4655]
Steps to reproduce:

1. Create a situation where a payment will fail (i.e. a decimal stock quantity is used). You can install and activate a plugin that supports decimal quantities, such as [WPC Product Quantity for WooCommerce](https://wordpress.org/plugins/wpc-product-quantity/). To use this plugin as an example, go to WP Admin > WPClever > Product Quantity, change Decimal Quantities to Yes, add 0.5 for Minimum, Step, and Default.
1. On the web, submit an order containing a product with a decimal stock quantity.
1. In the app, open the order.
1. Tap the "Collect Payment" button and tap the test card to the reader.
1. Observe the error messages that pop up—do they make sense?
1. Pull-to-refresh on the order details screen.
1. Try to collect payment again.

**Result:** when a payment fails with the unexpected error "Networking.Dotcom error 0", the "Collect Payment" button turns back into an "Issue Refund" button and you become stuck awaiting payment but there is no longer an option to collect payment. ([5m29s](https://cloudup.com/caJgmGjc_Eh))

**Errors:**

> Payment failed
> The operation couldn't be completed. (Networking.Dotcom error 0.)
> Button: Try collecting payment again
> Button: No thanks

> Payment failed
> The system experienced an unexpected internal error - please try again
> Button: Dismiss

> A capture of $2.50 failed to complete with the following message: Error: Invalid integer: 0.5.

Error 1|Error 2|Error in notes
---|---|---
<img src="https://user-images.githubusercontent.com/1119271/126243435-a91d4a75-744b-4dbb-ba33-aec7790dd725.png" width="270" alt="image">|<img src="https://user-images.githubusercontent.com/1119271/126243570-73c03f47-5694-4850-8cbe-f136cb2c5115.png" width="270" alt="image">|<img src="https://user-images.githubusercontent.com/1119271/126244298-3055aec7-01ce-4168-b9bd-a4fd004a8c0b.png" width="270" alt="image">

<sup>Tested with WCiOS 7.1.0.1 TestFlight beta on iPhone 6S iOS 14.7 logged in as testuser01121 with worthwhile-seahorse.jurassic.ninja selected and running WP 5.7.2 JP 9.9 WC 5.5.1 WCPay 2.7.0 WCS staging 1.0.</sup>

**Comment by ctarda** [comment]
@allendav could you take a look at this one whenever you have some time please?

**Comment by allendav** [comment]
With a 2.5 of an item in my cart, attempting to collect payment fails for me as well with "error 0." This is because, after the pull to refresh, the order payment method ID is updated and is now set to `woocommerce_payments` making it ineligible with our current logic:

https://github.com/woocommerce/woocommerce-ios/blob/eb23fb44a75a8421f4e1e8936692897d817c76d2/WooCommerce/Classes/ViewModels/Order%20Details/OrderDetailsDataSource.swift#L1493

This change to the payment method ID could likely happen for any error, not just decimal quantities (which Stripe will always reject) where the order payment method ID is updated by the backend to `woocommerce_payments` but the payment fails to complete (e.g. for an intermittent problem on the merchant's host or connection to Stripe)

I will post a PR to allow `woocommerce_payments` as an acceptable payment method ID for `isOrderPaymentMethodEligibleForCardPayment` - I see no downside to doing this for orders in the pending, processing or on-hold state, which is enforced by `isOrderStatusEligibleForCardPayment` in that same class
