### ISSUE TITLE
Order Editing: Add Edit Indicator on Customer Provided Note

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#4775]
<img width="325" alt="Screen Shot 2021-08-11 at 8 44 10 AM" src="https://user-images.githubusercontent.com/562080/129040231-d91fd36a-df61-4179-baa5-b5c332d53f41.png">

Tasks:

- [x] Add pencil icon on customer provided note
- [x] Make row always visible
- [x] Make sure its under a feature flag

**Comment by jaclync** [comment]
Hey @Ecarrion! I was checking out order details in the app today and saw this customer-provided note UI. The empty space in this row when the note is empty feels a bit unexpected, does it make sense to have a placeholder or remove the empty line? I didn't find a design for the empty note scenario, just wondering if it's intentional.

Also, nice work on implementing this with SwiftUI and working out a solution for the bold "Done" button!

empty customer note | non-empty customer note
-- | --
![Simulator Screen Shot - iPhone 11 - 2021-09-13 at 13 20 42](https://user-images.githubusercontent.com/1945542/133029331-f184a3fb-aac1-48cf-88c5-f829ad604e97.png) | ![Simulator Screen Shot - iPhone 11 - 2021-09-13 at 13 21 05](https://user-images.githubusercontent.com/1945542/133029323-aad71ebd-0a82-4552-8974-4cb63c79d153.png)

**Comment by Ecarrion** [comment]
Hi @jaclync, thanks for the annotation.
There isn't a specific design for this scenario just yet, but as the project is still running I'll make sure to confirm with the design team how they prefer to handle this case.

Thanks
