### ISSUE TITLE
Products: update placeholder text on the variation page to say "Add a variation image"

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce-ios#4848]
> Can we update the placeholder text on the variation page to say “Add a variation image:” instead of “Add a variation product”?

<img src="https://user-images.githubusercontent.com/1119271/130200493-57eee0a0-2126-4e97-a2e2-fde10358c362.PNG" width="270" alt="IMG_4954">

<sup>(internal reference: p5T066-2yX-p2#comment-9525 /hat tip @Garance91540)</sup>

**Comment by Ecarrion** [comment]
I'm taking this for a trial candidate!

**Comment by thehenrybyrd** [comment]
I'm working on this, sorry there hasn't been an update in a while! @Ecarrion thanks for letting me keep it :) 

What I initially assumed would be a fairly straightforward typo fix turns out to touch a number of layers and require giving a dynamic setup to this currently static element. The element (`ExtendedAddProductImageCollectionViewCell`) has a label which states "Add a product image", and is currently static.
Here's a quick overview of where I'm at.

**The problem as I understand it**: `ExtendedAddProductImageCollectionViewCell` doesn't know if it's being viewed from within a variation or not, and neither does anyone in the layers above. Only knowing whether the cell is using `EditableProductVariationModel` or `EditableProductModel` can tell us, and nothing touching `ExtendedAddProductImageCollectionViewCell` currently has that information.

**Solution**: Update various layers to include an `isVariation` boolean in the two cases being used: `extendedAddImage` and `extendedAddImages` (each in a separate enum). An alternative is to add a new case to each enum, something like `extendedAddVariableImage`.
Note: currently there are two enums, `ProductImagesItem` and `ProductImagesCellConfig` which have extremely similar functionality and are used somewhat interchangeably. A good followup task would be to refactor to only use one enum.

Once I have that dynamic setup, I can add a label in `ExtendedAddProductImageCollectionViewCell` that is applied only when we're looking at a variation.

I'll be working on this with @ealeksandrov's help over in [this branch](https://github.com/woocommerce/woocommerce-ios/compare/issue/4848/variation-image-placeholder-text-update). Since this is not my primary task, it will have a longer timeline than might be expected otherwise.
