### ISSUE TITLE
[Mobile Payments] Modals dismiss without animation

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#5053]
I've noticed a few cases where the payments modals dismiss without animation.

It looks like ca23427f512b05040d1692efd7d3485ddf34c9cb intentionally sets `animated: false` when dismissing, so I'd like to understand the reasoning better before changing it back. cc @allendav

**Comment by allendav** [comment]
It's because we don't animate between the modals in the series of card reader settings (discovery, found, connecting) modals when the view model changes, so I didn't want to introduce an animation just for the several-readers-found modal - which is basically another modal in the series.

The commit also avoids "presenting while presentation in progress", but I believe it will still do that if we change the several-readers-found presentation and dismissal to animated

**Comment by koke** [comment]
Interesting, I thought/assumed we were animating them in, but the reality is that what's jarring is not the lack of animation but that the dimmed background disappears ~half a second before the modal does. When they are presented, both views appear at the same time:

https://user-images.githubusercontent.com/8739/135469431-7bcc69fa-abd0-49ff-b205-91989b87c999.MP4

**Comment by ctarda** [comment]
Closing for now.
