### ISSUE TITLE
Shipping Labels: colors of navigation bar buttons are inconsistent on iOS 15

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#5083]
**Describe the bug**
On iOS 15, navigation bar buttons on SwiftUI views are inconsistent - some are purple and some are pink:

<img src="https://user-images.githubusercontent.com/5533851/135252475-642881de-bfe8-46a9-9df8-ca654f07f23f.PNG" width=320 /> <img src="https://user-images.githubusercontent.com/5533851/135252490-359bf84b-ea15-468e-9e43-52410f3692e0.PNG" width=320 /><img src="https://user-images.githubusercontent.com/5533851/135252494-a739fe67-d790-4d4b-a7b3-244eb633853b.PNG" width=320 />

**Expected behavior**
All Done button should be pink.

**Comment by itsmeichigo** [comment]
I found 2 problems regarding navigation button colors in SwiftUI views on iOS 15:
- `.navigationBarItems` is deprecated and should be replaced with `.toolbar` and `ToolBarItem`.
- Navigation bars on iOS 15 doesn't use the tint color set to `UINavigationBar.appearance().tintColor`.

**Comment by rachelmcr** [comment]
Leaving a couple notes here from my investigation:

> .navigationBarItems is deprecated and should be replaced with .toolbar and ToolBarItem.

One thing I discovered is that in places where we use `ToolbarItem` with the placement `.navigationBarTrailing`, the button isn't bold. (In at least one place, we continued using `.navigationBarItems` to make sure the button was bold.)

Instead, we can use the placement `.confirmationAction` which makes the button bold while still placing it in the trailing position in the navbar.

> Navigation bars on iOS 15 doesn't use the tint color set to UINavigationBar.appearance().tintColor.

Since the tint color affects all of our SwiftUI views (not just shipping labels screens) and a global solution affects more than just navigation bar styling, I asked for additional input on this here: p91TBi-69w-p2

**Comment by rachelmcr** [comment]
Per the discussion in p91TBi-69w-p2 I'll use a view modifier to make the color fix in our SwiftUI views.

Also from that discussion, @itsmeichigo noted:

> I just want to point out one thing that the modifier `.accentColor(_:)` is deprecated on iOS 15, so we may need to use #available check to switch to [`.tint(_:)`](https://developer.apple.com/documentation/swiftui/view/tint(_:)) for iOS 15.

This is a good thing to keep in mind, but after trying it out I realized we'll have to wait on this. `.tint(_:)` isn't available in Xcode 12.5, which we're still using for CI. I checked and `.accentColor(_:)` does still work on iOS 15.0, so for now we can use it.
