### ISSUE TITLE
[Mobile Payments] Present to user failure to fetch location when connecting to a reader

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#5088]
Right now we handle golden path only. We should present to the user a message when we are unable to fetch a location ID for their reader. Disambiguating from other connection failures should help with debugging connection failures.

Needs design?

**Comment by ctarda** [comment]
Is this still valid? My understanding is that Android will show an error message. Is that so @kidinov ?

**Comment by allendav** [comment]
Yes. This is still valid. For example, right now we present this if the REST API route cannot be found:

![IMG_0193](https://user-images.githubusercontent.com/1595739/137230336-f72fbef5-0c7d-4f0c-bc60-3adb6dbac09e.PNG)

And we also present that exact same dialog if the user hasn't provided a street, city and postal code for their business in wp-admin > WooCommerce > Settings

**Comment by kidinov** [comment]
@ctarda 

On android, if fetching fails with:
**Missing address error:**
* We show a specific error dialog with the "enter address" button
* Click on enter address leads a user to WebView (user will be authenticated) if it's WP.com or Atomic site
* Click on enter address leads a user to Chrome Tab (user will NOT be authenticated) in other cases

**Network connection or other error:**
* Just generic error dialog with try again button

**Comment by joshheald** [comment]
@allendav @ctarda Please could you check my understanding on this issue?

1. We don't give the user a useful error if they've not got an address set up in wp-admin.
2. This case is indicated by the API error [`store_address_is_incomplete`](https://github.com/Automattic/woocommerce.com/blob/1455c1dee22ffdee24a7c25e91a1a19a25064271/plugins/woocommerce-payments/includes/admin/class-wc-rest-payments-terminal-locations-controller.php#L66) with an accompanying URL.
3. When we get that error, we should show an error `Please provide your store address in order to proceed`, and an `Enter Address` button which opens the URL in the error, potentially in a webview or Safari (not sure whether we need the same handling as Android here.)

If you could let me know whether I'm on the right track with this one, that'd be ace 🙇

**Comment by allendav** [comment]
We can also fail if Stripe rejects the address, but we have a separate issue for that: https://github.com/woocommerce/woocommerce-ios/issues/5320

So... what you've proposed is one use case (and a big one) - that's all I'd ask you to keep in mind.

Oh, and I'd word it as something like "Please update your store address to proceed." (avoid the word order since it has a more likely meaning in the context of WooCommerce and could confuse ESL or translators)

One last thought: as an MVP, a refresh button may be sufficient similar to how we handle plugin activation.

**Comment by ctarda** [comment]
> as an MVP, a refresh button may be sufficient similar to how we handle plugin activation.

I like the idea of iterating fast. Unless the overhead of breaking this down in two PRs is too high, what about doing this?:
1. When we get that error, we should show an error: "Please provide your store address in order to proceed", and a refresh button in the app. Merchants will have to go to their browser to configure the store properly and then come back to the app to refresh and continue.
2. Open the url in the error in a web view in a separate PR that could be tackled right after the one implementing step number 1.

That way we would close the error path as fast as possible, polishing the experience as soon as possible.

**Comment by ctarda** [comment]
Sorry, [my previous comment](https://github.com/woocommerce/woocommerce-ios/issues/5088#issuecomment-975734771) was meant to be a question, not a statement 😊

**Comment by joshheald** [comment]
Thanks both. I'll go down the route of the error message and refresh button as you suggest, unless it looks super trivial to get the URL opening into the same PR.

**Comment by kidinov** [comment]
@joshheald 

The API is not really intuitive here, so just as an example:

```
{
  "error": "store_address_is_incomplete",
  "message": "https://wcsite.wpcomstaging.com/wp-admin/admin.php?page=wc-settings&tab=general"
}
```

The URL comes as "message"

**Comment by joshheald** [comment]
Thanks for the heads up on that @kidinov 😊
