### ISSUE TITLE
Order Editing: Tapping done multiple times

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#5111]
## Report:

> On edit flows,  if I tap "done" multiple times without internet, the error notice will be shown 2 times. So it'll appear, disappear after some time, then appear immediately again. I don't see an immediate reason in the code.

## Task 

We should debounce/throttle that button or disable it while a network operation is happening

**Comment by selanthiraiyan** [comment]
Hello @Ecarrion 👋 

I took a look into this and here are my observations.

1. The second Error notice appears after a delay because `enqueue` function in `DefaultNoticePresenter` tries to avoid showing duplicate notices. But, the `enqueue` function is only comparing the new `notice` against the `notices` enqueued, but it doesn’t compare with the `notice` which is already being presented. I have [raised a PR](https://github.com/woocommerce/woocommerce-ios/pull/5183) to cover this scenario.


1. The `Done` button is already being disabled and the `Done` text is replaced with a loading indicator when a network operation (`performingNetworkRequest`) is in process. 
https://github.com/woocommerce/woocommerce-ios/blob/3db342e09571c5552ad592f544ce1786ee516be9/WooCommerce/Classes/ViewRelated/Orders/Order%20Details/Address%20Edit/EditOrderAddressFormViewModel.swift#L324-L333
![DoneButtonLoadingState](https://user-images.githubusercontent.com/524475/136665602-aad54568-a350-4983-bc84-35d5b8fb9aa1.png)

Kindly let me know your thoughts. Thank you!

**Comment by Ecarrion** [comment]
Thanks for the investigation @selanthiraiyan!

I will take a look at that PR as soon as I can!

> Kindly let me know your thoughts. Thank you!

In anything in particular? 😅

**Comment by selanthiraiyan** [comment]
Oh, sorry for being not clear. 😅 Kindly let me know your thoughts on, whether the `Done` button's implementation should be altered. i.e. throttle etc. 

I think the current implementation is fine. Especially, after we fix the duplicate `Notice` problem.

**Comment by Ecarrion** [comment]
> I think the current implementation is fine. Especially, after we fix the duplicate `Notice` problem.

I agree with this too!
