### ISSUE TITLE
Order Editing: Empty Order Note cell design

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#5112]
It was reported that the empty space in this row when the note is empty feels a bit unexpected.

<img width="426" alt="Screen Shot 2021-10-01 at 10 23 50 AM" src="https://user-images.githubusercontent.com/562080/135646402-a7aac325-90e3-4d72-a489-46354ad88d2a.png">

@adamzelinski do you think that is ok, or do you want to adjust it in some way?

**Comment by ghost** [comment]
I was under the impression Customer Note isn't shown unless there is one? If not, maybe that's the way to go. Otherwise, we could introduce an add action like so. Thoughts? CC @Garance91540 @Ecarrion 


<img width="544" alt="Screen Shot 2021-10-05 at 6 33 34 pm" src="https://user-images.githubusercontent.com/74938219/135979765-a98eac90-18e5-4db2-8d8a-4200c4918328.png">

**Comment by Ecarrion** [comment]
@adamzelinski That looks good to me!
