### ISSUE TITLE
Quick Order: Can tap "Cancel" to cancel quick order after tapping "Done," but order is still created

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-ios#5302]
**Describe the bug**

After I tap "Done" on the Quick Order screen, the "Cancel" button (or drag to dismiss action) are still available. If I cancel after tapping "Done," though, the order is still created.

**To Reproduce**

1. On a store that's onboarded for IPP, enable Quick Order in Settings > Experimental Features.
2. Go to Orders and tap the + button.
3. Enter an amount and tap "Done."
4. Immediately tap the "Cancel" button or swipe to dismiss the quick order screen.
5. Notice that the quick order seems to be canceled, but the order is created and appears in the Orders list anyway.

**Screenshots**

https://user-images.githubusercontent.com/8658164/139257580-cb3fd04e-20e4-450b-bacb-a40668a28bf7.mp4

**Comment by Ecarrion** [comment]
I'm assigning this to a trial candidate

**Comment by anas-p** [comment]
@rachelmcr @Ecarrion 
In the latest GitHub version, I noticed a separate workflow or Am I trying a different workflow?

https://user-images.githubusercontent.com/19687299/141257904-447f7d6b-6df3-4019-a65c-d38fc9b16c1e.mov

**Comment by Ecarrion** [comment]
Hi @anas-p Yes, that is an experimental flow that is behind a feature flag.

In order to see the production flow, you can set the following line to false during your development.

https://github.com/woocommerce/woocommerce-ios/blob/4fb64991809c42bdd99e5edad136062d0cb8ea8d/Experiments/Experiments/DefaultFeatureFlagService.swift#L24-L25
