### ISSUE TITLE
Render order note into receipt

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#5342]
# Report
It was reported(p91TBi-6nk#comment-7047) that it will be nice if receipts contain the order note information so there is some way for the merchant to remember what this is and adjust their inventory later.

# Task
- [ ] Render order note text into receipt

**Comment by joshheald** [comment]
![receipt with notes](https://user-images.githubusercontent.com/2472348/140745302-e6d053d1-c4c9-4b0a-9e92-bd3b13fd7cd5.jpg)

4 notes on this Quick Order, only the first of which was actually one I wrote.

@ctarda @allendav One problem with this; there are a bunch of payment related notes from Quick Orders (or any IPP payment) which would be shown on the receipt if we just show them all in a table. It also seems likely that for normal orders, there could be a number of notes added by plugins, as in general they're not expected to be customer-visible.

Ideally, I think we should only include those notes which have `isCustomerNote: true`... but there's no way to make such a note in the app at the moment 😞... If we did add that ability, those notes would be emailed to the customer (if an email address is available, so that won't affect quick orders)

As a short term workaround, we _could_ exclude all notes which are added after the `paymentIntent.created` date, which would resolve the problem until we can add the ability to save customer-visible notes. WDYT?

**Comment by Ecarrion** [comment]
@joshheald we could also render the "customer provided note" as a first iteration and see if that is good enough as a first iteration.

**Comment by joshheald** [comment]
@Ecarrion Yeah, we could and that would be simpler as that field would be less likely to have lots of notes added by plugins, and by definition seems appropriate to show to the customer. 
I think we would be misusing that field a little though, as these aren't really notes that the customer is providing, more notes that the merchant is writing. Perhaps that makes it less discoverable?

**Comment by Ecarrion** [comment]
Thinking about Quick Order(Simple Payments) That's the field merchants are able to modify so it would make sense for them to have that field printed.

**Comment by joshheald** [comment]
Will editing that field be a part of the Quick Order flow? When I do a quick order I'm not prompted to add any notes at the moment, so I'm adding them from the Order Details screen in between adding the order and taking payment.

**Comment by Ecarrion** [comment]
@joshheald the prototype does not include that option, but the full release will do
<img width="688" alt="Screen Shot 2021-11-08 at 8 39 04 AM" src="https://user-images.githubusercontent.com/562080/140751949-a597be2a-41ef-430a-bc61-3b8c99b38136.png">
.

**Comment by joshheald** [comment]
OK, will change this up to use the `Order.customerNote` field if it's not nil. Thanks for the clarification @Ecarrion
