### ISSUE TITLE
Can't select "Today" as initial start date on custom date range

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#5646]
**Describe the bug**
Unable to select today's date as start date when using custom date on date range filter.

**To Reproduce**
1. Go to Orders screen
2. Tap on Filter and select Date Range > Custom Range
3. On Start Date field, attempt to select today's date
4. See that nothing happens and today's date can't be selected

**Screenshots**

https://user-images.githubusercontent.com/17252150/145336405-4d428646-95a7-4f36-a714-cfb5c5553675.MP4

**Expected behavior**
Should be able to select today's date as start date on custom range

**Isolating the problem (mark completed items with an [x]):**
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13 Mini
- iOS version: 15.0
- WooCommerce iOS version: 8.1

**Comment by Ecarrion** [comment]
I'm assigning this to a trial candidate!

**Comment by chrisKns** [comment]
The problem lies in that the `UIDatePicker`(by default) has a starting initial date (defaults to current date), but the selected  `startDate` in `DateRangeFilterViewController` does not have initial value. Then we are listening for the value change event of the picker in `DatePickerTableViewCell`, so when the user taps the initial selected date, it does not trigger a value change event(since it is already the selected value).
Detecting when the user taps an already selected value in the datepicker is not easily done. But the underlying problem here is that the `UIDatePicker` has a starting value that is not in synch with the `startDate` in `DateRangeFilterViewController`. 
I think the best solution here is to automatically set the `startDate`/`endDate` in `DateRangeFilterViewController` when we tap to display the picker (if we do not have already a selected starting/ending date). This way the initial value that is displayed by the picker will match the `startDate` in `DateRangeFilterViewController`.

You can see that the default value the picker has is automatically selected, when the picker appears:

https://user-images.githubusercontent.com/96764631/151696716-16ac3bb0-4075-40bf-bb97-4b80d0255ac5.mp4
