### ISSUE TITLE
Orders List: Order status is not localized

### ISSUE THREAD

**Issue by itsmeichigo** [woocommerce/woocommerce-ios#5720]
**Describe the bug**
Currently we are using either `name` of `OrderStatus` returned from remote or raw value of `OrderStatusEnum`, both of which are not localized. So for users using the app in languages other than English they're seeing status in English by default.

**To Reproduce**
1. Change device language to any language supported by WooCommerce iOS app that is not English.
2. Open the app, switch to Orders tab
3. Notice that orders on the list all have statuses in English.

**Screenshots**
<img src="https://user-images.githubusercontent.com/5533851/146922281-e4cddd18-a60a-453a-98f7-14879b146ad8.png" width=320 />

**Expected behavior**
Order statuses should be localized.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Any iPhone or iPad
- iOS version: Any
- WooCommerce iOS version: 8.1

**Comment by hichamboushaba** [comment]
Just for visibility, as per the discussions p1640078180247200-slack-C6H8C3G23 and p1635346726086100-slack-C70PAM3RA, this is not completely non-localized, but instead, it respects the site's language instead of the device's one, and it's a corner case to have your device in a language different than your site.

But this doesn't mean it shouldn't be handled, it's just something to keep in mind when deciding, and we need also to think about custom statuses' when handling it.

**Comment by itsmeichigo** [comment]
Thanks for the explanation @hichamboushaba! Great point about custom statuses - we would not be able to handle all the cases for those custom ones then. I removed the `bug` tag and added `enhancement`, but it's very likely that we will not handle this for now.
