### ISSUE TITLE
Home screen glitch by scrolling up

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#5843]
While I was testing the new home screen update, I discovered a glitch that happens when I scroll up the view. It happens for me on a simulator running iOS 15.2 (device: iPhone 13 Pro Max). See the video below for more details.

https://user-images.githubusercontent.com/495617/148779976-16ca0c20-73f3-4cd9-a160-218f381a0ffe.mp4

**Comment by jaclync** [comment]
Update: after some debugging, the issue is from [showing/hiding the store name label when scrolling the dashboard](https://github.com/woocommerce/woocommerce-ios/issues/3959). Because we use a "hidden scroll view" as a large title workaround to propagate the scrolling content offset for the large title to shrink when scrolling up, the change of the store name label height breaks the content offset y and thus could cause weird scrolling behavior.

Commenting out the following line fixes the glitch but then the store name label is always shown. I'm still trying to figure out if there is a way to maintain the existing store name label visibility logic.

https://github.com/woocommerce/woocommerce-ios/blob/bf6413a942dee0ce06f91da3a5d43963c517777e/WooCommerce/Classes/ViewRelated/Dashboard/DashboardViewController.swift#L295
