### ISSUE TITLE
[Mobile Payments] Can't connect to reader after switching stores - terminal SDK incorrectly asks old store for token

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-ios#5912]
When testing #5868 I noticed the Terminal SDK asking the wrong store for reader tokens and location after switching stores.

**To Reproduce**
1. Add a breakpoint to the token fetch and location fetch, or `print` the siteID in those functions
2. Connect to a card reader
3. Disconnect the reader
4. As the same user, and without exiting the app, switch to a different store also set up for WCPay
5. Connect to the card reader
6. Observe the siteID the request is posted to

**Screenshots**
N/A

**Expected behavior**
The siteID fetched from should be changing as the store selected changes.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by allendav** [comment]
OK. I've confirmed this is a real problem. Here's the steps:

- In CardPresentPaymentStore > WCPayTokenProvider > fetchToken add a breakpoint or something like the following

`print("==== fetching token using wcpay remote for site \(siteID)")`

- Similarly, in CardPresentPaymentStore > WCPayTokenProvider > fetchDefaultLocationID add a breakpoint or something like the following

`print("==== fetching location using wcpay remote for site \(siteID)")`

- On a store with WCPay setup, enter Menu > gear (settings) > In-Person Payments > Manage card reader > Connect to card reader
- You should see the token fetch happen for the site, i.e.:

`==== fetching token using wcpay remote for site 197907611`

- When asked if you'd like to connect to a found reader, tap Connect to Reader. You should then see:

`==== fetching location using wcpay remote for site 197907611`

- Now, disconnect the reader and then switch to another store with WCPay set up
- After switching, tap on gear (settings) > In-Person Payments > Manage card reader > Connect to card reader
- You should see the token fetch happen **incorrectly - i.e. for the site you used to be connected to**, i.e.:

`==== fetching token using wcpay remote for site 197907611`

- When asked if you'd like to connect to a found reader, tap Connect to Reader. You should then see:
 
`==== fetching location using wcpay remote for site 201846069`

- Note the correct site ID is used for the location fetch.
- Unfortunately, the token being fetched for the wrong account has borked things up at this point. The connection to the reader will fail with "We couldn't connect to your reader"

- At this time, the only known work around until we fix this bug is to exit the app and start it again. Then you should be able to use the card reader for the "second" site.

**Comment by ctarda** [comment]
Just in case it helps:

StripeCardReaderService.setConfigProvider does this:

```
        if !Terminal.hasTokenProvider() {
            Terminal.setTokenProvider(tokenProvider)
        }
```

So, the second time there is an attempt to set a token provider, it will bail out and not call setTokenProvider. 

The documentation for [setTokenProvider](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPTerminal.html#/c:objc(cs)SCPTerminal(cm)setTokenProvider:) mentions that calling clearCacheCredentials should reset the token provider. 

So the problem is probably either one of the following or a combination of them:
1. We are not calling clearCacheCredentials when switching stores. 
2. We are calling clearCacheCredentials when switching stores but hasTokenProvider is still returning true, therefore we do not set the token provider for the second time.
3. The implementation of our clear() is not actually clearing anything. (see the comments in StripeCardReaderService.clear()
4. WCPayTokenProvider aggregates the siteID. It is possible that we are not actually re-initializing the class when switching stores.

**Comment by ctarda** [comment]
Dumping things here as I'm testing:

* When switching stores, I can see how StripeCardReaderService.clear() is hit, and we call Terminal.clearCacheCredentials()
* I added a print to the initializer of WCPayTokenProvider, to make sure the initializer is called anywhere after switching stores. It turns out, it is, and the site ID is passed properly
* So I looked at StripeCardReaderService.start() once again
* Followed the flow to setConfigProvider. And Terminal.hasTokenProvider() returns true, so we bail out and do not call setTokenProvider

So the source of the difficult solution is that, after calling Teerminal.clearCacheCredentials, Terminal.hasTokenProvider() still returns true, so we never call Terminal.setTokenProvider after switching stores. 

I think this is something we might need to bring up with Stripe? At the very least, check with them whether our assumptions about what Terminal.clearCacheCredentials is expected to do are correct.

**Comment by ctarda** [comment]
Actually, I've been reading the docs again, and we probably had the wrong expectations. 

The docs for [clearCacheCredentials](https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPTerminal.html#/c:objc(cs)SCPTerminal(im)clearCachedCredentials) say: 

```
In order to switch accounts in your app:

if a reader is connected, call disconnectReader:
configure the tokenProvider object to return connection tokens for the new account. The tokenProvider is implemented by your code, and you can do this however you want.
call clearCachedCredentials
call discoverReaders and connectReader to connect to a reader. The connect call will request a new connection token from your backend server via the token provider.
An overview of the lifecycle of a connection token under the hood:

When the Terminal singleton is initialized, the SDK attempts to proactively request a connection token from your backend server.
When connect is called, the SDK uses the connection token and reader information to create a reader session.
Subsequent calls to connect will re-use the reader session if the SDK has successfully connected to the reader already. Otherwise, it will require a new connection token when you call connect again.
```

**Comment by ctarda** [comment]
Here is a draft PR that might be taken as a starting point for a potential solution: https://github.com/woocommerce/woocommerce-ios/pull/5920
