### ISSUE TITLE
Settings: Drop case on row titles and alignment of version number

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-ios#598]
**Describe the bug**
Words in titles aren't all init-capped in the app; there are a couple instances in the help/settings screen that need to be lowercased. Also the version number should be bottom-aligned to coincide with the Android design unless @kyleaparker thinks differently. 😄 

**Screenshots**
![img_6400](https://user-images.githubusercontent.com/373903/51135009-a80bfa00-17fe-11e9-8068-140640c07eb7.png)

**Mobile Environment**
Please include:
- Device: iPhone X
- iOS version: 12.1.2
- WooCommerce iOS version: 1.0

**Comment by mindgraffiti** [comment]
@kyleaparker @astralbodies 

1. WordPress iOS uses Title Case everywhere in the Me section. It also makes sense to use it because the top line is the title for each row.

2. As for the Version number sitting "up high", it's because it's a native tableViewFooter element. The tableViewFooter is a view attached to the very last row of a table. Since this table doesn't have much content, the footer doesn't show up at the bottom of the screen. Maybe it's better to delete the version number that shows up in Settings > Help?

I say that because we have a detailed version number in Settings > About the app > WooCommerce:
<img src="https://user-images.githubusercontent.com/1062444/51188671-08a14280-18a4-11e9-9130-4f23f9654268.PNG" width="350" />

**Comment by mindgraffiti** [comment]
@kyleaparker 

JSYK, since we're reviewing all screens in settings, for Settings > Privacy Settings:
- I'm making the title at the top of the screen title case
- I'm making "Collection information" and "Report crashes" title case

I'm making them all title case because that is what Apple does in the Settings App.

Old screen for reference:
<img src="https://user-images.githubusercontent.com/1062444/51264764-d9123900-197c-11e9-88b1-aba5d280ed9d.png" width="350" />
