### ISSUE TITLE
Dashboard: Last updated phrases don't match design

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-ios#600]
**Describe the bug**
There are five recency messages: "Updated moments ago" "Updated x minutes ago" "Updated x hour/s ago" "Updated 1 day/s ago" "Updated on x y". I don't think the iOS app matches these exactly as I see "Updated just now" for the first one.

**To Reproduce**
1. Refresh the dashboard.
2. See "Updated just now" instead of "Updated moments ago".

**Screenshots**

From the design doc:
<img width="749" alt="2019-01-14_13-32-34" src="https://user-images.githubusercontent.com/373903/51135941-dee30f80-1800-11e9-83cd-1224bb255b61.png">

**Mobile Environment**
Please include:
- Device: iPhone X
- iOS version: 12.1.2
- WooCommerce iOS version: 1.0

**Comment by bummytime** [comment]
Just leaving some quick notes here. Also, because of localization, this is not a simple issue to fix.

**1.** The current recency message is created using the `mediumString()` func in the `Date` extension within WordPressShared. This method uses the [`TTTTimeIntervalFormatter` lib](https://github.com/mattt/FormatterKit#ttttimeintervalformatter) which is actually quite comprehensive in what it does and is designed to be localized (managing deictic expressions).

**2.** "Just now" does not translate well in some languages. See #620
