### ISSUE TITLE
Order Creation - Product Sync: Do not store / list auto-draft orders

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#6228]
When we create an order as part of the `RemoteOrderSynchronizer` logic, it is stored and shown in the order list screen.

`auto-draft` orders should not be shown as they are not returned by the `Order API` 

One way to fix this is to add a parameter in the `order creation action` to not store the order in our storage layer.

<img width="438" alt="Screen Shot 2022-02-17 at 11 35 29 PM" src="https://user-images.githubusercontent.com/562080/154618403-7be283d7-ebdd-4815-9ae2-ecc5a243f42a.png">

**Comment by rachelmcr** [comment]
Leaving myself a couple notes about this:

* It might be a good idea to discard the `auto-draft` orders on any order `upsert` into storage (since I don't think we ever want to persist them in storage), or perhaps we could do that in the order creation/update actions. Not sure if those approaches are too hidden / not explicit enough, in case there are scenarios where we want to handle auto-drafts differently.
* If we do it with a parameter on the order creation/update action, we'll have to be careful to check the `baseSyncStatus` when we set the parameter in the synchronizer. (We don't want to store `auto-draft` orders, but we should store `pending` orders when that's the base sync status since those orders are expected in the order list.)

Also we're planning to add a discard prompt (https://github.com/woocommerce/woocommerce-ios/issues/5815), which isn't a comprehensive solution but should also help with cleanup.
