### ISSUE TITLE
More localization issues

### ISSUE THREAD

**Issue by bummytime** [woocommerce/woocommerce-ios#631]
It appears like we have some additional localization issues in the app.

### Notifications screen

<img width="382" alt="screen shot 2019-01-23 at 1 05 08 pm" src="https://user-images.githubusercontent.com/154014/51632957-1430e100-1f16-11e9-8073-9bae57c83f5c.png">

<img width="382" alt="screen shot 2019-01-23 at 1 05 52 pm" src="https://user-images.githubusercontent.com/154014/51632969-23179380-1f16-11e9-9660-6c437cf46847.png">

### Order List Screen

Specifically whenever a filter is applied to the list (the "All" filter is translated as expected): 

<img width="277" alt="screen shot 2019-01-23 at 1 54 15 pm" src="https://user-images.githubusercontent.com/154014/51633124-84d7fd80-1f16-11e9-9fb7-cc3363711d9c.png">
<img width="277" alt="screen shot 2019-01-23 at 1 54 24 pm" src="https://user-images.githubusercontent.com/154014/51633129-86a1c100-1f16-11e9-9299-43cbd0acd240.png">
<img width="285" alt="screen shot 2019-01-23 at 1 54 34 pm" src="https://user-images.githubusercontent.com/154014/51633133-87d2ee00-1f16-11e9-97ff-1fc9b5a93cdb.png">

**Comment by naokomc** [comment]
For many locales, "Notifications" is currently Fuzzy status.

https://translate.wordpress.com/projects/woocommerce%2Fwoocommerce-ios/-all-translated/244821/

I wonder if this was caused by a change in context? If the change is minor, I can approve them so the status is set to Current.

"Orders: (filter)" translations exist for all locales since 2018-11-14.
https://translate.wordpress.com/projects/woocommerce%2Fwoocommerce-ios/-all-translated/244836/
