### ISSUE TITLE
Order Creation - Product Sync: Immediately perform additive changes

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#6339]
When adding new items to the order, we should immedially fire those requests to avoid scenarios where the user is able to open new screens to then be blocked while the network requests completes.

https://user-images.githubusercontent.com/3132438/156133573-3d5d5520-58fa-4c5f-9084-cff60a6db2b1.mp4

**Comment by rachelmcr** [comment]
I've been working on this and should have a PR up soon, but I wanted to make a few notes about what I found.

Right now we're debouncing before performing the sync for every input:

https://github.com/woocommerce/woocommerce-ios/blob/0d73cc3d5f0fd6304065c3de9344c02c55743155/WooCommerce/Classes/ViewRelated/Orders/Order%20Creation/Synchronizer/RemoteOrderSynchronizer.swift#L160-L176

* Up to now we've been debouncing the inputs before doing any sync work. Removing this debounce causes a race condition: We use these inputs to update the order in `bindInputs()`, but we also use them to start the sync here. However, since we get `self.order` directly for the sync it may not be updated yet (the debounce was effectively slowing down this operation enough that it wasn't an issue). To resolve this, we need to make sure `bindOrderSync()` is not just using the input event as a trigger but actually using the updated order with that input.
* Once `bindOrderSync()` uses the updated order, we can change the debounce behavior. Since the main issue is wanting to immediately block interactions during additive changes, we can debounce _after_ setting the blocking state. That way we can still debounce normally (we don't have to figure out a way to conditionally debounce the requests) but that debouncing doesn't delay any blocking that needs to happen in the UI.
* We may want to use `.throttle` instead of `.debounce` to make sure that the first request is fired immediately. That should help us act faster on UI-blocking requests while still throttling other changes to the order that happen more quickly.

**Comment by Ecarrion** [comment]
Nice findings @rachelmcr! Two small thoughts!

1. As it seems we will be solving more than one issue, would you mind splitting them into different PRs so we can do a good review of them?

2. I know I created this issue because "ideally" we would want to perform additive changes immediately but after having the feature on the wild this has appeared to be a problem for our users, so maybe we don't need to fix it 🤷

**Comment by rachelmcr** [comment]
> As it seems we will be solving more than one issue, would you mind splitting them into different PRs so we can do a good review of them?

Definitely! I did a little testing yesterday and I don't think switching from `debounce` to `throttle` makes sense here, so it'll just be the first two issues I mentioned. I'll open separate PRs for those once the fixes are ready.

> after having the feature on the wild this has appeared to be a problem for our users, so maybe we don't need to fix it

I agree that we haven't heard of any issues from our users, but I think it's still worth fixing. For one thing, once I finally worked out what was going on I was most of the way to a fix. 😆  But also, even if no one complains about the current behavior, having the immediate UI feedback (having it immediately block the UI instead of waiting to debounce) really feels like an improvement to me.

I think it's the kind of thing that you may not consciously notice or necessarily have problems with, but you still notice that something feels better when it's fixed.

**Comment by Ecarrion** [comment]
True, I also think it will be a great learning experience for all of us, so if the fix is not something that would make the code harder to maintain, go for it!
