### ISSUE TITLE
Order Creation: Autofocus keyboard on Customer Note

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-ios#6581]
Reported by @jaclync in CFT

> It’d be nice if the keyboard comes up automatically on the Customer Note screen

**Comment by jaclync** [comment]
After taking a look at the `EditCustomerNote` SwiftUI view, autofocus works in iOS 15+ while I tested with an iOS 14.5.1 device in the first place 😅 

https://github.com/woocommerce/woocommerce-ios/blob/795eec8fe9ea522fdfcbda1542f3a775e91bd35a/WooCommerce/Classes/View%20Modifiers/View%2BAutofocusTextModifier.swift#L27-L29

Since it's working in iOS 15, closing this issue!
