### ISSUE TITLE
Order Creation: Percentage Fee Shown as `1000` on Order With No Products

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-ios#6647]
**To Reproduce**
1. Start with creating a new order,
2. Without adding any product yet, select "Add Fees"
3. Enter any value as Fee, tap Done,
4. Tap "Fees" again, then tap the "%" tab,
5. "Amount (%)" will show `1000`, which is inaccurate.

This also happens on step 2 if Products with zero price is added first.

https://user-images.githubusercontent.com/266376/163383341-adf7beff-de56-4888-84bb-e745f1e3a884.MP4

**Comment by rachelmcr** [comment]
So there's a logical explanation for this behavior, but I'm not sure how it aligns with expectations or how we want it to behave:

* When you add a fee, it's added as an amount to the order.
* When you edit an existing fee on the order, we show the fee amount but we also calculate and display the percentage based on the order total minus the fee itself.
* Because tax is on a separate line (and is a total of the tax for everything in the order), it's included when calculating the fee percentage.

In the reported scenario, there is an $0.80 tax added to the order (automatically calculated by the store and added after adding the fee to the order). The percentage fee is then calculated to be 1000%, because the $8 fee is 1000% of $0.80 (the order total $8.80 minus the $8 fee, i.e. the added tax).

Some considerations:

* Right now we use the `totalTax` from the API for the tax amount, so if we want to try to exclude the fee-related tax amount from this calculation, we'll have to figure out if it's feasible to use each tax line and filter out the fee-related tax.
* If we don't exclude the fee-related tax, then any time you edit the fee and use the percentage option, you're effectively adding a little extra (since a newly calculated fee in theory should exclude both the previously added fee and any related tax).
* Other solutions might include not allowing merchants to switch to the percentage when editing existing fees, or maybe make sure the remote sync first removes the previous fee (and tax) before calculating and adding the new fee.

This is the same behavior as on Android, so if we change how this works we should make sure both platforms are updated. cc @ThomazFB @shiki

**Comment by nbradbury** [comment]
We have [a similar issue](https://github.com/woocommerce/woocommerce-android/issues/5973) on Android.

**Comment by shiki** [comment]
Nice sleuthing, @rachelmcr! And thanks for reporting this, @hafizrahman! 

If I understand this correctly, the percentage calculation is working correctly and 1000% is correct. It looks like whatever solution we come up with, the calculation will always be confusing. 😬 

Maybe it would be best to leave this alone for now. I'm curious if what @atorresveiga made in https://github.com/woocommerce/woocommerce-android/pull/6151 would help make the calculation more transparent and that would be good enough.

**Comment by atorresveiga** [comment]
The strategy I followed to overcome this issue [here](https://github.com/woocommerce/woocommerce-android/pull/6151) was :

> When you edit an existing fee on the order, we show the fee amount but we also calculate and display the percentage based on the order total minus the fee itself.

We changed the percentage calculation to take into account the fee taxes. So the percentage will be calculated based on 
Order Total - (Fee + Fee taxes)

Also, we have a check that if Order Total = (Fee + Fee taxes), we hide the percentage calculation. 

Finally, based on [this discussion](https://github.com/woocommerce/woocommerce-android/issues/5973) as we don't have a way to store a _Percentage fee_ , we decide to show the merchant a caption to the field with the **calculated amount**.

As Joe commented [here](https://github.com/woocommerce/woocommerce-android/issues/5973#issuecomment-1081351873):

> You’ll enter the percentage, see the dollar value, and confirm your decision. Then on the order details screen, you’ll recognise the dollar value when you see it again.

Something like this:

<img src="https://user-images.githubusercontent.com/18119390/161287841-190c1005-659f-4272-9aa4-2cf80932f865.png" width="300">
