### ISSUE TITLE
In-person payments: handle amounts under the minimum value in the US and CA properly

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#6736]
Ref: p1650975321959889-slack-C025A8VV728

In-person payments are only allowed for amounts above the minimum [50 cents in the US and CA](https://stripe.com/docs/currencies#minimum-and-maximum-charge-amounts) (this value might differ in other currencies when we support other countries). We can add this minimum charge value to `CardPresentPaymentsConfiguration` and then check this even before card reader connection (right now it's after the reader is ready).

https://github.com/woocommerce/woocommerce-ios/blob/29392f97d49c40125919789b9151b76cc4248a21/WooCommerce/Classes/ViewModels/CardPresentPayments/PaymentCaptureOrchestrator.swift#L42-L48

The tasks include:
- [x] Move the "0.5" minimum amount to `CardPresentPaymentsConfiguration` so that we can configure different values in each country
- [x] Move the minimum amount check from `PaymentCaptureOrchestrator` to `CollectOrderPaymentUseCase` before the card reader connection
- [x] Make the alert for this error non-retryable

**Comment by joshheald** [comment]
> Fix the incorrect currency in the minimum amount message in the alert (CAD should be shown in CA stores):

@jaclync I don't think this is required – we show a plain $ symbol for CAD everywhere else in Canadian stores. Android are also changing to show plain $ symbols for both US and CA in this modal (currently they show USD after the amount in this modal.)

I agree that it would be better if currency were set to match the store, rather than a hardcoded string, for the future... and we may want to consider taking device locale into consideration for when we display it too. But I think this task can be about moving the check earlier and non-retryable.
