### ISSUE TITLE
Settings > Switch Store > Site Picker can trap a user in the flow

### ISSUE THREAD

**Issue by mindgraffiti** [woocommerce/woocommerce-ios#678]
**Describe the bug**
[Background](https://github.com/woocommerce/woocommerce-ios/pull/660#issuecomment-462388240)
If the user goes to Settings > Switch Store and switches to airplane mode, they can become trapped by the UX. There is no Cancel or Back button to take them out of the site switching flow.

Internal ref for uxtrap.patch p1549923119041400-slack-C6H8C3G23

**To Reproduce**
1. Settings > Switch Stores
2. Wait for the Site Picker to appear
3. Turn off data by switching to airplane mode and turning off wifi
4. An error pops up stating "Unable to connect to store" and there is no way to back out of the flow.

**Screenshots**
<img src="https://user-images.githubusercontent.com/154014/52575187-66617580-2de3-11e9-9359-096c26401156.png" width="300" />

**Expected behavior**
There are multiple ways to fix this flow. The issue is not changing the UI, but rather the tightly coupled actions and network calls happening in the background.

The UI is the easy part:
- add a nav bar with the Back button (and move Help to the nav bar)
- add a Cancel button on the left (and leave the Help button on the right)
- make an exception for this error message and change the "Retry" button to "Go back"

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active. **- N/A**
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/). **- N/A**
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: (all)
- iOS version: (all) 
- WooCommerce iOS version: 1.2

**Comment by bummytime** [comment]
This is not a showstopper, but I wanted to capture it here so we can all think on this....

An additional flow to consider is what currently happens when a user does the following:

1. User navs to Settings → switch store
2. Store picker is displayed
3. App is force killed
4. On next launch user is logged out

![switch_site](https://user-images.githubusercontent.com/154014/52798626-ee42bc00-303d-11e9-9006-7046e322a488.gif)

Do we think force-ably deauthenticating the user is the best option in this situation. 

Just to make things interesting, we **DO** need to deauth the user on the site picker screen when it is foce-killed during the main login flow:

![switch_site_original](https://user-images.githubusercontent.com/154014/52798903-7cb73d80-303e-11e9-953a-029cb2ecaa02.gif)

😄

**Comment by rachelmcr** [comment]
> Do we think force-ably deauthenticating the user is the best option in this situation?

I happened to run into this today while testing the experience and messaging with a bad/no network connection. I killed the app to try to effectively cancel the "Switch store" action, because I couldn't navigate away without a connection, and was really surprised that this deauthenticated me. As a user I wouldn't expect that at all.

**Comment by bummytime** [comment]
Also, while we are at it, let's update the update warning text ala WCAndroid: https://github.com/woocommerce/woocommerce-android/pull/866
