### ISSUE TITLE
[Mobile Payments] Wrong string on low battery card reader message

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#6787]
**Describe the bug**

The modal shown when a card reader update fails due to low battery contains a stray unicode sequence in Spanish:

**To Reproduce**
1. Go to Settings -> In-Person Payments
2. Attempt to connect to a reader that has a pending update and low battery
3. See error

![Screen Shot 2022-05-06 at 12 24 11](https://user-images.githubusercontent.com/8739/167114499-c3cfcd0e-76e5-4889-a2a9-3956b08752de.png)

**Comment by koke** [comment]
@AliSoftware I noticed [your comment on GlotPress](https://translate.wordpress.com/projects/woocommerce/woocommerce-ios/es/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=702360&filters%5Btranslation_id%5D=12181065), but it doesn't seem to be working correctly

> Note: I had to replace the regular `%` percent character (U+0025) in this translation with the `%` “Full Width Percent Sign” character (U+FF05, see https://www.fileformat.info/info/unicode/char/FF05/browsertest.htm) because our linter considered that in the `50% de carga` part, the `% d` were a placeholder (indeed `%d` is a valid placeholder we use for a numeric value that is inserted dynamically into out strings) and detected that this string didn’t contain such placeholders in the original so (falsely) considered it a violation.
This is something we hope to fix in our linter, but in the meantime, using the FullWidth Percent Escape character instead was an easy workaround that still made sense in the copy.

**Comment by koke** [comment]
It looks like [it might need to go in brackets](https://docs.swift.org/swift-book/LanguageGuide/StringsAndCharacters.html#ID295)?

```
  6> "50\\uFF05"
$R5: String = "50\\uFF05"
  7> "50\u{FF05}" 
$R6: String = "50％"
```

**Comment by koke** [comment]
No variation seems to be working 🤔 @AliSoftware I just realized that your comment was on the pt-BR translation, which still has the regular `%`, but it was replaced in `es`, `fr`, and `sv`. Neither have a `d` following the `%`. Can we revert the translations to using a regular % symbol and see if the linter is happy now?

**Comment by AliSoftware** [comment]
@koke as an alternative, would it be ok to use `String(format: "50%%")` here to trick the linter?

Basically our linter can't know when a string seen in a `Localizable.strings` will be used directly (without formatting) or via `String(format:)` so the only thing it can do is assume that if there's a `%` in the string it's meant to be formatted.

Which means:
 - Using a literal `%` will make the linter sometimes interpret this as a placeholder (if followed by `d` or `s` for example in one of the translations), sometimes not (followed by something invalid for a fprintf-like placeholder)
 - Using `\u{FF05}` _should_ work… and actually even using `\u{0025}` — for the regular percent sign but via its unicode codepoint rather than its literal — as `String(format:)` — and thus our linter — would not see that as a potential placeholder
 - Another alternative would be to use the `％` literal in the original (👈  this is not the literal for `0x25 PERCENT SIGN` but the literal for `0xFF05 FULLWIDTH PERCENT SIGN`), so that it wouldn't be confused by the linter for a potential placeholder. This would still put us at risk that some translators don't realize that this is _not_ a standard percent sign literal, and use a standard percent sign literal in their own translation (then making the linter potentially wrongly see it as a placeholder again). But then if that happens we could go correct it in GlotPress to replace their percent sign literal with a `％` literal instead 🤷 
 - Another option would be to embrace that the linter will consider that all strings might go thru `String(format:)`… and so make that string go thru it as well. So you'd make the original be `String(format: NSLocalizedString("half_battery", value: "50 %% of battery", comment: …))`, which could look a bit useless (going thru `String(format:)` while we don't have any placeholder nor parameter to replace…) but would totally work (and make the linter happy)

---

A final option now that I've recently implemented the ability to finally use arbitrary keys for localized strings instead of being constrained by using the English copy (See paNNhX-nP-p2#arbitrary-keys) is that we could consider modify the linter to consider that if the key name ends with, say, `[nofmt]`, then the linter would ignore it.
For this option to be possible, this will require:
 - To wait for @mokagio to finish porting my new L10n Tooling to WooCommerce (it's currently only on WPiOS, but Gio is actively working on porting it to WCiOS and should hopefully have it during next sprint 🤞 )
 - For me to slightly modify the linter to make it ignore keys ending in `[nofmt]`. This should be pretty easy actually
 - Then you'd be able to use `text = NSLocalizedString("half_battery[nofmt]", value: "You must be at 50% minimum", comment: "…")` to bypass the linter for that specific key

---

All that being said, that last option could look interesting (including for the long term), but for the immediate case of the but you reported, I think changing the value in GlotPress for that translation to use `\u{FF05}` (or even the `％` full-width percent literal directly) instead should be way enough for an quick fix of this.

**Comment by koke** [comment]
> Using a literal % will make the linter sometimes interpret this as a placeholder

TIL a [space is a valid flag](https://pubs.opengroup.org/onlinepubs/009695399/functions/printf.html) for formatted strings 🤯 

I think using `String(format:)` might be the simplest solution, even if it looks awkward 🤷🏽

**Comment by koke** [comment]
@AliSoftware actually, I understand the linter runs on the `Localizable.strings` file right?

I was not entirely happy with `FULLWIDTH PERCENT SIGN`, as it's visually very close to %, but still slightly different. And while researching this, I came across [this StackOverflow post](https://stackoverflow.com/questions/23452906/ios-localization-unicode-character-escape-sequences-which-have-the-form-uxxx) that mentions `NSString` and strings files escaping things slightly differently. It looks like strings files use `\Unnnn` for escaping, which seems to work.

If I replace the text in the Spanish strings file with `...por encima del 50\U0025 antes de...`, it seems to work fine and uses the regular percent sign. Can you confirm that the linter will be happy about this one?

**Comment by AliSoftware** [comment]
> TIL a [space is a valid flag](https://pubs.opengroup.org/onlinepubs/009695399/functions/printf.html) for formatted strings 🤯

Yep, that the whole issue, which makes `% d` — which is still quite likely to be found in a regular copy, more likely than `%d` at least — to be considered a placeholder… and thus causing the whole issue

> @AliSoftware actually, I understand the linter runs on the Localizable.strings file right?

Correct

> If I replace the text in the Spanish strings file with ...por encima del 50\U0025 antes de..., it seems to work fine and uses the regular percent sign. Can you confirm that the linter will be happy about this one?

Yes, I think it should be happy, because:
 - We don't use [the `-u` flag](https://keith.github.io/xcode-man-pages/genstrings.1.html#u) when [calling `genstrings`](https://github.com/wordpress-mobile/release-toolkit/blob/ae15f11f1c635e8457a7a18aab51c4df0ebe9f64/lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_generate_strings_file_from_code.rb#L6-L8) to generate the `en.lproj/Localizable.strings` file from source — which is then sent to GlotPress for translation — so that should be kept as `\U0025` in the `.strings` file and not transformed into its literal character equivalent
 - When translators will translate this, if they keep the `\U0025`, I don't think GlotPress will replace that with the literal during export, but instead keep that `\U0025` verbatim as written by the polyglots in their translation, so that shouldn't be transformed into the literal equivalent either

Which means that both the `en.lproj/Localizable.strings` generated by `genstrings` and the `*.lproj/Localizable.strings` downloaded from GlotPress should (🤞) keep `\U0025` and not making the linter risk interpreting this as a `fprintf`-style placeholder! 🎉

**Comment by koke** [comment]
> I don't think GlotPress will replace that with the literal during export, but instead keep that \U0025 verbatim as written by the polyglots in their translation, so that shouldn't be transformed into the literal equivalent either

Unfortunately, GlotPress escapes the backslash and turns it into `\\U205`, which doesn't work :(
I've replaced the GlotPress translations with the literal `％` which seems to be working fine. Maybe the linter should check that there are no `\\` in translations, if that's not going to work.

Closing this, since it's fixed in GlotPress, and the fix will be picked up the next time we update translations.

**Comment by AliSoftware** [comment]
> Unfortunately, GlotPress escapes the backslash and turns it into \\U205

Mmmh I wonder if we should consider that a bug to be reported in GlotPress then… 🤔 

When you say GlotPress escapes the backslash, what do you mean exactly btw, did you try to write `\U0025` for a translation in GlotPress, then tried to export the `.strings` files from the GlotPress UI? Or did you try using our scripts? Or input the `\U0025` somewhere else? And does it really turn it into `\\U205` or is it `\\U0025` and your comment above was a typo?

> Maybe the linter should check that there are no \\ in translations, if that's not going to work.

I think that would be risky and opening a can of worms, since I could also imagine `\\` being totally valid in a translation (albeit rare and improbable)…

> I've replaced the GlotPress translations with the literal ％ which seems to be working fine.

Let's roll with this for now and see how it goes then.

Probably the next best thing, if your use of the literal `％` isn't enough, or to avoid similar issue in future cases, would be to implement that `[nofmt]` idea on the linter (once @mokagio finishes porting the new tooling to WCiOS to allow us to use arbitrary keys), but let's see if that need actually reappears before starting to implement that (priorities, priorities…)

**Comment by koke** [comment]
> did you try using our scripts?

IIRC, I used the `update_translations` script while testing this.
