### ISSUE TITLE
[Coupons] - No discard alert when swiping down to cancel editing a coupon

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#6836]
**Describe the bug**
When a user uses swipe-down gesture to close the edit coupon screen after making some changes, there are no alerts about discarding the changes. On some screens on the app, this action would trigger an alert (e.g. Shipping Address screen on Orders)

**To Reproduce**
1. Turn on Coupon Management experimental feature
2. Select a coupon > Edit Coupon
3. Make some changes on the coupon and swipe down to cancel
4. There's no alert warning about discarding the changes

**Expected behavior**
When changes have been made, it would be better if there is a warning about discarding it when the swipe down gesture is used as the swipe down could be accidental from the user.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13
- iOS version: 15.3.1
- WooCommerce iOS version: AppCenter build pr6809-84ae456

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by ThomazFB** [comment]
@itsmeichigo @pmusolino I would like to get some input about a strategy to fix this issue. I've been investigating ways to intercept the swipe-down dismissal of a modal through a SwiftUI view, and so far, I've only found the `.interactiveDismissDisabled()` function, which is not exactly the solution we're looking for here. Also, it's only available starting from iOS 15.

But then I reminded myself that the WCiOS Order Creation modal view is actually able to intercept the swipe gesture and send the discard alert. So, after taking a look there, correct me if I'm wrong, but it looks like this interception is possible because the `NewOrder` view relies on a `UIHostingController` wrapping structure that implements the `UIAdaptivePresentationControllerDelegate` and triggers the alert when the `presentationControllerDidAttemptToDismiss` is called. 

With that said, should we do the same to achieve this interception inside the `AddEditCoupon`? Or maybe do we have another option or strategy I'm not aware of? What do you folks think?

**Comment by itsmeichigo** [comment]
Good point! I'm thinking that even if we drop support for iOS 14, using `.interactiveDismissDisabled()` will only disable the swiping gesture and we can't present the confirm alert with this modifier, so it might not be what we want.

It'd be nice if we could use the same approach as we did on `NewOrder` screen. I still haven't found a solution yet though, since the `AddEditCoupon` view is now presented the SwiftUI way, and it's not possible to check for its hosting controller.

**Comment by itsmeichigo** [comment]
I've even tried a hacky workaround like adding this in `viewDidLoad` of `CouponDetailsHostingController`:
```Swift
subscription = publisher(for: \.presentedViewController)
            .sink { [weak self] viewController in
                guard let self = self else { return }
                viewController?.presentationController?.delegate = self
            }
```
I wanted to set the delegate to any view controller that is presented on top of this view controller - but it seems that presenting the `AddEditCoupon` view the SwiftUI way doesn't trigger any update to the hosting view controller's `presentedViewController` or `viewWillDisappear`.
