### ISSUE TITLE
[Coupons] - Unclear error when updating percentage discount coupon to more than 100%

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#6837]
**Describe the bug**
When updating a percentage discount coupon to more than 100%, there is an error displayed when attempting to save. However, the error is generic so if there were multiple changes made at the same time, it could take a while to realized what the error is for.

**To Reproduce**
1. Turn on Coupon Management experimental feature
2. Select a percentage discount coupon
3. Edit the coupon code and update percentage discount to more than 100%
4. Save coupon - see that there is an error displayed saying that something went wrong

**Screenshots**

https://user-images.githubusercontent.com/17252150/168037691-39886921-6f3c-4de4-93db-1fc3be2d9793.MP4

**Expected behavior**
The error should describe what the issue is so that user can take action to correct it.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13
- iOS version: 15.3.1
- WooCommerce iOS version: AppCenter build pr6809-84ae456

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by ThomazFB** [comment]
@itsmeichigo @joe-keenan looking at how the Woo Core handles this scenario of a discount percentage above 100%, there's no clear error there too. It just ignores the input and reverses to the previous value as it was before the update. From the mobile perspective, instead of relying on a network/generic error, maybe we could use a local validation for this scenario with a specific message hinting that a percentage above 100% doesn't make sense. What do you folks think about it?

**Comment by itsmeichigo** [comment]
There was a discussion about what we should validate, but we decided to follow the web (p91TBi-7FL-p2#comment-9095). Personally, I'd prefer at least some basic validation like this one since it's pretty obvious. Let's wait to see what the design team thinks though.

**Comment by joe-keenan** [comment]
Validation sounds great! I always wish we could validate as soon as the field loses focus since that allows people to correct any mistakes before attempting to submit. I get that that isn’t always possible though.
For the UI, just showing an error state of the field with error text below it should be enough, right?
