### ISSUE TITLE
[Coupons] - Selecting a word from keyboard suggestion display results not found on Edit Product Categories screen

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#6839]
**Describe the bug**
On the Edit Product Categories screen, when searching and selecting a word from the keyboard suggestion, it will result in results not found. It could be because of the extra space on the selected word.

**To Reproduce**
1. Turn on Coupon Management experimental feature
2. Select a coupon
3. Edit the coupon code and go to Edit Product Categories
4. Search for a product category but use the keyboard suggestion to select the word
5. See that no results are found
6. Type the same word and see that results are displayed

**Screenshots**

https://user-images.githubusercontent.com/17252150/168041734-231b84fb-35b3-40ee-b31f-4e475a60f617.MP4

**Expected behavior**
Search should return the correct results when user selects a word from the suggestion

**Mobile Environment**
Device: iPhone 13
iOS version: 15.3.1
WooCommerce iOS version: AppCenter build pr6809-84ae456

**Comment by pmusolino** [comment]
I believe that one of the reason is because tapping the suggested word, it add an extra space in the search text field, and that's why it's not returning the expected category. API search isn't super smart, so it doesn't understand it should take away that space. I wonder if it should stay that way, or should we virtually take out that space under the hood ourselves.

**Comment by itsmeichigo** [comment]
Just to clarify: I'm searching categories locally using CoreData query instead of calling the API since we are fetching all categories recursively. I'll trim the extra space on both ends of the query to fix this issue
