### ISSUE TITLE
Add Swipe to Refresh to Coupons Empty case

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-ios#6898]
There is no swipe to refresh available when coupons list is empty and displays the empty case. This means that when creating the first coupon from `wc-core` we need to navigate back and re-open coupons list to be able to see the new added coupon

**Comment by itsmeichigo** [comment]
This should be a subtask for #6356 - since we've migrated all empty views to [`GhostableViewController`](https://github.com/woocommerce/woocommerce-ios/blob/trunk/WooCommerce/Classes/ViewRelated/ReusableViews/GhostableViewController.swift), we should update this controller to enable pulling to refresh.

**Comment by JorgeMucientes** [comment]
Perfect! I'll close the issue and mark it as duplicated.
