### ISSUE TITLE
[Order Details] Shipping label section should be shown below Refunded Products section

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-ios#7073]
![Image](https://user-images.githubusercontent.com/2472348/173091972-4c33362f-ce93-4b16-a1d7-b76d19798eb2.png)

> [iOS] should also show the Refunded Products section above the Shipping Label section. This keeps all product information together and removes ambiguity around what has been refunded and what hasn’t.
> – @joe-keenan

**Comment by iamgabrielma** [comment]
Some initial debugging:

By checking the `OrderDetailsDataSource`, it seems that at the moment we're rendering some shipping label related elements within the products section/row, for example [here](https://github.com/woocommerce/woocommerce-ios/blob/ef94fd64422bf32f58a5d38433dc3805d436bf3e/WooCommerce/Classes/ViewModels/Order%20Details/OrderDetailsDataSource.swift#L1009), we're appending the `.shippingLabelCreateButton` directly to the products section, in the `.aggregateOrderItem` row

At first glance seems that we can keep the same logic but re-arrange and append these to either an existing section/row (`shippingLabelSections` perhaps?) or create a new one depending on how it looks on Android.

**Comment by joe-keenan** [comment]
Hey @iamgabrielma, I think this is less complicated than you suggest.
The **Create Shipping Label** button appears on the products section. This is fine because we can assume that shipping labels will only be useful for orders with products.
Once the label has been created, we show a new section with a **Print Shipping Label** button and some information.
Additionally, if refunded products exist, they also have their own section. 
This task is about ensuring the **Refunded Products** section always follows the **Products** section. Right now, on iOS, the Print Shipping Label section is shown in between the two.

Sorry if this was already obvious to you. I just read my quoted description and realised it wasn’t 100% clear!

**Comment by iamgabrielma** [comment]
> The Create Shipping Label button appears on the products section. This is fine because we can assume that shipping labels will only be useful for orders with products.

> This task is about ensuring the Refunded Products section always follows the Products section. Right now, on iOS, the Print Shipping Label section is shown in between the two.

Thanks for the clarification @joe-keenan , definitely helpful 🙇
