### ISSUE TITLE
App Widget - No padding between the Store title and the widget

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-ios#7797]
There seems to be no padding between the Store title and the widget.

![WhatsApp Image 2022-09-29 at 12 21 24 PM](https://user-images.githubusercontent.com/1331230/193265102-34185e76-27f4-4eaa-826d-d2e99d169594.jpeg)

This happens when the larger accessibility text is off and the font is set to a particular size. Please refer to the image below. For the rest of the font sizes, the widget seems to have proper padding.

![WhatsApp Image 2022-09-29 at 3 52 52 PM](https://user-images.githubusercontent.com/1331230/193265153-9511ecb4-8a8a-4024-8e21-dd138905dbdf.jpeg)

**Comment by ealeksandrov** [comment]
@AnirudhBhat thanks for the report! Can you confirm what iOS version you were using?
I've tested widget with described text size in 3 simulators and I see it as iOS 14-specific issue.

iOS 14.5|iOS 15.5|iOS 16.0
--|--|--
![ios-14 5](https://user-images.githubusercontent.com/3132438/195670168-b14b1027-fb06-4fdd-84f6-bffe3639f7a5.png)|![ios-15 5](https://user-images.githubusercontent.com/3132438/195670180-7bc25a48-52f4-4887-a8fe-3fc8dd40cce0.png)|![ios-16 0](https://user-images.githubusercontent.com/3132438/195670182-a97e87fb-9c32-4365-bfa6-a8c8bdb09d1d.png)

Since we're [removing iOS 14 support](https://github.com/woocommerce/woocommerce-ios/pull/7851) in this sprint, I consider the issue as wontfix.

**Comment by ealeksandrov** [comment]
Added [a small fix](https://github.com/woocommerce/woocommerce-ios/pull/7861) since we're keeping iOS 14 deployment target until 10.9 (p1665735758971909-slack-C6H8C3G23).
