### ISSUE TITLE
Order Details refresh issue

### ISSUE THREAD

**Issue by bummytime** [woocommerce/woocommerce-ios#789]
I noticed an intermittent issue on order details where the layout gets messed up when pulling-to-refresh:

![refresh bug](https://user-images.githubusercontent.com/154014/54457438-667cca00-472f-11e9-862d-da496d144905.gif)

This issue doesn't appear to occur on first load of the screen (from notifications, order list, or search) — typically you see it when refreshing the screen in-place.

**Comment by rachelmcr** [comment]
I ran into this today while testing version 1.6.0.0 (TestFlight beta). For me, it seems to happen every other time I pull to refresh — the layout alternates between looking right and having this issue.

**Comment by ctarda** [comment]
Potentially related to #1021

**Comment by jaclync** [comment]
after some debugging disabling certain sections, the issue was in the order notes calling `strippedHTML` which takes ~0.01s on average on my device. I tried the [WPiOS version](https://github.com/wordpress-mobile/WordPress-iOS-Shared/blob/bdfa2075e1331db720907e794cbc375e1db4dc46/WordPressShared/Core/Utility/NSString%2BHelpers.m#L243), and the time gets down to 1/60x of the WCiOS version. However, the WPiOS version of `strippedHTML` doesn’t pass the unit tests in WCiOS since there are some conventions of HTML escape characters and syntax like `&lt` and `<br>` needed in WCiOS.

I'm going to try asynchronously calling `strippedHTML` and perhaps caching it somewhere

**Comment by bummytime** [comment]
Nice sleuthing @jaclync. Releated: https://github.com/woocommerce/woocommerce-ios/pull/569#issuecomment-452090957

**Comment by jaclync** [comment]
@mindgraffiti I'm planning on working on this after Cesar's Order Details PR https://github.com/woocommerce/woocommerce-ios/pull/1077 to avoid merge conflicts

**Comment by ctarda** [comment]
I hate to be the blocker. Sorry about that. I will try to unlock #1077 today

**Comment by mindgraffiti** [comment]
Closing. No new reports made on this bug for more than a month 🎉
