### ISSUE TITLE
[Variable Product] - Variation name input starts with lowercase instead of uppercase

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#8692]
**Describe the bug**
When adding a new variation attribute name, the first letter is not capitalized, the merchant would need to do an extra tap to make it uppercase. This only happens on the add variation screen. 

**To Reproduce**
1. Go to Product > Add new product > Variable product > Add variation
2. Click on Add Attributes
3. Add a new attribute name
4. See that the first letter of the attribute name is in lowercase instead of uppercase

**Screenshots**

https://user-images.githubusercontent.com/17252150/213347348-9786c3ea-7257-4112-bf52-76bee4b83fca.MP4

**Expected behavior**
The keyboard should start with uppercase when typing the first letter of the attribute.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: iPhone 13 mini
- iOS version: 15.7.2
- WooCommerce iOS version: v11.8

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by reginabally** [comment]
I was able to fix this issue with a local build, but I have some questions about the code I'm about to commit.

1. The requirement is to capitalize the first letter of the attribute. What about attributes with multiple words? Do we capitalize the first letter in each word?
2. The way I managed to fix this is to add `UITextAutocapitalizationType` support in `WooCommerce.Classes.ViewRelated.ReusableViews.TextFieldTableViewCell`. However, changing this class impacted other controller classes like `ProductMenuOrderViewController`. Would this be okay? Or there is a better way of fixing this?

To help illustrate what I changed locally, the screenshot below shows the changes I made to `TextFieldTableViewCell`:

![Markup on 2023-01-29 at 19:32:17](https://user-images.githubusercontent.com/40906847/215323252-78d4465b-5a3f-4298-8150-dc73ace61520.png)

Fix for this issue in `AddAttributeViewController`:

![Markup on 2023-01-29 at 19:32:59](https://user-images.githubusercontent.com/40906847/215323284-caaa9318-674d-4ebe-9282-30cdc690fdad.png)

One of the other controllers that are impacted by this change:

![Markup on 2023-01-29 at 19:34:12](https://user-images.githubusercontent.com/40906847/215323309-535ed53d-a204-46ae-9f03-d657c922f9a8.png)

**Comment by ealeksandrov** [comment]
Thanks for taking this issue @reginabally!

Your solution is correct, but I recommend 1 minor change:
You've noticed that update to `TextFieldTableViewCell` can impact many different screens in the app, so when we extend its viewmodel with new option - we can add a default value that is equal to old behavior (`.none`), just like `var returnKeyType` is already implemented.

With default value provided, whole codebase will continue to behave as expected, without need to update any existing `TextFieldTableViewCell.ViewModel` initializers. But for the cases where we want custom capitalization logic (variations flow) we can add `autocapitalizationType` with desired value.

**Bonus:**
I also recommend improving `ViewModel` initializer. Right now to provide default values we need to change `let` to `var`. But we don't need mutable state in the viewmodel. It sets wrong expectations, we **can** change `var returnKeyType` from outside later - but it **won't** automatically trigger any updates to the cell/textfield.
Instead - right-click on `ViewModel` and tap "Refactor > Generate Memberwise Initializer". It will create initializer with all arguments and default values. Then we can update `returnKeyType` (and new `autocapitalizationType`) to `let` (and keep default value only in `init`).

<img width="805" alt="image" src="https://user-images.githubusercontent.com/3132438/215412129-374dafae-313c-4b09-8496-58030eda73a5.png">

Couple of nits unrelated to the issue:
- Feel free to create draft PR instead of sharing screenshots, so discussion can continue there. It's both ok to continue pushing changes to the draft or close it and push another one (when very different approach is chosen, for example).
- `Optional.none` on the last screenshot equals to `nil`. (Optional is [implemented as an enum](https://github.com/apple/swift/blob/3fd895a13da48fc4f545de2a90fa0dfef6540015/stdlib/public/core/Optional.swift#L121-L132).) It's not `UITextAutocapitalizationType.none`, while looks very similar. In your cell logic `nil` will anyway translate (through `??`) to `UITextAutocapitalizationType.none`, but passing `.none` of one type to get `.none` of another type is a bit confusing.

**Comment by reginabally** [comment]
Thank you so much for your input and guidance, @ealeksandrov! I will create a branch, commit the code and submit a PR for code review.
