### ISSUE TITLE
Order fulfillment: OrderID not necessary when fetching shipment providers

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#875]
Ref p99K0U-19V-p2. 

The v3 shipment tracking API [has been updated](https://github.com/woocommerce/woocommerce-shipment-tracking/pull/108). [Per the documentation](https://docs.woocommerce.com/document/shipment-tracking/), we no longer need to send the `order_id` as part of the request URL.

**Comment by toupper** [comment]
We are not using the [v3 API yet](https://github.com/woocommerce/woocommerce-ios/blob/06648338ee7f704128f57b8282527d91607553c6/Networking/Networking/Remote/ShipmentsRemote.swift#L18) so it seems more convenient to migrate to v3 first and then adapt the API call.
However, even with v3, it looks like this API endpoint still needs an `order_id` when fetching shipment tracking providers according to the documentation, [here](https://gist.github.com/gedex/cf3639918fdec31feceffd03eff7f3d4) and [here](https://gist.github.com/gedex/cf3639918fdec31feceffd03eff7f3d4): `GET /wp-json/wc-shipment-tracking/v3/orders/<order_id>/shipment-trackings/`

There is a similar discussion on this [issue](https://github.com/woocommerce/woomobile-private/issues/31) 

Because of this, I close this issue for now. If they adapt the documentation we can tackle this one again.
