### ISSUE TITLE
SPE: Update new product action sheet

### ISSUE THREAD

**Issue by ealeksandrov** [woocommerce/woocommerce-ios#8836]
- [ ] Merge template and type steps
- [ ] Show different template types for new/existing user

For first time user, we show:
- physical
- digital
- external

For existing users who have products we add:
- grouped

Blank should default to simple product type (physical).

no products|existing products
--|--
![Image](https://user-images.githubusercontent.com/3132438/218071165-e717cf7e-0d60-4388-95b0-6763c23fa61f.png)|![Image](https://user-images.githubusercontent.com/3132438/218071166-d07e9a83-3c88-4db6-967d-ce791ae6b5ef.png)

**Comment by rachelmcr** [comment]
Brief notes about this implementation:

* We can add the "Blank" product option to `BottomSheetProductType` and reuse the `ProductTypeBottomSheetListSelectorCommand`, updating the command data to select only the product types we want in the new bottom sheet.
* We can update `AppProductCoordinator` to show the new bottom sheet when the feature flag is enabled, instead of the current experience. This coordinator also has a products results controller we can reuse to decide if the grouped product type should be included in the command data.

**Comment by rachelmcr** [comment]
Note: With this change we need to support creating new products from two new template types that we didn't before (grouped and external).

Because of the template data the API returns for a grouped product, by default it will import several new products when the grouped product is created:

https://user-images.githubusercontent.com/8658164/220638575-084bad2e-11a1-42b3-94b0-ee0be7efad8e.mp4

That behavior is not ideal (the imported products have some odd formatting and need to be deleted individually) so we should be sure to clean up the template product to remove those grouped products before presenting the grouped product details.
