### ISSUE TITLE
Polish store setup card to match the design

### ISSUE THREAD

**Issue by jaclync** [woocommerce/woocommerce-ios#8907]
Done in - https://github.com/woocommerce/woocommerce-ios/pull/8948
- [x] Hide the divider for the last task
- [x] Show a chevron icon (`>`) at the trailing edge for each task 
- [x] Show a progress bar at the top with different alignments in the collapsed/expanded state
- [x] Show a "View all (#)" at the bottom to see the expanded state

Done in https://github.com/woocommerce/woocommerce-ios/pull/8991
- [x] Add padding with a different background color above & below the onboarding list
- [x] Collapsed state: only show up to 3 incomplete tasks
- [x] Update the navigation method so that the expanded state is a modal
- [x] Close button to dismiss modal

Done in https://github.com/woocommerce/woocommerce-ios/pull/9115
- [x] Use `Menu` instead of action sheet VyLr7LvKodHE4kINfBE7Lw-fi-1644:82305 - 

Done in https://github.com/woocommerce/woocommerce-ios/pull/9151
- [x] Add a way to show`PRIVATE` label to task VyLr7LvKodHE4kINfBE7Lw-fi-1644%3A82231 - 

**Pending**
- [ ] Ensure every icon & checkmark icon is the same size - p1679487928153459-slack-C045CUK1Y3U

**Comment by jaclync** [comment]
@selanthiraiyan I just added two subtasks to the issue description, they just came to mind when reviewing the PR.

**Comment by selanthiraiyan** [comment]
❓ about the below pending task

> Ensure every icon & checkmark icon is the same size

This happens because some image files (grid icons in this case) have padding added around them. And some don't. Please take a look at the image below.

#### Images with padding (GridIcons) | Images without padding
<img width="1194" alt="ImagePadding" src="https://user-images.githubusercontent.com/524475/226247922-5382265d-9f89-4b14-a10b-3a2114d498a3.png">


❓ Is there a way to remove the padding from the grid icons? Or should I fix this by exporting images without padding instead of using grid icons? 

Thank you!

--- 
**Update**
I raised this to design and got a resolution.

I should ignore the grid icons and export all the icons from the Figma file. The icons used in the Figma file have different padding/size than the grid icons. 

p1679487928153459-slack-C045CUK1Y3U
