### ISSUE TITLE
Dashboard: Add support for Dynamic Type to Chart labels

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-ios#896]
The labels in the chart do not change their size when users change their device's preferred font size.

![Simulator Screen Shot - iPhone 8 - 2019-04-23 at 08 32 05](https://user-images.githubusercontent.com/2722505/56543270-8fe90b00-65a3-11e9-9c43-ff0567867e75.png)

**Comment by mindgraffiti** [comment]
This is happening inside of the `Charts` framework. There is a GitHub ticket filed here: https://github.com/danielgindi/Charts/issues/1060.

**Comment by mindgraffiti** [comment]
So when it's time to work on this ticket, on a PR in the Charts framework, do the work there, and link back to this ticket.

**Comment by rachelmcr** [comment]
Confirming that the issue linked above in the `Charts` framework is still open, and this issue is still valid (checked in version 8.9.0.0):

<img src="https://user-images.githubusercontent.com/8658164/161779158-cecf47a3-9a9d-43b4-9c20-fe6dccecbafe.PNG" width="300px">

**Comment by rossanafmenezes** [comment]
I am cleaning up GH a bit and came across this issue. While the ChartOrgs issue does not seem to have been touched since 2018, I just tested it and the chart labels seem to be adjusting:

![photo_2024-08-22 14 14 49](https://github.com/user-attachments/assets/24e62bd2-6056-4964-badf-90628662766d)

![photo_2024-08-22 14 25 12](https://github.com/user-attachments/assets/e36de29d-86a0-45d0-b902-f9122433aa86)

https://github.com/user-attachments/assets/7bf4e13e-79c7-4e55-b590-6af193ced43b
