### ISSUE TITLE
[Product Multi-Selection] Make clearer that product variations have to be selected individually

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce-ios#9074]
From https://github.com/woocommerce/woocommerce-ios/pull/8943#issuecomment-1457672047

**Comment by jostnes** [comment]
just to add a suggestion, i was looking at the Android implementation, and on Android, tapping on any area of a variable product would redirect the product variation screen. perhaps the same can be done on iOS? so instead of not doing anything on tap, it will open the screen with all the product variations. wdyt?

**Comment by iamgabrielma** [comment]
> just to add a suggestion, i was looking at the Android implementation, and on Android, tapping on any area of a variable product would redirect the product variation screen. perhaps the same can be done on iOS? so instead of not doing anything on tap, it will open the screen with all the product variations. wdyt?

Yeah! That sounds about right 💯  the same idea was suggested [here](https://github.com/woocommerce/woocommerce-ios/pull/9079#pullrequestreview-1337542771).

**Comment by iamgabrielma** [comment]
Closed in favor of https://github.com/woocommerce/woocommerce-ios/issues/9120
