### ISSUE TITLE
[Products] - Incorrect product type screen displayed on create product

### ISSUE THREAD

**Issue by jostnes** [woocommerce/woocommerce-ios#9429]
**Describe the bug**
When creating a "grouped" or "external" product, the product screen displayed after product template creation doesn't show options for grouped or external products. Instead, it looks like the same screen as creating a physical/virtual product.

Using an example of creating a grouped product, after I tap to create "grouped product", the "creating template product" screen is displayed. I can see a POST request with this body when that happens:
`body=%7B%22template_name%22%3A%22grouped%22%7D&json=true&path=/wc-admin/onboarding/tasks/create_product_from_template%26_method%3Dpost`

When I land on the draft product screen, in the next call to display the draft product, I see `"type": "simple",` in the response body instead of `"type": "grouped",`. On the UI, the `grouped products` button that should be available for group product is also missing.

**To Reproduce**
1. Go to Products
2. Click on Add Product > Grouped product
3. On the product screen, see that for Grouped product, the "Grouped products" cell is not displayed
4. Repeat for other types of products and see that they all show the same screen

**Screenshots**

https://user-images.githubusercontent.com/17252150/231099453-4bc29736-e246-4190-8a99-e537d3abe1f9.mp4

**Expected behavior**
When creating a grouped or external product, on the product creation screen, I should see options related to those products (e.g. `grouped product` button ). 

**Mobile Environment**
Please include:
- Device: iPhone 13 mini
- iOS version: 15.7.1
- WooCommerce iOS version: v13.0 and v13.1

**Comment by rachelmcr** [comment]
This issue was related to the Simplify Product Editing experiment (treatment behavior). Closing this since we've removed the Simplify Product Editing experiment and it's no longer possible to create grouped and external products with a template:

<img src="https://github.com/woocommerce/woocommerce-ios/assets/8658164/8b6e06c0-5d87-4f20-9d41-830ff2697e02" width="300px">

When I add those product types manually, the correct blank product form is displayed:

Grouped|External
-|-
![Simulator Screenshot - iPhone 14 Pro - 2023-05-12 at 16 26 19](https://github.com/woocommerce/woocommerce-ios/assets/8658164/933216ce-c380-4575-89c8-b0f798240e8a)|![Simulator Screenshot - iPhone 14 Pro - 2023-05-12 at 16 26 13](https://github.com/woocommerce/woocommerce-ios/assets/8658164/ed4d5894-ab5c-4172-bed9-37db318950b2)
